from __future__ import annotations

import json

SOURCE = {
    "book": "新HSK教程1",
    "pdf_path": "HSK 3.0 PDF/新HSK教程1.pdf",
    "pdf_pages": [32, 33, 34, 35, 36, 37, 38, 39, 40],
    "printed_pages": [18, 19, 20, 21, 22, 23, 24, 25, 26],
    "rights_note": "Dialogue reuse permitted by project owner.",
    "extraction_status": "verified_from_rendered_pages",
}

LESSON = {
    "level": "nhsk1",
    "lesson_order": 4,
    "lesson_code": "NHSK1-L04",
    "title": "我有两个孩子",
    "title_pinyin": "Wǒ yǒu liǎng ge háizi",
    "goal": json.dumps(
        {
            "uz": "“有” orqali egalik va mavjudlikni ifodalash; sonlarni, “呢” savol yuklamasini va son+o‘lchov so‘zi tuzilmasini ishlatish; yosh va oila a’zolari haqida so‘rash va javob berish.",
            "ru": "Выражать наличие и обладание с “有”; использовать числа, вопросительную частицу “呢” и структуру число+счётное слово; спрашивать и отвечать о возрасте и семье.",
            "tj": "Бо “有” соҳибият ва мавҷудиятро ифода кардан; рақамҳо, ҳиссачаи саволии “呢” ва сохтори рақам+воҳиди ҳисобро истифода бурдан; дар бораи синну сол ва оила саволу ҷавоб кардан.",
        },
        ensure_ascii=False,
    ),
    "intro_text": json.dumps(
        {
            "uz": "Dars oila a’zolari, odam soni va yosh haqidagi uchta dialog orqali “有”, sonlar, “呢” va o‘lchov so‘zlarini o‘rgatadi.",
            "ru": "Урок через три диалога о семье, количестве людей и возрасте вводит “有”, числа, “呢” и счётные слова.",
            "tj": "Дарс тавассути се гуфтугӯ дар бораи оила, шумораи одамон ва синну сол “有”, рақамҳо, “呢” ва воҳидҳои ҳисобро меомӯзонад.",
        },
        ensure_ascii=False,
    ),
    "vocabulary_json": json.dumps(
        [
            {"no": 1, "zh": "有", "pinyin": "yǒu", "pos": "v.", "uz": "bor; ega bo‘lmoq", "ru": "иметь; есть", "tj": "доштан; ҳаст"},
            {"no": 2, "zh": "多少", "pinyin": "duōshao", "pos": "pron.", "uz": "qancha; nechta", "ru": "сколько", "tj": "чанд; чӣ қадар"},
            {"no": 3, "zh": "个", "pinyin": "gè", "pos": "m.", "uz": "umumiy o‘lchov so‘zi", "ru": "универсальное счётное слово", "tj": "воҳиди умумии ҳисоб"},
            {"no": 4, "zh": "哥哥", "pinyin": "gēge", "pos": "n.", "uz": "aka", "ru": "старший брат", "tj": "бародари калонӣ"},
            {"no": 5, "zh": "呢", "pinyin": "ne", "pos": "part.", "uz": "“-chi?” savol yuklamasi", "ru": "вопросительная частица «а…?»", "tj": "ҳиссачаи саволии «-чӣ?»"},
            {"no": 6, "zh": "没有", "pinyin": "méiyǒu", "pos": "v.", "uz": "yo‘q; ega emas", "ru": "не иметь; нет", "tj": "надоштан; нест"},
            {"no": 7, "zh": "家", "pinyin": "jiā", "pos": "n.", "uz": "oila; uy", "ru": "семья; дом", "tj": "оила; хона"},
            {"no": 8, "zh": "几", "pinyin": "jǐ", "pos": "pron.", "uz": "nechta", "ru": "сколько; несколько", "tj": "чанд"},
            {"no": 9, "zh": "口", "pinyin": "kǒu", "pos": "m.", "uz": "oila a’zolari uchun o‘lchov so‘zi", "ru": "счётное слово для членов семьи", "tj": "воҳиди ҳисоб барои аъзои оила"},
            {"no": 10, "zh": "爸爸", "pinyin": "bàba", "pos": "n.", "uz": "ota; dada", "ru": "папа", "tj": "падар; дада"},
            {"no": 11, "zh": "妈妈", "pinyin": "māma", "pos": "n.", "uz": "ona; mama", "ru": "мама", "tj": "модар; оча"},
            {"no": 12, "zh": "妹妹", "pinyin": "mèimei", "pos": "n.", "uz": "singil", "ru": "младшая сестра", "tj": "хоҳари хурдӣ"},
            {"no": 13, "zh": "和", "pinyin": "hé", "pos": "conj.", "uz": "va", "ru": "и", "tj": "ва"},
            {"no": 14, "zh": "儿子", "pinyin": "érzi", "pos": "n.", "uz": "o‘g‘il", "ru": "сын", "tj": "писар"},
            {"no": 15, "zh": "孩子", "pinyin": "háizi", "pos": "n.", "uz": "bola; farzand", "ru": "ребёнок; дети", "tj": "кӯдак; фарзанд"},
            {"no": 16, "zh": "女儿", "pinyin": "nǚ'ér", "pos": "n.", "uz": "qiz farzand", "ru": "дочь", "tj": "духтар"},
            {"no": 17, "zh": "岁", "pinyin": "suì", "pos": "m.", "uz": "yosh (yil)", "ru": "лет (возраст)", "tj": "сола (синну сол)"},
            {"no": 18, "zh": "他", "pinyin": "tā", "pos": "pron.", "uz": "u (erkak)", "ru": "он; его", "tj": "ӯ (мард)"},
            {"no": 19, "zh": "今年", "pinyin": "jīnnián", "pos": "n.", "uz": "bu yil", "ru": "этот год", "tj": "имсол"},
            {"no": 20, "zh": "多", "pinyin": "duō", "pos": "pron.", "uz": "qanchalik; necha", "ru": "насколько; сколько", "tj": "чӣ қадар; чанд"},
            {"no": 21, "zh": "大", "pinyin": "dà", "pos": "adj.", "uz": "katta; yosh (yosh so‘rashda)", "ru": "большой; старший по возрасту", "tj": "калон; синну сол"},
        ],
        ensure_ascii=False,
    ),
    "dialogue_json": json.dumps(
        [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_zh": "在家里，刘明和王一雪在聊天儿。",
                "scene_en": "At home, Liu Ming and Wang Yixue were chatting.",
                "scene_uz": "Uyda Liu Ming va Wang Yixue suhbatlashmoqda.",
                "scene_ru": "Дома Лю Мин и Ван Исюэ разговаривают.",
                "scene_tj": "Дар хона Лю Мин ва Ван Исюэ суҳбат мекунанд.",
                "dialogue": [
                    {"speaker": "Liu Ming", "zh": "一飞忙吗？", "pinyin": "Yīfēi máng ma?", "en": "Is Yifei busy?", "uz": "Yifei bandmi?", "ru": "Ифэй занята?", "tj": "Ифэй банд аст?"},
                    {"speaker": "Wang Yixue", "zh": "她很忙。", "pinyin": "Tā hěn máng.", "en": "She is very busy.", "uz": "U juda band.", "ru": "Она очень занята.", "tj": "Ӯ хеле банд аст."},
                    {"speaker": "Liu Ming", "zh": "她有多少个学生？", "pinyin": "Tā yǒu duōshao ge xuésheng?", "en": "How many students does she have?", "uz": "Uning nechta talabasi bor?", "ru": "Сколько у неё студентов?", "tj": "Ӯ чанд донишҷӯ дорад?"},
                    {"speaker": "Wang Yixue", "zh": "她有二十个学生。", "pinyin": "Tā yǒu èrshí ge xuésheng.", "en": "She has twenty students.", "uz": "Uning yigirmata talabasi bor.", "ru": "У неё двадцать студентов.", "tj": "Ӯ бист донишҷӯ дорад."},
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_zh": "在公司里，王一雪和杨同乐休息时聊天儿。",
                "scene_en": "At the company, Wang Yixue and Yang Tongle were chatting during a break.",
                "scene_uz": "Kompaniyada Wang Yixue va Yang Tongle tanaffus payti suhbatlashmoqda.",
                "scene_ru": "В компании Ван Исюэ и Ян Тунлэ разговаривают во время перерыва.",
                "scene_tj": "Дар ширкат Ван Исюэ ва Ян Тунлэ ҳангоми танаффус суҳбат мекунанд.",
                "dialogue": [
                    {"speaker": "Wang Yixue", "zh": "我有两个哥哥，你呢？", "pinyin": "Wǒ yǒu liǎng ge gēge, nǐ ne?", "en": "I have two elder brothers. How about you?", "uz": "Mening ikkita akam bor, sen-chi?", "ru": "У меня два старших брата. А у тебя?", "tj": "Ман ду бародари калон дорам, ту чӣ?"},
                    {"speaker": "Yang Tongle", "zh": "我没有哥哥。", "pinyin": "Wǒ méiyǒu gēge.", "en": "I don't have any elder brothers.", "uz": "Mening akam yo‘q.", "ru": "У меня нет старшего брата.", "tj": "Ман бародари калон надорам."},
                    {"speaker": "Wang Yixue", "zh": "你家有几口人？", "pinyin": "Nǐ jiā yǒu jǐ kǒu rén?", "en": "How many people are there in your family?", "uz": "Oilangda nechta odam bor?", "ru": "Сколько человек в твоей семье?", "tj": "Дар оилаи ту чанд нафар ҳаст?"},
                    {"speaker": "Yang Tongle", "zh": "我家有四口人，爸爸、妈妈、哥哥、妹妹和我。", "pinyin": "Wǒ jiā yǒu sì kǒu rén, bàba, māma, gēge, mèimei hé wǒ.", "en": "There are four people in my family: my dad, my mom, my younger sister, and me.", "uz": "Oilamda to‘rt kishi bor: dadam, onam, akam, singlim va men.", "ru": "В моей семье четыре человека: папа, мама, старший брат, младшая сестра и я.", "tj": "Дар оилаи ман чор нафар ҳаст: падар, модар, бародари калон, хоҳари хурдӣ ва ман."},
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_zh": "在街上，王一雪带着儿子偶遇杨同乐。",
                "scene_en": "On the street, Wang Yixue ran into Yang Tongle while she was out with her son.",
                "scene_uz": "Ko‘chada Wang Yixue o‘g‘li bilan ketayotib Yang Tonglega duch keladi.",
                "scene_ru": "На улице Ван Исюэ встречает Ян Тунлэ, гуляя с сыном.",
                "scene_tj": "Дар кӯча Ван Исюэ бо писараш рафта истода, бо Ян Тунлэ вомехӯрад.",
                "dialogue": [
                    {"speaker": "Yang Tongle", "zh": "这是您儿子吗？", "pinyin": "Zhè shì nín érzi ma?", "en": "Is this your son?", "uz": "Bu sizning o‘g‘lingizmi?", "ru": "Это ваш сын?", "tj": "Ин писари шумост?"},
                    {"speaker": "Wang Yixue", "zh": "是的。我有两个孩子，一个女儿，一个儿子。", "pinyin": "Shì de. Wǒ yǒu liǎng ge háizi, yí ge nǚ'ér, yí ge érzi.", "en": "Yes. I have two children, a daughter and a son.", "uz": "Ha. Mening ikki farzandim bor: bir qiz va bir o‘g‘il.", "ru": "Да. У меня двое детей: дочь и сын.", "tj": "Ҳа. Ман ду фарзанд дорам: як духтар ва як писар."},
                    {"speaker": "Yang Tongle", "zh": "您儿子几岁？", "pinyin": "Nín érzi jǐ suì?", "en": "How old is your son?", "uz": "O‘g‘lingiz necha yoshda?", "ru": "Сколько лет вашему сыну?", "tj": "Писари шумо чандсола аст?"},
                    {"speaker": "Wang Yixue", "zh": "他今年五岁。", "pinyin": "Tā jīnnián wǔ suì.", "en": "He is five years old.", "uz": "U bu yil besh yoshda.", "ru": "Ему в этом году пять лет.", "tj": "Ӯ имсол панҷсола аст."},
                    {"speaker": "Yang Tongle", "zh": "您女儿多大？", "pinyin": "Nín nǚ'ér duō dà?", "en": "How old is your daughter?", "uz": "Qizingiz necha yoshda?", "ru": "Сколько лет вашей дочери?", "tj": "Духтари шумо чандсола аст?"},
                    {"speaker": "Wang Yixue", "zh": "她今年十二。", "pinyin": "Tā jīnnián shí'èr.", "en": "She is twelve.", "uz": "U bu yil o‘n ikki yoshda.", "ru": "Ей двенадцать.", "tj": "Ӯ имсол дувоздаҳсола аст."},
                ],
            },
        ],
        ensure_ascii=False,
    ),
    "grammar_json": json.dumps(
        [
            {
                "no": 1,
                "title_zh": "“有”字句（1）",
                "title_uz": "“有” bilan gap (1)",
                "title_ru": "Предложение с “有” (1)",
                "title_tj": "Ҷумла бо “有” (1)",
                "rule_zh": "“有”表示领有，否定形式为“没/没有”。",
                "rule_en": "The word “有” indicates possession. Its negative form is “没/没有”.",
                "rule_uz": "“有” egalik yoki mavjudlikni bildiradi. Inkor shakli: 没/没有.",
                "rule_ru": "“有” выражает наличие/обладание. Отрицание: 没/没有.",
                "rule_tj": "“有” соҳибият ё мавҷудиятро ифода мекунад. Инкор: 没/没有.",
                "examples": [
                    {"zh": "她有二十个学生。", "pinyin": "Tā yǒu èrshí ge xuésheng.", "uz": "Uning yigirmata talabasi bor.", "ru": "У неё двадцать студентов.", "tj": "Ӯ бист донишҷӯ дорад."},
                    {"zh": "她没有一个姐姐。", "pinyin": "Tā méiyǒu yí ge jiějie.", "uz": "Uning opasi yo‘q.", "ru": "У неё нет старшей сестры.", "tj": "Ӯ хоҳари калон надорад."},
                    {"zh": "我没/没有姐姐。", "pinyin": "Wǒ méi/méiyǒu jiějie.", "uz": "Mening opam yo‘q.", "ru": "У меня нет старшей сестры.", "tj": "Ман хоҳари калон надорам."},
                ],
            },
            {
                "no": 2,
                "title_zh": "数字的表达",
                "title_uz": "Sonlarni ifodalash",
                "title_ru": "Выражение чисел",
                "title_tj": "Ифодаи рақамҳо",
                "rule_zh": "汉语中的数字可以用阿拉伯数字和汉字两种写法；“2”在不同结构中可读“二”或“两”。",
                "rule_en": "Numbers in Chinese can be written with Arabic numerals or Chinese characters; 2 may be pronounced 二 or 两 depending on the structure.",
                "rule_uz": "Xitoy tilida sonlar arab raqamlari yoki xitoycha belgilar bilan yoziladi; 2 ayrim tuzilmalarda 二, ayrimlarida 两 o‘qiladi.",
                "rule_ru": "Числа записываются арабскими цифрами или иероглифами; 2 читается 二 или 两 в зависимости от структуры.",
                "rule_tj": "Рақамҳо бо ададҳои арабӣ ё иероглифҳо навишта мешаванд; 2 вобаста ба сохтор 二 ё 两 хонда мешавад.",
                "examples": [
                    {"zh": "十二", "pinyin": "shí'èr", "uz": "o‘n ikki", "ru": "двенадцать", "tj": "дувоздаҳ"},
                    {"zh": "两个孩子", "pinyin": "liǎng ge háizi", "uz": "ikki farzand", "ru": "двое детей", "tj": "ду фарзанд"},
                ],
            },
            {
                "no": 3,
                "title_zh": "语气助词“呢”（1）",
                "title_uz": "“呢” modal yuklamasi (1)",
                "title_ru": "Модальная частица “呢” (1)",
                "title_tj": "Ҳиссачаи модалии “呢” (1)",
                "rule_zh": "“呢”在句末表示疑问，常用于反问或承接上文追问同类信息，基本结构：A……，B呢？",
                "rule_en": "The word “呢” is used at the end of a sentence to indicate a question, often asking the same type of information about another person or thing.",
                "rule_uz": "“呢” gap oxirida savol ma’nosini beradi, ko‘pincha “sen-chi?” kabi oldingi mavzuni davom ettiradi.",
                "rule_ru": "“呢” в конце предложения задаёт встречный вопрос по уже упомянутой теме: «а ты?».",
                "rule_tj": "“呢” дар охири ҷумла саволи ҷавобӣ медиҳад, масалан «ту чӣ?».",
                "examples": [
                    {"zh": "我有两个哥哥，你呢？", "pinyin": "Wǒ yǒu liǎng ge gēge, nǐ ne?", "uz": "Mening ikkita akam bor, sen-chi?", "ru": "У меня два старших брата, а у тебя?", "tj": "Ман ду бародари калон дорам, ту чӣ?"},
                    {"zh": "我叫白家月，你呢？", "pinyin": "Wǒ jiào Bái Jiāyuè, nǐ ne?", "uz": "Mening ismim Bai Jiayue, sen-chi?", "ru": "Меня зовут Бай Цзяюэ, а тебя?", "tj": "Номи ман Бай Ҷяюэ аст, ту чӣ?"},
                ],
            },
            {
                "no": 4,
                "title_zh": "名量词和名量结构",
                "title_uz": "O‘lchov so‘zlari va son+o‘lchov tuzilmasi",
                "title_ru": "Счётные слова и структура число+счётное слово",
                "title_tj": "Воҳидҳои ҳисоб ва сохтори рақам+воҳиди ҳисоб",
                "rule_zh": "汉语数量时，名词前通常要用名量词；常见结构：Num + M + (N)。",
                "rule_en": "When expressing quantity, a measure word is generally used before a noun. Common structure: Num + M + (N).",
                "rule_uz": "Miqdor ifodalanganda ot oldidan odatda o‘lchov so‘zi ishlatiladi: son + o‘lchov so‘zi + (ot).",
                "rule_ru": "При выражении количества перед существительным обычно используется счётное слово: число + счётное слово + (существительное).",
                "rule_tj": "Ҳангоми ифодаи миқдор пеш аз исм одатан воҳиди ҳисоб меояд: рақам + воҳиди ҳисоб + (исм).",
                "examples": [
                    {"zh": "一个", "pinyin": "yí ge", "uz": "bitta", "ru": "один (счётное слово 个)", "tj": "якто"},
                    {"zh": "四口人", "pinyin": "sì kǒu rén", "uz": "to‘rt kishi (oilada)", "ru": "четыре человека в семье", "tj": "чор нафар дар оила"},
                    {"zh": "两个学生", "pinyin": "liǎng ge xuésheng", "uz": "ikki talaba", "ru": "два студента", "tj": "ду донишҷӯ"},
                ],
            },
        ],
        ensure_ascii=False,
    ),
}
