from __future__ import annotations

import json

SOURCE = {
    "book": "新HSK教程1",
    "pdf_path": "HSK 3.0 PDF/新HSK教程1.pdf",
    "pdf_pages": [68, 69, 70, 71, 72, 73, 74],
    "printed_pages": [54, 55, 56, 57, 58, 59, 60],
    "rights_note": "Dialogue reuse permitted by project owner.",
    "extraction_status": "verified_from_rendered_pages",
}

LESSON = {
    "level": "nhsk1",
    "lesson_order": 8,
    "lesson_code": "NHSK1-L08",
    "title": "我爸爸也在医院工作",
    "title_pinyin": "Wǒ bàba yě zài yīyuàn gōngzuò",
    "goal": json.dumps(
        {
            "uz": "Joy, yo‘nalish va nisbiy o‘rinni tushunish va tasvirlash; joyni ko‘rsatish uchun “在” predlogini ishlatish; “能” bilan imkoniyat, sharoit yoki mumkinlikni ifodalash.",
            "ru": "Понимать и описывать местоположение, направление и относительное положение; использовать предлог “在” для обозначения места; выражать способность, условие или возможность с “能”.",
            "tj": "Ҷой, самт ва мавқеи нисбиро фаҳмидан ва тасвир кардан; барои нишон додани ҷой пешоянди “在”-ро истифода бурдан; бо “能” қобилият, шароит ё имконро ифода кардан.",
        },
        ensure_ascii=False,
    ),
    "intro_text": json.dumps(
        {
            "uz": "Dars mushukning joylashuvi, uchrashuv joyi va kasalxonadagi ish haqida uchta dialog orqali joylashuv so‘zlari, “在” va “能” ni o‘rgatadi.",
            "ru": "Урок через три диалога о местоположении котёнка, месте встречи и работе в больнице вводит слова местоположения, “在” и “能”.",
            "tj": "Дарс тавассути се гуфтугӯ дар бораи ҷойи гурба, ҷойи вохӯрӣ ва кори беморхона калимаҳои мавқеъ, “在” ва “能”-ро меомӯзонад.",
        },
        ensure_ascii=False,
    ),
    "vocabulary_json": json.dumps(
        [
            {"no": 1, "zh": "房间", "pinyin": "fángjiān", "pos": "n.", "uz": "xona", "ru": "комната", "tj": "ҳуҷра"},
            {"no": 2, "zh": "外", "pinyin": "wài", "pos": "n.", "uz": "tashqari; tashqarida", "ru": "снаружи; вне", "tj": "берун; беруни"},
            {"no": 3, "zh": "只", "pinyin": "zhī", "pos": "m.", "uz": "hayvonlar uchun o‘lchov so‘zi", "ru": "счётное слово для животных", "tj": "воҳиди ҳисоб барои ҳайвонот"},
            {"no": 4, "zh": "小", "pinyin": "xiǎo", "pos": "adj.", "uz": "kichik", "ru": "маленький", "tj": "хурд"},
            {"no": 5, "zh": "猫", "pinyin": "māo", "pos": "n.", "uz": "mushuk", "ru": "кошка", "tj": "гурба"},
            {"no": 6, "zh": "没", "pinyin": "méi", "pos": "adv.", "uz": "yo‘q; -magan", "ru": "не; ещё не", "tj": "не; ҳанӯз не"},
            {"no": 7, "zh": "看见", "pinyin": "kànjiàn", "pos": "v.", "uz": "ko‘rib qolmoq; ko‘rmoq", "ru": "увидеть; заметить", "tj": "дидан; пай бурдан"},
            {"no": 8, "zh": "桌子", "pinyin": "zhuōzi", "pos": "n.", "uz": "stol", "ru": "стол", "tj": "миз"},
            {"no": 9, "zh": "下", "pinyin": "xià", "pos": "n.", "uz": "past; ost", "ru": "низ; под", "tj": "поён; зери"},
            {"no": 10, "zh": "漂亮", "pinyin": "piàoliang", "pos": "adj.", "uz": "chiroyli", "ru": "красивый", "tj": "зебо"},
            {"no": 11, "zh": "在", "pinyin": "zài", "pos": "prep.", "uz": "da; joyda", "ru": "в; на; у", "tj": "дар; назди"},
            {"no": 12, "zh": "学校", "pinyin": "xuéxiào", "pos": "n.", "uz": "maktab; o‘quv yurti", "ru": "школа; учебное заведение", "tj": "мактаб; муассисаи таълимӣ"},
            {"no": 13, "zh": "书店", "pinyin": "shūdiàn", "pos": "n.", "uz": "kitob do‘koni", "ru": "книжный магазин", "tj": "мағозаи китоб"},
            {"no": 14, "zh": "前", "pinyin": "qián", "pos": "n.", "uz": "old; oldi", "ru": "перед; впереди", "tj": "пеш; пеши"},
            {"no": 15, "zh": "能", "pinyin": "néng", "pos": "mod.", "uz": "qila olmoq; mumkin bo‘lmoq", "ru": "мочь; быть в состоянии", "tj": "тавонистан; мумкин будан"},
            {"no": 16, "zh": "到", "pinyin": "dào", "pos": "v.", "uz": "yetib bormoq", "ru": "прибывать; достигать", "tj": "расидан"},
            {"no": 17, "zh": "午饭", "pinyin": "wǔfàn", "pos": "n.", "uz": "tushlik", "ru": "обед", "tj": "хӯроки нисфирӯзӣ"},
            {"no": 18, "zh": "饭", "pinyin": "fàn", "pos": "n.", "uz": "ovqat", "ru": "еда; приём пищи", "tj": "хӯрок"},
            {"no": 19, "zh": "大", "pinyin": "dà", "pos": "adj.", "uz": "katta", "ru": "большой", "tj": "калон"},
            {"no": 20, "zh": "病人", "pinyin": "bìngrén", "pos": "n.", "uz": "bemor", "ru": "пациент; больной", "tj": "бемор"},
            {"no": 21, "zh": "多", "pinyin": "duō", "pos": "adj.", "uz": "ko‘p", "ru": "много", "tj": "бисёр"},
            {"no": 22, "zh": "医生", "pinyin": "yīshēng", "pos": "n.", "uz": "shifokor", "ru": "врач", "tj": "духтур"},
            {"no": 23, "zh": "工作", "pinyin": "gōngzuò", "pos": "v.", "uz": "ishlamoq", "ru": "работать", "tj": "кор кардан"},
        ],
        ensure_ascii=False,
    ),
    "proper_nouns_json": json.dumps(
        [{"zh": "胡医生", "pinyin": "Hú yīshēng", "en": "Dr. Hu", "uz": "Doktor Hu", "ru": "доктор Ху", "tj": "духтур Ҳу"}],
        ensure_ascii=False,
    ),
    "dialogue_json": json.dumps(
        [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_zh": "在王一飞家，白家月和陈天中来做客。",
                "scene_en": "At Wang Yifei's home, Bai Jiayue and Chen Tianzhong came over for a visit.",
                "scene_uz": "Wang Yifeining uyida Bai Jiayue va Chen Tianzhong mehmonga kelgan.",
                "scene_ru": "Бай Цзяюэ и Чэнь Тяньчжун пришли в гости к Ван Ифэй.",
                "scene_tj": "Бай Ҷяюэ ва Чэн Тянҷун ба хонаи Ван Ифэй меҳмон шудаанд.",
                "dialogue": [
                    {"speaker": "Bai Jiayue", "zh": "房间外有一只小猫。", "pinyin": "Fángjiān wài yǒu yì zhī xiǎomāo.", "en": "There is a little cat outside the room.", "uz": "Xona tashqarisida bitta kichik mushuk bor.", "ru": "Снаружи комнаты есть маленький котёнок.", "tj": "Берун аз ҳуҷра як гурбачаи хурд ҳаст."},
                    {"speaker": "Chen Tianzhong", "zh": "我没看见，它在哪儿呢？", "pinyin": "Wǒ méi kànjiàn, tā zài nǎr ne?", "en": "I don't see it. Where is it?", "uz": "Men uni ko‘rmadim, u qayerda?", "ru": "Я его не вижу. Где он?", "tj": "Ман онро надидам, он куҷост?"},
                    {"speaker": "Bai Jiayue", "zh": "它在桌子下呢。", "pinyin": "Tā zài zhuōzi xià ne.", "en": "It's under the table.", "uz": "U stol ostida.", "ru": "Он под столом.", "tj": "Он зери миз аст."},
                    {"speaker": "Chen Tianzhong", "zh": "这只小猫真漂亮！", "pinyin": "Zhè zhī xiǎomāo zhēn piàoliang!", "en": "This little cat is so beautiful!", "uz": "Bu kichik mushuk juda chiroyli!", "ru": "Этот котёнок очень красивый!", "tj": "Ин гурбачаи хурд хеле зебост!"},
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_zh": "在教室里，下课后，白家月给李文打电话。",
                "scene_en": "After class, Bai Jiayue was calling Li Wen in the classroom.",
                "scene_uz": "Darsdan keyin sinfda Bai Jiayue Li Wenga telefon qilmoqda.",
                "scene_ru": "После занятия Бай Цзяюэ звонит Ли Вэню из аудитории.",
                "scene_tj": "Пас аз дарс Бай Ҷяюэ аз синф ба Ли Вэн занг мезанад.",
                "dialogue": [
                    {"speaker": "Bai Jiayue", "zh": "我们在哪儿见呢？", "pinyin": "Wǒmen zài nǎr jiàn ne?", "en": "Where shall we meet?", "uz": "Qayerda uchrashamiz?", "ru": "Где мы встретимся?", "tj": "Дар куҷо вомехӯрем?"},
                    {"speaker": "Li Wen", "zh": "在学校书店前面见吧。", "pinyin": "Zài xuéxiào shūdiàn qiánmiàn jiàn ba.", "en": "Let's meet in front of the school bookstore.", "uz": "Maktab kitob do‘koni oldida uchrashaylik.", "ru": "Давай встретимся перед школьным книжным магазином.", "tj": "Биёед пеши мағозаи китоби мактаб вохӯрем."},
                    {"speaker": "Bai Jiayue", "zh": "好的。下午两点你能到吗？", "pinyin": "Hǎo de. Xiàwǔ liǎng diǎn nǐ néng dào ma?", "en": "Okay. Can you arrive at 2:00 in the afternoon?", "uz": "Xo‘p. Tushdan keyin soat 2 da yetib kela olasanmi?", "ru": "Хорошо. Ты сможешь прийти в 2 часа дня?", "tj": "Хуб. Баъди нисфирӯзӣ соати 2 расида метавонӣ?"},
                    {"speaker": "Li Wen", "zh": "我能到。我在学校吃午饭。", "pinyin": "Wǒ néng dào. Wǒ zài xuéxiào chī wǔfàn.", "en": "Yes, I can. I'll have lunch at school.", "uz": "Yetib kela olaman. Men maktabda tushlik qilaman.", "ru": "Да, смогу. Я пообедаю в школе.", "tj": "Расида метавонам. Ман дар мактаб хӯроки нисфирӯзӣ мехӯрам."},
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_zh": "在医院里，刘明和胡医生在聊天儿。",
                "scene_en": "In the hospital, Liu Ming was chatting with Dr. Hu.",
                "scene_uz": "Kasalxonada Liu Ming doktor Hu bilan suhbatlashmoqda.",
                "scene_ru": "В больнице Лю Мин разговаривает с доктором Ху.",
                "scene_tj": "Дар беморхона Лю Мин бо духтур Ҳу суҳбат мекунад.",
                "dialogue": [
                    {"speaker": "Liu Ming", "zh": "小胡，还没吃饭呢？", "pinyin": "Xiǎo Hú, hái méi chī fàn ne?", "en": "Xiao Hu, haven't you eaten yet?", "uz": "Xiao Hu, hali ovqat yemadingmi?", "ru": "Сяо Ху, ты ещё не ел?", "tj": "Сяо Ҳу, ҳоло ҳам хӯрок нахӯрдаӣ?"},
                    {"speaker": "Dr. Hu", "zh": "没吃呢。", "pinyin": "Méi chī ne.", "en": "No, I haven't.", "uz": "Yo‘q, yemadim.", "ru": "Нет, ещё не ел.", "tj": "Не, ҳоло нахӯрдаам."},
                    {"speaker": "Liu Ming", "zh": "大医院病人多，医生非常忙。", "pinyin": "Dà yīyuàn bìngrén duō, yīshēng fēicháng máng.", "en": "There are a lot of patients in big hospitals, and doctors are very busy.", "uz": "Katta kasalxonalarda bemorlar ko‘p, shifokorlar juda band.", "ru": "В больших больницах много пациентов, и врачи очень заняты.", "tj": "Дар беморхонаҳои калон беморон бисёранд ва духтурон хеле банданд."},
                    {"speaker": "Dr. Hu", "zh": "是的。我爸爸也在医院工作，他也非常忙。", "pinyin": "Shì de. Wǒ bàba yě zài yīyuàn gōngzuò, tā yě fēicháng máng.", "en": "That's right. My father also works at a hospital, and he's extremely busy too.", "uz": "Ha. Otam ham kasalxonada ishlaydi, u ham juda band.", "ru": "Да. Мой отец тоже работает в больнице и тоже очень занят.", "tj": "Ҳа. Падарам ҳам дар беморхона кор мекунад ва ӯ ҳам хеле банд аст."},
                    {"speaker": "Liu Ming", "zh": "你家有两个医生？", "pinyin": "Nǐ jiā yǒu liǎng ge yīshēng?", "en": "So there are two doctors in your family?", "uz": "Demak, oilangda ikkita shifokor bor?", "ru": "Значит, в вашей семье два врача?", "tj": "Пас, дар оилаи шумо ду духтур ҳаст?"},
                    {"speaker": "Dr. Hu", "zh": "对。", "pinyin": "Duì.", "en": "Yes.", "uz": "Ha.", "ru": "Да.", "tj": "Ҳа."},
                ],
            },
        ],
        ensure_ascii=False,
    ),
    "grammar_json": json.dumps(
        [
            {
                "no": 1,
                "title_zh": "方位词",
                "title_uz": "Joylashuv so‘zlari",
                "title_ru": "Слова местоположения",
                "title_tj": "Калимаҳои мавқеъ",
                "rule_zh": "本册学习的表达方位、位置的方位词有：上、下、里、前、后、外、外边。",
                "rule_en": "The positional words expressing direction and location in this volume include 上, 下, 里, 前, 后, 外 and 外边.",
                "rule_uz": "Bu bosqichda joy va yo‘nalishni ifodalovchi 上、下、里、前、后、外、外边 o‘rganiladi.",
                "rule_ru": "В этом уровне изучаются слова местоположения 上、下、里、前、后、外、外边.",
                "rule_tj": "Дар ин сатҳ калимаҳои мавқеи 上、下、里、前、后、外、外边 омӯхта мешаванд.",
                "examples": [
                    {"zh": "房间里有一只小猫。", "pinyin": "Fángjiān lǐ yǒu yì zhī xiǎomāo.", "uz": "Xona ichida kichik mushuk bor.", "ru": "В комнате есть котёнок.", "tj": "Дар ҳуҷра як гурбачаи хурд ҳаст."},
                    {"zh": "我们去书店外吧。", "pinyin": "Wǒmen qù shūdiàn wài ba.", "uz": "Kitob do‘koni tashqarisiga boraylik.", "ru": "Давай пойдём к книжному магазину снаружи.", "tj": "Биёед ба беруни мағозаи китоб равем."},
                    {"zh": "小猫的手机在桌子上呢。", "pinyin": "Xiǎomāo de shǒujī zài zhuōzi shàng ne.", "uz": "Mushukning telefoni stol ustida.", "ru": "Телефон котёнка на столе.", "tj": "Телефони гурба рӯйи миз аст."},
                ],
            },
            {
                "no": 2,
                "title_zh": "介词“在”",
                "title_uz": "Predlog “在”",
                "title_ru": "Предлог “在”",
                "title_tj": "Пешоянди “在”",
                "rule_zh": "介词“在”和表示位置、处所的词语组合，在动词前面，表示在什么位置、处所做什么。",
                "rule_en": "The preposition “在” is used with words or phrases that indicate a location or place and is placed before the verb to show where an action takes place.",
                "rule_uz": "“在” joyni bildiruvchi so‘z yoki birikma bilan kelib, fe’l oldidan harakat qayerda sodir bo‘lishini ko‘rsatadi.",
                "rule_ru": "“在” сочетается с обозначением места и ставится перед глаголом, показывая, где происходит действие.",
                "rule_tj": "“在” бо калима ё ибораи ҷой омада, пеш аз феъл нишон медиҳад, ки амал дар куҷо сурат мегирад.",
                "examples": [
                    {"zh": "我在学校吃午饭。", "pinyin": "Wǒ zài xuéxiào chī wǔfàn.", "uz": "Men maktabda tushlik qilaman.", "ru": "Я обедаю в школе.", "tj": "Ман дар мактаб хӯроки нисфирӯзӣ мехӯрам."},
                    {"zh": "他爸爸在医院工作。", "pinyin": "Tā bàba zài yīyuàn gōngzuò.", "uz": "Uning otasi kasalxonada ishlaydi.", "ru": "Его отец работает в больнице.", "tj": "Падараш дар беморхона кор мекунад."},
                    {"zh": "你在哪儿买菜？", "pinyin": "Nǐ zài nǎr mǎi cài?", "uz": "Sabzavotni qayerda sotib olasan?", "ru": "Где ты покупаешь овощи?", "tj": "Ту сабзавотро дар куҷо мехарӣ?"},
                ],
            },
            {
                "no": 3,
                "title_zh": "能愿动词“能”",
                "title_uz": "Modal fe’l “能”",
                "title_ru": "Модальный глагол “能”",
                "title_tj": "Феъли модалии “能”",
                "rule_zh": "“能”放在动词前面，表示有能力、有条件或可能做某事。",
                "rule_en": "The modal verb “能” is placed before a verb to indicate the ability, condition, or possibility of doing something.",
                "rule_uz": "“能” fe’l oldidan kelib biror ishni qilish qobiliyati, sharoiti yoki imkoniyati borligini bildiradi.",
                "rule_ru": "“能” ставится перед глаголом и выражает способность, наличие условий или возможность выполнить действие.",
                "rule_tj": "“能” пеш аз феъл омада, қобилият, шароит ё имкони иҷрои амалро ифода мекунад.",
                "examples": [
                    {"zh": "下午两点你能到吗？", "pinyin": "Xiàwǔ liǎng diǎn nǐ néng dào ma?", "uz": "Tushdan keyin soat 2 da kela olasanmi?", "ru": "Ты сможешь прийти в 2 часа дня?", "tj": "Баъди нисфирӯзӣ соати 2 расида метавонӣ?"},
                    {"zh": "爸爸能来。", "pinyin": "Bàba néng lái.", "uz": "Otam kela oladi.", "ru": "Папа сможет прийти.", "tj": "Падарам омада метавонад."},
                    {"zh": "我不能去学校吃午饭。", "pinyin": "Wǒ bù néng qù xuéxiào chī wǔfàn.", "uz": "Men maktabga tushlik qilgani bora olmayman.", "ru": "Я не могу пойти в школу пообедать.", "tj": "Ман барои нисфирӯзӣ ба мактаб рафта наметавонам."},
                ],
            },
        ],
        ensure_ascii=False,
    ),
}
