from __future__ import annotations

import json

SOURCE = {
    "book": "新HSK教程1",
    "pdf_path": "HSK 3.0 PDF/新HSK教程1.pdf",
    "pdf_pages": [75, 76, 77, 78, 79, 80, 81, 82, 83],
    "printed_pages": [61, 62, 63, 64, 65, 66, 67, 68, 69],
    "rights_note": "Dialogue reuse permitted by project owner.",
    "extraction_status": "verified_from_rendered_pages",
}

LESSON = {
    "level": "nhsk1",
    "lesson_order": 9,
    "lesson_code": "NHSK1-L09",
    "title": "我明天上午在学校学习",
    "title_pinyin": "Wǒ míngtiān shàngwǔ zài xuéxiào xuéxí",
    "goal": json.dumps(
        {
            "uz": "“有/是” bilan mavjudlikni ifodalovchi gaplarni ishlatish; vaqt va joy birga hol bo‘lganda ularning tartibini to‘g‘ri qo‘llash; “第” bilan tartib sonlarini yasash; zamonaviy xitoyliklarning bo‘sh vaqt mashg‘ulotlari haqida tushunish.",
            "ru": "Использовать предложения существования с “有/是”; правильно располагать время и место, когда оба являются обстоятельствами; образовывать порядковые числительные с “第”; понимать лексику повседневного досуга.",
            "tj": "Ҷумлаҳои мавҷудиятро бо “有/是” истифода бурдан; ҳангоми ҳамзамон ҳол будани вақт ва ҷой тартиби онҳоро дуруст гузоштан; бо “第” шумораҳои тартибиро сохтан; луғати фароғати рӯзмарраро фаҳмидан.",
        },
        ensure_ascii=False,
    ),
    "intro_text": json.dumps(
        {
            "uz": "Dars kinoteatr, kitob va dam olish kunidagi mashg‘ulotlar haqidagi uchta dialog orqali mavjudlik gaplari, vaqt+joy tartibi va “第” ni o‘rgatadi.",
            "ru": "Урок через три диалога о кинотеатре, книге и занятиях в выходной вводит экзистенциальные предложения, порядок время+место и “第”.",
            "tj": "Дарс тавассути се гуфтугӯ дар бораи кинотеатр, китоб ва машғулиятҳои рӯзи истироҳат ҷумлаҳои мавҷудият, тартиби вақт+ҷой ва “第”-ро меомӯзонад.",
        },
        ensure_ascii=False,
    ),
    "vocabulary_json": json.dumps(
        [
            {"no": 1, "zh": "前边", "pinyin": "qiánbian", "pos": "n.", "uz": "old tomoni; oldida", "ru": "передняя сторона; впереди", "tj": "пеш; тарафи пеш"},
            {"no": 2, "zh": "边", "pinyin": "biān/bian", "pos": "suf./n.", "uz": "tomon; chet", "ru": "сторона; край", "tj": "тараф; канор"},
            {"no": 3, "zh": "家", "pinyin": "jiā", "pos": "m.", "uz": "tashkilot/korxona uchun o‘lchov so‘zi", "ru": "счётное слово для семей/предприятий", "tj": "воҳиди ҳисоб барои оила/корхона"},
            {"no": 4, "zh": "那个", "pinyin": "nàge", "pos": "pron.", "uz": "ana u; o‘sha", "ru": "тот", "tj": "он; ҳамон"},
            {"no": 5, "zh": "外边", "pinyin": "wàibian", "pos": "n.", "uz": "tashqarida; tashqi tomon", "ru": "снаружи; внешняя сторона", "tj": "берун; тарафи берун"},
            {"no": 6, "zh": "椅子", "pinyin": "yǐzi", "pos": "n.", "uz": "stul", "ru": "стул", "tj": "курсӣ"},
            {"no": 7, "zh": "上", "pinyin": "shàng", "pos": "n.", "uz": "ust; yuqori tomon", "ru": "верх; на", "tj": "боло; рӯйи"},
            {"no": 8, "zh": "本", "pinyin": "běn", "pos": "m.", "uz": "kitoblar uchun o‘lchov so‘zi", "ru": "счётное слово для книг", "tj": "воҳиди ҳисоб барои китоб"},
            {"no": 9, "zh": "书", "pinyin": "shū", "pos": "n.", "uz": "kitob", "ru": "книга", "tj": "китоб"},
            {"no": 10, "zh": "那", "pinyin": "nà", "pos": "pron.", "uz": "u; o‘sha", "ru": "тот; та", "tj": "он; ҳамон"},
            {"no": 11, "zh": "第", "pinyin": "dì", "pos": "pref.", "uz": "tartib son belgisi", "ru": "показатель порядкового числа", "tj": "нишондиҳандаи шумораи тартибӣ"},
            {"no": 12, "zh": "学习", "pinyin": "xuéxí", "pos": "v.", "uz": "o‘qimoq; o‘rganmoq", "ru": "учиться; изучать", "tj": "хондан; омӯхтан"},
            {"no": 13, "zh": "做", "pinyin": "zuò", "pos": "v.", "uz": "qilmoq; shug‘ullanmoq", "ru": "делать; заниматься", "tj": "кардан; машғул шудан"},
            {"no": 14, "zh": "白天", "pinyin": "báitiān", "pos": "n.", "uz": "kunduz", "ru": "днём; дневное время", "tj": "рӯзона"},
            {"no": 15, "zh": "读书", "pinyin": "dúshū", "pos": "v.", "uz": "kitob o‘qimoq", "ru": "читать; учиться", "tj": "китоб хондан"},
            {"no": 16, "zh": "和", "pinyin": "hé", "pos": "prep.", "uz": "bilan", "ru": "с", "tj": "бо"},
            {"no": 17, "zh": "朋友", "pinyin": "péngyou", "pos": "n.", "uz": "do‘st", "ru": "друг", "tj": "дӯст"},
            {"no": 18, "zh": "唱歌", "pinyin": "chànggē", "pos": "v.", "uz": "qo‘shiq aytmoq", "ru": "петь", "tj": "суруд хондан"},
            {"no": 19, "zh": "歌", "pinyin": "gē", "pos": "n.", "uz": "qo‘shiq", "ru": "песня", "tj": "суруд"},
            {"no": 20, "zh": "好听", "pinyin": "hǎotīng", "pos": "adj.", "uz": "yoqimli eshitiladigan", "ru": "приятный на слух", "tj": "хушсадо"},
            {"no": 21, "zh": "电视", "pinyin": "diànshì", "pos": "n.", "uz": "televizor; televideniye", "ru": "телевизор; телевидение", "tj": "телевизор; телевизион"},
            {"no": 22, "zh": "狗", "pinyin": "gǒu", "pos": "n.", "uz": "it", "ru": "собака", "tj": "саг"},
            {"no": 23, "zh": "玩", "pinyin": "wán", "pos": "v.", "uz": "o‘ynamoq; hordiq chiqarmoq", "ru": "играть; развлекаться", "tj": "бозӣ кардан; вақтхушӣ кардан"},
        ],
        ensure_ascii=False,
    ),
    "dialogue_json": json.dumps(
        [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_zh": "在校园里，李文和白家月在聊天儿。",
                "scene_en": "On campus, Li Wen and Bai Jiayue were chatting.",
                "scene_uz": "Kampusda Li Wen va Bai Jiayue suhbatlashmoqda.",
                "scene_ru": "В кампусе Ли Вэнь и Бай Цзяюэ разговаривают.",
                "scene_tj": "Дар кампус Ли Вэн ва Бай Ҷяюэ суҳбат мекунанд.",
                "dialogue": [
                    {"speaker": "Li Wen", "zh": "学校前边有一家电影院。", "pinyin": "Xuéxiào qiánbian yǒu yì jiā diànyǐngyuàn.", "en": "There is a cinema in front of the school.", "uz": "Maktab oldida bitta kinoteatr bor.", "ru": "Перед школой есть кинотеатр.", "tj": "Пеши мактаб як кинотеатр ҳаст."},
                    {"speaker": "Bai Jiayue", "zh": "对。我们晚上去那个电影院看电影吧。", "pinyin": "Duì. Wǒmen wǎnshang qù nàge diànyǐngyuàn kàn diànyǐng ba.", "en": "Yes. Let's go to the cinema to watch a movie tonight.", "uz": "Ha. Bugun kechqurun o‘sha kinoteatrga film ko‘rgani boraylik.", "ru": "Да. Давай вечером пойдём в тот кинотеатр посмотреть фильм.", "tj": "Ҳа. Биёед шом ба ҳамон кинотеатр барои тамошои филм равем."},
                    {"speaker": "Li Wen", "zh": "好！我们七点在电影院外边见，好吗？", "pinyin": "Hǎo! Wǒmen qī diǎn zài diànyǐngyuàn wàibian jiàn, hǎo ma?", "en": "Great! Let's meet outside the cinema at 7:00, okay?", "uz": "Yaxshi! Soat 7 da kinoteatr tashqarisida uchrashamiz, maylimi?", "ru": "Хорошо! Встретимся в 7 часов у кинотеатра, ладно?", "tj": "Хуб! Соати 7 беруни кинотеатр вомехӯрем, майлаш?"},
                    {"speaker": "Bai Jiayue", "zh": "好的，晚上七点见！", "pinyin": "Hǎo de, wǎnshang qī diǎn jiàn!", "en": "Okay, see you at 7:00 in the evening!", "uz": "Xo‘p, kechqurun soat 7 da ko‘rishamiz!", "ru": "Хорошо, увидимся в 7 вечера!", "tj": "Хуб, шом соати 7 мебинем!"},
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_zh": "在教室里，下课后，白家月和陈天中在对话。",
                "scene_en": "After class, Bai Jiayue and Chen Tianzhong were talking in the classroom.",
                "scene_uz": "Darsdan keyin sinfda Bai Jiayue va Chen Tianzhong suhbatlashmoqda.",
                "scene_ru": "После занятия Бай Цзяюэ и Чэнь Тяньчжун разговаривают в аудитории.",
                "scene_tj": "Пас аз дарс Бай Ҷяюэ ва Чэн Тянҷун дар синф суҳбат мекунанд.",
                "dialogue": [
                    {"speaker": "Bai Jiayue", "zh": "椅子上有一本中文书，那是谁的书？", "pinyin": "Yǐzi shàng yǒu yì běn Zhōngwén shū, nà shì shéi de shū?", "en": "There is a Chinese book on the chair. Whose book is that?", "uz": "Stul ustida bitta xitoycha kitob bor. U kimning kitobi?", "ru": "На стуле лежит книга на китайском. Чья это книга?", "tj": "Рӯйи курсӣ як китоби чинӣ ҳаст. Он китоби кист?"},
                    {"speaker": "Chen Tianzhong", "zh": "是我的书，谢谢。这是我的第二本中文书。", "pinyin": "Shì wǒ de shū, xièxie. Zhè shì wǒ de dì èr běn Zhōngwén shū.", "en": "It is my book. Thank you. This is my second Chinese book.", "uz": "Bu mening kitobim, rahmat. Bu mening ikkinchi xitoycha kitobim.", "ru": "Это моя книга, спасибо. Это моя вторая книга на китайском.", "tj": "Ин китоби ман аст, раҳмат. Ин китоби дуюми чинии ман аст."},
                    {"speaker": "Bai Jiayue", "zh": "不客气。你明天上午在哪儿？", "pinyin": "Bú kèqi. Nǐ míngtiān shàngwǔ zài nǎr?", "en": "You're welcome. Where will you be tomorrow morning?", "uz": "Arzimaydi. Ertaga ertalab qayerda bo‘lasan?", "ru": "Не за что. Где ты будешь завтра утром?", "tj": "Марҳамат. Фардо субҳ дар куҷо мешавӣ?"},
                    {"speaker": "Chen Tianzhong", "zh": "我明天上午在学校学习。", "pinyin": "Wǒ míngtiān shàngwǔ zài xuéxiào xuéxí.", "en": "I'll be studying at school tomorrow morning.", "uz": "Men ertaga ertalab maktabda o‘qiyman.", "ru": "Завтра утром я буду заниматься в школе.", "tj": "Ман фардо субҳ дар мактаб таҳсил мекунам."},
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_zh": "在办公室里，休息时，王一雪和杨同乐谈论周末生活。",
                "scene_en": "In the office, Wang Yixue and Yang Tongle were talking about their weekend lives during a break.",
                "scene_uz": "Ofisda tanaffus payti Wang Yixue va Yang Tongle dam olish kunlari haqida suhbatlashmoqda.",
                "scene_ru": "В офисе во время перерыва Ван Исюэ и Ян Тунлэ обсуждают выходные.",
                "scene_tj": "Дар идора ҳангоми танаффус Ван Исюэ ва Ян Тунлэ дар бораи рӯзҳои истироҳат суҳбат мекунанд.",
                "dialogue": [
                    {"speaker": "Wang Yixue", "zh": "明天星期六，你做什么？", "pinyin": "Míngtiān Xīngqīliù, nǐ zuò shénme?", "en": "Tomorrow is Saturday. What are you going to do?", "uz": "Ertaga shanba. Nima qilasan?", "ru": "Завтра суббота. Что будешь делать?", "tj": "Фардо шанбе. Чӣ кор мекунӣ?"},
                    {"speaker": "Yang Tongle", "zh": "我白天在家里读书，晚上和朋友们一起看电影。", "pinyin": "Wǒ báitiān zài jiālǐ dú shū, wǎnshang hé péngyoumen yìqǐ kàn diànyǐng.", "en": "I will read at home during the day and go out to see a movie with my friends in the evening.", "uz": "Kunduz uyda kitob o‘qiyman, kechqurun do‘stlarim bilan birga film ko‘raman.", "ru": "Днём я буду читать дома, а вечером смотреть фильм с друзьями.", "tj": "Рӯзона дар хона китоб мехонам, шом бо дӯстонам якҷо филм тамошо мекунам."},
                    {"speaker": "Wang Yixue", "zh": "你唱歌很好听。", "pinyin": "Nǐ chànggē hěn hǎotīng.", "en": "You sing very well.", "uz": "Sen juda chiroyli kuylaysan.", "ru": "Ты очень хорошо поёшь.", "tj": "Ту хеле хуш месароӣ."},
                    {"speaker": "Yang Tongle", "zh": "谢谢！您星期六做什么？", "pinyin": "Xièxie! Nín Xīngqīliù zuò shénme?", "en": "Thank you! What will you do on Saturday?", "uz": "Rahmat! Siz shanba kuni nima qilasiz?", "ru": "Спасибо! Что вы будете делать в субботу?", "tj": "Раҳмат! Шумо рӯзи шанбе чӣ кор мекунед?"},
                    {"speaker": "Wang Yixue", "zh": "我在家里做饭、看电视，和孩子们、小狗玩。", "pinyin": "Wǒ zài jiālǐ zuò fàn, kàn diànshì, hé háizimen, xiǎogǒu wán.", "en": "I will cook, watch TV, and play with my children and my little dog at home.", "uz": "Uyda ovqat pishiraman, televizor ko‘raman, bolalarim va kichik itim bilan o‘ynayman.", "ru": "Дома я буду готовить, смотреть телевизор и играть с детьми и маленькой собакой.", "tj": "Дар хона хӯрок мепазам, телевизор тамошо мекунам ва бо фарзандонам ва сагчаам бозӣ мекунам."},
                    {"speaker": "Yang Tongle", "zh": "我也有一只小狗。", "pinyin": "Wǒ yě yǒu yì zhī xiǎogǒu.", "en": "I also have a little dog.", "uz": "Menda ham bitta kichik it bor.", "ru": "У меня тоже есть маленькая собака.", "tj": "Ман ҳам як сагча дорам."},
                ],
            },
        ],
        ensure_ascii=False,
    ),
    "grammar_json": json.dumps(
        [
            {
                "no": 1,
                "title_zh": "存现句（1）",
                "title_uz": "Mavjudlik gapi (1)",
                "title_ru": "Экзистенциальное предложение (1)",
                "title_tj": "Ҷумлаи мавҷудият (1)",
                "rule_zh": "表示某处存在某人或某物的一种句子，一般以“有”或“是”为标记；有否定时，宾语前不能带数量词。",
                "rule_en": "Existential sentences indicate the existence of someone or something in a specific place or location, generally marked by 有 or 是. When negating a 有-sentence, no numeral-measure word phrase is used before the object.",
                "rule_uz": "Mavjudlik gapi biror joyda kimdir yoki nimadir borligini bildiradi va odatda “有” yoki “是” bilan tuziladi. “有” inkor qilinganda obyekt oldida son+o‘lchov birikmasi kelmaydi.",
                "rule_ru": "Экзистенциальное предложение показывает наличие кого-либо или чего-либо в определённом месте и обычно строится с “有” или “是”. При отрицании с “有” перед объектом не ставится числительно-счётная группа.",
                "rule_tj": "Ҷумлаи мавҷудият будани шахс ё чизро дар ҷойи муайян нишон медиҳад ва одатан бо “有” ё “是” сохта мешавад. Ҳангоми инкори “有” пеш аз объект таркиби рақам+воҳиди ҳисоб намеояд.",
                "examples": [
                    {"zh": "学校前边有一家电影院。", "pinyin": "Xuéxiào qiánbian yǒu yì jiā diànyǐngyuàn.", "uz": "Maktab oldida bitta kinoteatr bor.", "ru": "Перед школой есть кинотеатр.", "tj": "Пеши мактаб як кинотеатр ҳаст."},
                    {"zh": "电影院前边是一家超市。", "pinyin": "Diànyǐngyuàn qiánbian shì yì jiā chāoshì.", "uz": "Kinoteatr oldida supermarket bor.", "ru": "Перед кинотеатром находится супермаркет.", "tj": "Пеши кинотеатр як супермаркет аст."},
                    {"zh": "桌子上没有小猫。", "pinyin": "Zhuōzi shàng méiyǒu xiǎomāo.", "uz": "Stol ustida mushuk yo‘q.", "ru": "На столе нет котёнка.", "tj": "Рӯйи миз гурба нест."},
                ],
            },
            {
                "no": 2,
                "title_zh": "时间词语和处所词语同时作状语的顺序",
                "title_uz": "Vaqt va joy ifodalari birga hol bo‘lgandagi tartib",
                "title_ru": "Порядок выражений времени и места при совместной роли обстоятельства",
                "title_tj": "Тартиби ифодаҳои вақт ва ҷой ҳангоми ҳамзамон ҳол будан",
                "rule_zh": "时间词语和处所词语同时作状语时，时间词语要在处所词语前面。",
                "rule_en": "When time and location expressions function as adverbials simultaneously, the time expression should precede the location expression.",
                "rule_uz": "Vaqt va joy birikmalari bir vaqtda hol bo‘lsa, vaqt ifodasi joy ifodasidan oldin keladi.",
                "rule_ru": "Когда время и место одновременно выступают обстоятельствами, выражение времени ставится перед выражением места.",
                "rule_tj": "Вақте вақт ва ҷой ҳамзамон вазифаи ҳолро доранд, ифодаи вақт пеш аз ифодаи ҷой меояд.",
                "examples": [
                    {"zh": "我们七点在电影院外边见。", "pinyin": "Wǒmen qī diǎn zài diànyǐngyuàn wàibian jiàn.", "uz": "Biz soat 7 da kinoteatr tashqarisida uchrashamiz.", "ru": "Мы встретимся в 7 часов у кинотеатра.", "tj": "Мо соати 7 беруни кинотеатр вомехӯрем."},
                    {"zh": "你明天下午在家里做什么？", "pinyin": "Nǐ míngtiān xiàwǔ zài jiālǐ zuò shénme?", "uz": "Sen ertaga tushdan keyin uyda nima qilasan?", "ru": "Что ты будешь делать дома завтра днём?", "tj": "Фардо баъди нисфирӯзӣ дар хона чӣ кор мекунӣ?"},
                    {"zh": "陈天中明天中午在学校吃午饭。", "pinyin": "Chén Tiānzhōng míngtiān zhōngwǔ zài xuéxiào chī wǔfàn.", "uz": "Chen Tianzhong ertaga tushda maktabda tushlik qiladi.", "ru": "Чэнь Тяньчжун завтра в полдень пообедает в школе.", "tj": "Чэн Тянҷун фардо нисфирӯзӣ дар мактаб хӯрок мехӯрад."},
                ],
            },
            {
                "no": 3,
                "title_zh": "表示序数的“第”",
                "title_uz": "Tartib sonini bildiruvchi “第”",
                "title_ru": "“第” для порядковых числительных",
                "title_tj": "“第” барои шумораҳои тартибӣ",
                "rule_zh": "“第”位于基数词的数词前面，表示序数。基本结构：（1）第+数词；（2）第+数词+量词+（名词）。",
                "rule_en": "“第” precedes cardinal numbers to indicate ordinal numbers. Basic structures: 第 + numeral; 第 + numeral + measure word + (noun).",
                "rule_uz": "“第” sanoq soni oldidan kelib tartib sonini hosil qiladi: 第+son; yoki 第+son+o‘lchov so‘zi+(ot).",
                "rule_ru": "“第” ставится перед количественным числительным и образует порядковое: 第+число; либо 第+число+счётное слово+(существительное).",
                "rule_tj": "“第” пеш аз шумораи миқдорӣ омада, шумораи тартибиро месозад: 第+рақам; ё 第+рақам+воҳиди ҳисоб+(исм).",
                "examples": [
                    {"zh": "第一、第二、第三", "pinyin": "dì yī, dì èr, dì sān", "uz": "birinchi, ikkinchi, uchinchi", "ru": "первый, второй, третий", "tj": "якум, дуюм, сеюм"},
                    {"zh": "第一个、第二个、第一本", "pinyin": "dì yí ge, dì èr ge, dì yì běn", "uz": "birinchi dona, ikkinchi dona, birinchi kitob", "ru": "первый, второй, первая книга", "tj": "якум, дуюм, китоби якум"},
                    {"zh": "第一个学生、第一本书", "pinyin": "dì yí ge xuésheng, dì yì běn shū", "uz": "birinchi talaba; birinchi kitob", "ru": "первый студент; первая книга", "tj": "донишҷӯи якум; китоби якум"},
                ],
            },
        ],
        ensure_ascii=False,
    ),
}
