from __future__ import annotations

import json

SOURCE = {
    "book": "新HSK教程1",
    "pdf_path": "HSK 3.0 PDF/新HSK教程1.pdf",
    "pdf_pages": [59, 60, 61, 62, 63, 64, 65, 66, 67],
    "printed_pages": [45, 46, 47, 48, 49, 50, 51, 52, 53],
    "rights_note": "Dialogue reuse permitted by project owner.",
    "extraction_status": "verified_from_rendered_pages",
}

LESSON = {
    "level": "nhsk1",
    "lesson_order": 7,
    "lesson_code": "NHSK1-L07",
    "title": "我晚上六点半下班",
    "title_pinyin": "Wǒ wǎnshang liù diǎn bàn xiàbān",
    "goal": json.dumps(
        {
            "uz": "Voqealar vaqtini tushunish va aytish; “吧” bilan taklif, maslahat, buyruq yoki iltimosni ifodalash; “呢” bilan tasdiqlanayotgan faktni bildirish; vaqt so‘zlari va ravishlarning gapdagi o‘rnini to‘g‘ri qo‘llash.",
            "ru": "Понимать и называть время событий; использовать “吧” для предложения, совета, побуждения или просьбы; использовать “呢” для подтверждаемого факта; правильно располагать наречия и выражения времени.",
            "tj": "Вақти рӯйдодҳоро фаҳмидан ва гуфтан; бо “吧” пешниҳод, маслиҳат, амр ё хоҳишро ифода кардан; бо “呢” воқеияти тасдиқшавандаро нишон додан; ҷойи дурусти зарфҳо ва ифодаҳои вақтро истифода бурдан.",
        },
        ensure_ascii=False,
    ),
    "intro_text": json.dumps(
        {
            "uz": "Dars soat, uchrashuv va ish vaqti haqidagi uchta dialog orqali vaqt ifodasi, “吧”, “呢” va vaqt/ravishlarning gapdagi o‘rnini o‘rgatadi.",
            "ru": "Урок через три диалога о времени, встречах и рабочем графике вводит выражение времени, “吧”, “呢” и порядок наречий/временных выражений.",
            "tj": "Дарс тавассути се гуфтугӯ дар бораи вақт, вохӯрӣ ва вақти кор ифодаи вақт, “吧”, “呢” ва ҷойи зарфҳо/ифодаҳои вақтро меомӯзонад.",
        },
        ensure_ascii=False,
    ),
    "vocabulary_json": json.dumps(
        [
            {"no": 1, "zh": "现在", "pinyin": "xiànzài", "pos": "n.", "uz": "hozir", "ru": "сейчас", "tj": "ҳозир"},
            {"no": 2, "zh": "点", "pinyin": "diǎn", "pos": "m.", "uz": "soat (vaqt birligi)", "ru": "час (при указании времени)", "tj": "соат (ҳангоми гуфтани вақт)"},
            {"no": 3, "zh": "早上", "pinyin": "zǎoshang", "pos": "n.", "uz": "erta tong", "ru": "раннее утро", "tj": "субҳи барвақт"},
            {"no": 4, "zh": "上午", "pinyin": "shàngwǔ", "pos": "n.", "uz": "ertalab; tushgacha", "ru": "утро; до полудня", "tj": "субҳ; то нисфирӯзӣ"},
            {"no": 5, "zh": "分", "pinyin": "fēn", "pos": "m.", "uz": "daqiqa", "ru": "минута", "tj": "дақиқа"},
            {"no": 6, "zh": "课", "pinyin": "kè", "pos": "n.", "uz": "dars", "ru": "урок; занятие", "tj": "дарс"},
            {"no": 7, "zh": "下午", "pinyin": "xiàwǔ", "pos": "n.", "uz": "tushdan keyin", "ru": "вторая половина дня", "tj": "баъди нисфирӯзӣ"},
            {"no": 8, "zh": "见", "pinyin": "jiàn", "pos": "v.", "uz": "uchrashmoq; ko‘rishmoq", "ru": "встречать; встречаться", "tj": "вохӯрдан; дидан"},
            {"no": 9, "zh": "吧", "pinyin": "ba", "pos": "part.", "uz": "taklif/maslahat/iltimos yuklamasi", "ru": "частица предложения/совета/просьбы", "tj": "ҳиссачаи пешниҳод/маслиҳат/хоҳиш"},
            {"no": 10, "zh": "电影院", "pinyin": "diànyǐngyuàn", "pos": "n.", "uz": "kinoteatr", "ru": "кинотеатр", "tj": "кинотеатр"},
            {"no": 11, "zh": "看", "pinyin": "kàn", "pos": "v.", "uz": "ko‘rmoq; tomosha qilmoq; o‘qimoq", "ru": "смотреть; видеть; читать", "tj": "дидан; тамошо кардан; хондан"},
            {"no": 12, "zh": "电影", "pinyin": "diànyǐng", "pos": "n.", "uz": "film; kino", "ru": "фильм; кино", "tj": "филм; кино"},
            {"no": 13, "zh": "事", "pinyin": "shì", "pos": "n.", "uz": "ish; masala", "ru": "дело; событие", "tj": "кор; масъала"},
            {"no": 14, "zh": "上课", "pinyin": "shàngkè", "pos": "v.", "uz": "darsga qatnashmoq; dars boshlamoq", "ru": "быть на занятии; проводить занятие", "tj": "ба дарс рафтан; дарс гузарондан"},
            {"no": 15, "zh": "呢", "pinyin": "ne", "pos": "part.", "uz": "modal yuklama", "ru": "модальная частица", "tj": "ҳиссачаи модалӣ"},
            {"no": 16, "zh": "半", "pinyin": "bàn", "pos": "num.", "uz": "yarim", "ru": "половина", "tj": "ним"},
            {"no": 17, "zh": "下课", "pinyin": "xiàkè", "pos": "v.", "uz": "dars tugamoq", "ru": "заканчивать занятие", "tj": "дарс тамом шудан"},
            {"no": 18, "zh": "在", "pinyin": "zài", "pos": "v.", "uz": "bo‘lmoq; joylashmoq", "ru": "находиться; быть", "tj": "будан; ҷойгир будан"},
            {"no": 19, "zh": "家", "pinyin": "jiā", "pos": "n.", "uz": "uy", "ru": "дом", "tj": "хона"},
            {"no": 20, "zh": "里", "pinyin": "lǐ", "pos": "n.", "uz": "ichida", "ru": "внутри", "tj": "дарун; дохил"},
            {"no": 21, "zh": "晚上", "pinyin": "wǎnshang", "pos": "n.", "uz": "kechqurun", "ru": "вечер", "tj": "шом"},
            {"no": 22, "zh": "医院", "pinyin": "yīyuàn", "pos": "n.", "uz": "kasalxona", "ru": "больница", "tj": "беморхона"},
            {"no": 23, "zh": "上班", "pinyin": "shàngbān", "pos": "v.", "uz": "ishga bormoq; ishlamoq", "ru": "идти на работу; работать", "tj": "ба кор рафтан; кор кардан"},
            {"no": 24, "zh": "店", "pinyin": "diàn", "pos": "n.", "uz": "do‘kon", "ru": "магазин", "tj": "мағоза"},
            {"no": 25, "zh": "菜", "pinyin": "cài", "pos": "n.", "uz": "sabzavot; taom", "ru": "овощи; блюдо", "tj": "сабзавот; таом"},
            {"no": 26, "zh": "分钟", "pinyin": "fēnzhōng", "pos": "m.", "uz": "daqiqa", "ru": "минута", "tj": "дақиқа"},
            {"no": 27, "zh": "后", "pinyin": "hòu", "pos": "n.", "uz": "keyin", "ru": "после; спустя", "tj": "баъд; пас"},
        ],
        ensure_ascii=False,
    ),
    "dialogue_json": json.dumps(
        [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_zh": "白家月和安妮在打电话。",
                "scene_en": "Bai Jiayue and Annie were talking on the phone.",
                "scene_uz": "Bai Jiayue va Annie telefonda gaplashmoqda.",
                "scene_ru": "Бай Цзяюэ и Энни разговаривают по телефону.",
                "scene_tj": "Бай Ҷяюэ ва Энни бо телефон суҳбат мекунанд.",
                "dialogue": [
                    {"speaker": "Bai Jiayue", "zh": "现在几点？", "pinyin": "Xiànzài jǐ diǎn?", "en": "What time is it now?", "uz": "Hozir soat necha?", "ru": "Который сейчас час?", "tj": "Ҳозир соат чанд?"},
                    {"speaker": "Annie", "zh": "早上八点四十分。", "pinyin": "Zǎoshang bā diǎn sìshí fēn.", "en": "It is 8:40 in the morning.", "uz": "Ertalab soat 8:40.", "ru": "Сейчас 8:40 утра.", "tj": "Субҳ соати 8:40."},
                    {"speaker": "Bai Jiayue", "zh": "我上午十点十分有课。", "pinyin": "Wǒ shàngwǔ shí diǎn shí fēn yǒu kè.", "en": "I have a class at 10:10 in the morning.", "uz": "Ertalab soat 10:10 da darsim bor.", "ru": "У меня занятие в 10:10 утра.", "tj": "Субҳ соати 10:10 дарс дорам."},
                    {"speaker": "Annie", "zh": "好的，我们下午两点见吧。", "pinyin": "Hǎo de, wǒmen xiàwǔ liǎng diǎn jiàn ba.", "en": "Alright, let's meet at 2:00 in the afternoon.", "uz": "Xo‘p, tushdan keyin soat 2 da uchrashamiz.", "ru": "Хорошо, давай встретимся в 2 часа дня.", "tj": "Хуб, баъди нисфирӯзӣ соати 2 вомехӯрем."},
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_zh": "在校园里，李文遇到白家月。",
                "scene_en": "On campus, Li Wen came across Bai Jiayue.",
                "scene_uz": "Kampusda Li Wen Bai Jiayuega duch keladi.",
                "scene_ru": "В кампусе Ли Вэнь встречает Бай Цзяюэ.",
                "scene_tj": "Дар кампус Ли Вэн бо Бай Ҷяюэ вомехӯрад.",
                "dialogue": [
                    {"speaker": "Li Wen", "zh": "下午我想去电影院看电影，你去吗？", "pinyin": "Xiàwǔ wǒ xiǎng qù diànyǐngyuàn kàn diànyǐng, nǐ qù ma?", "en": "I want to go to the cinema to watch a movie this afternoon. Are you going?", "uz": "Bugun tushdan keyin kinoteatrga film ko‘rgani bormoqchiman. Sen ham borasanmi?", "ru": "Сегодня днём я хочу пойти в кино. Ты пойдёшь?", "tj": "Имрӯз баъди нисфирӯзӣ мехоҳам ба кино равам. Ту ҳам меравӣ?"},
                    {"speaker": "Bai Jiayue", "zh": "我不想去，下午还有事。", "pinyin": "Wǒ bù xiǎng qù, xiàwǔ hái yǒu shì.", "en": "I don't want to go. I still have something to do this afternoon.", "uz": "Borgim kelmaydi, tushdan keyin yana ishim bor.", "ru": "Я не хочу идти, днём у меня ещё есть дела.", "tj": "Рафтан намехоҳам, баъди нисфирӯзӣ боз кор дорам."},
                    {"speaker": "Li Wen", "zh": "好的。明天呢？", "pinyin": "Hǎo de. Míngtiān ne?", "en": "Okay. How about tomorrow?", "uz": "Xo‘p. Ertaga-chi?", "ru": "Хорошо. А завтра?", "tj": "Хуб. Фардо чӣ?"},
                    {"speaker": "Bai Jiayue", "zh": "我明天下午两点还上课呢，两点半下课。", "pinyin": "Wǒ míngtiān xiàwǔ liǎng diǎn hái shàngkè ne, liǎng diǎn bàn xiàkè.", "en": "I have a class tomorrow afternoon at 2:00, and it finishes at 2:30.", "uz": "Ertaga tushdan keyin soat 2 da hali darsda bo‘laman, 2:30 da dars tugaydi.", "ru": "Завтра в 2 часа дня у меня ещё занятие, оно заканчивается в 2:30.", "tj": "Фардо баъди нисфирӯзӣ соати 2 ҳоло дарс дорам, соати 2:30 дарс тамом мешавад."},
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_zh": "王一雪在办公室给刘明打电话。",
                "scene_en": "Wang Yixue was calling Liu Ming at the office.",
                "scene_uz": "Wang Yixue ofisdan Liu Mingga telefon qilmoqda.",
                "scene_ru": "Ван Исюэ звонит Лю Мину из офиса.",
                "scene_tj": "Ван Исюэ аз идора ба Лю Мин занг мезанад.",
                "dialogue": [
                    {"speaker": "Wang Yixue", "zh": "喂，你在哪儿呢？", "pinyin": "Wèi, nǐ zài nǎr ne?", "en": "Hey, where are you?", "uz": "Allo, qayerdasan?", "ru": "Алло, ты где?", "tj": "Алло, ту куҷоӣ?"},
                    {"speaker": "Liu Ming", "zh": "我在家里呢。", "pinyin": "Wǒ zài jiālǐ ne.", "en": "I'm at home.", "uz": "Men uydaman.", "ru": "Я дома.", "tj": "Ман дар хонаам."},
                    {"speaker": "Wang Yixue", "zh": "我晚上六点半下班。", "pinyin": "Wǒ wǎnshang liù diǎn bàn xiàbān.", "en": "I'll finish work at 6:30 in the evening.", "uz": "Men kechqurun soat 6:30 da ishdan chiqaman.", "ru": "Я заканчиваю работу в 6:30 вечера.", "tj": "Ман шом соати 6:30 аз кор мебароям."},
                    {"speaker": "Liu Ming", "zh": "我八点去医院上班。", "pinyin": "Wǒ bā diǎn qù yīyuàn shàngbān.", "en": "I'll go to work at the hospital at 8:00.", "uz": "Men soat 8 da kasalxonaga ishga boraman.", "ru": "В 8 часов я пойду работать в больницу.", "tj": "Ман соати 8 ба беморхона ба кор меравам."},
                    {"speaker": "Wang Yixue", "zh": "好的，你去店里买些菜吧。", "pinyin": "Hǎo de, nǐ qù diàn lǐ mǎi xiē cài ba.", "en": "Alright, could you go to the store to buy some vegetables?", "uz": "Xo‘p, do‘konga borib biroz sabzavot ol.", "ru": "Хорошо, зайди в магазин и купи овощей.", "tj": "Хуб, ба мағоза рафта каме сабзавот бихар."},
                    {"speaker": "Liu Ming", "zh": "好，我十分钟后去。", "pinyin": "Hǎo, wǒ shí fēnzhōng hòu qù.", "en": "Okay, I'll go in ten minutes.", "uz": "Xo‘p, o‘n daqiqadan keyin boraman.", "ru": "Хорошо, пойду через десять минут.", "tj": "Хуб, пас аз даҳ дақиқа меравам."},
                ],
            },
        ],
        ensure_ascii=False,
    ),
    "grammar_json": json.dumps(
        [
            {
                "no": 1,
                "title_zh": "时间的表达（2）",
                "title_uz": "Vaqtni ifodalash (2)",
                "title_ru": "Выражение времени (2)",
                "title_tj": "Ифодаи вақт (2)",
                "rule_zh": "用“点、分”等表达具体钟点；“早上、上午、下午、晚上”等时间名词可表示时间段，并可直接放在时间点前。",
                "rule_en": "Use 点 and 分 to express specific clock times. Time nouns such as 早上, 上午, 下午 and 晚上 indicate periods of the day and can appear before a specific time.",
                "rule_uz": "Aniq soatni 点 va 分 bilan aytiladi. 早上、上午、下午、晚上 kabi vaqt otlari kunning vaqt oralig‘ini bildiradi va aniq soat oldidan kelishi mumkin.",
                "rule_ru": "Точное время выражается с 点 и 分. Слова 早上、上午、下午、晚上 обозначают части дня и могут стоять перед конкретным временем.",
                "rule_tj": "Вақти дақиқ бо 点 ва 分 ифода мешавад. 早上、上午、下午、晚上 қисми рӯзро нишон медиҳанд ва пеш аз вақти дақиқ омада метавонанд.",
                "examples": [
                    {"zh": "上午九点半", "pinyin": "shàngwǔ jiǔ diǎn bàn", "uz": "ertalab 9:30", "ru": "9:30 утра", "tj": "субҳ 9:30"},
                    {"zh": "下午两点半", "pinyin": "xiàwǔ liǎng diǎn bàn", "uz": "tushdan keyin 2:30", "ru": "2:30 дня", "tj": "баъди нисфирӯзӣ 2:30"},
                    {"zh": "晚上九点十分", "pinyin": "wǎnshang jiǔ diǎn shí fēn", "uz": "kechqurun 9:10", "ru": "9:10 вечера", "tj": "шом 9:10"},
                ],
            },
            {
                "no": 2,
                "title_zh": "语气助词“吧”（1）",
                "title_uz": "Modal yuklama “吧” (1)",
                "title_ru": "Модальная частица “吧” (1)",
                "title_tj": "Ҳиссачаи модалии “吧” (1)",
                "rule_zh": "“吧”读轻声，位于句子末尾，表示建议、商量、劝告、请求。",
                "rule_en": "The modal particle “吧” is pronounced with a neutral tone at the end of a sentence and is used to express suggestions, consultations, advice, or requests.",
                "rule_uz": "“吧” yengil ohangda gap oxirida kelib taklif, maslahatlashish, maslahat yoki iltimosni bildiradi.",
                "rule_ru": "“吧” произносится нейтральным тоном и ставится в конце предложения для предложения, обсуждения, совета или просьбы.",
                "rule_tj": "“吧” бо оҳанги сабук дар охири ҷумла омада, пешниҳод, маслиҳат, машварат ё хоҳишро ифода мекунад.",
                "examples": [
                    {"zh": "我们下午两点见吧。", "pinyin": "Wǒmen xiàwǔ liǎng diǎn jiàn ba.", "uz": "Tushdan keyin soat 2 da uchrashaylik.", "ru": "Давай встретимся в 2 часа дня.", "tj": "Биёед баъди нисфирӯзӣ соати 2 вохӯрем."},
                    {"zh": "你去超市买吧。", "pinyin": "Nǐ qù chāoshì mǎi ba.", "uz": "Supermarketga borib ol.", "ru": "Сходи купи в супермаркете.", "tj": "Ба супермаркет рафта бихар."},
                ],
            },
            {
                "no": 3,
                "title_zh": "副词、时间词语作状语的位置",
                "title_uz": "Ravish va vaqt so‘zlarining hol sifatidagi o‘rni",
                "title_ru": "Позиция наречий и выражений времени в роли обстоятельства",
                "title_tj": "Ҷойи зарфҳо ва ифодаҳои вақт ҳамчун ҳол",
                "rule_zh": "副词、时间词语作状语时，一般都要在动词或者形容词前。",
                "rule_en": "In Chinese, when adverbs and time expressions function as adverbials, they are generally placed before verbs or adjectives.",
                "rule_uz": "Ravish va vaqt so‘zlari hol vazifasida kelganda odatda fe’l yoki sifatdan oldin turadi.",
                "rule_ru": "Когда наречия и выражения времени выступают обстоятельствами, они обычно стоят перед глаголом или прилагательным.",
                "rule_tj": "Вақте зарфҳо ва ифодаҳои вақт вазифаи ҳолро иҷро мекунанд, одатан пеш аз феъл ё сифат меоянд.",
                "examples": [
                    {"zh": "我下午有课。", "pinyin": "Wǒ xiàwǔ yǒu kè.", "uz": "Tushdan keyin darsim bor.", "ru": "Днём у меня занятие.", "tj": "Баъди нисфирӯзӣ дарс дорам."},
                    {"zh": "妹妹很高兴。", "pinyin": "Mèimei hěn gāoxìng.", "uz": "Singlim juda xursand.", "ru": "Младшая сестра очень рада.", "tj": "Хоҳари хурдӣ хеле хурсанд аст."},
                    {"zh": "她上午八点半上课。", "pinyin": "Tā shàngwǔ bā diǎn bàn shàngkè.", "uz": "U ertalab 8:30 da darsga kiradi.", "ru": "У неё занятие в 8:30 утра.", "tj": "Ӯ субҳ соати 8:30 ба дарс медарояд."},
                ],
            },
            {
                "no": 4,
                "title_zh": "语气助词“呢”（2）",
                "title_uz": "Modal yuklama “呢” (2)",
                "title_ru": "Модальная частица “呢” (2)",
                "title_tj": "Ҳиссачаи модалии “呢” (2)",
                "rule_zh": "“呢”位于句子末尾，表示确认的事实。基本结构：……呢。",
                "rule_en": "The modal particle “呢” is placed at the end of a sentence to indicate confirmed facts.",
                "rule_uz": "“呢” gap oxirida kelib tasdiqlanayotgan faktni bildiradi.",
                "rule_ru": "“呢” ставится в конце предложения и подчёркивает подтверждаемый факт.",
                "rule_tj": "“呢” дар охири ҷумла омада, воқеияти тасдиқшавандаро таъкид мекунад.",
                "examples": [
                    {"zh": "下午两点我还上课呢。", "pinyin": "Xiàwǔ liǎng diǎn wǒ hái shàngkè ne.", "uz": "Tushdan keyin soat 2 da men hali darsda bo‘laman.", "ru": "В 2 часа дня у меня ещё занятие.", "tj": "Баъди нисфирӯзӣ соати 2 ман ҳоло ҳам дарс дорам."},
                    {"zh": "妹妹会做两个菜呢。", "pinyin": "Mèimei huì zuò liǎng ge cài ne.", "uz": "Singlim hatto ikkita taom pishira oladi.", "ru": "Младшая сестра умеет готовить два блюда.", "tj": "Хоҳари хурдӣ ду таом пухта метавонад."},
                    {"zh": "李文晚上还有事呢。", "pinyin": "Lǐ Wén wǎnshang hái yǒu shì ne.", "uz": "Li Wenning kechqurun yana ishi bor.", "ru": "У Ли Вэня вечером ещё есть дела.", "tj": "Ли Вэн шом боз кор дорад."},
                ],
            },
        ],
        ensure_ascii=False,
    ),
}
