import SwiftUI
struct VoiceScreen:View {
 @ObservedObject var model:VoiceViewModel; let account:LinkedAccount; let onClose:()->Void
 @State private var text=""; private let roles=[("lily","person.crop.circle.fill"),("chen","figure.walk"),("xiao_mei","graduationcap.fill"),("teacher_li","books.vertical.fill"),("manager_wang","briefcase.fill")]
 var body:some View{NavigationStack{ZStack{HSKGlassBackdrop();content}.navigationTitle("voice_title").toolbar{ToolbarItem(placement:.topBarLeading){Button("action_close",action:onClose)}}}.task{if model.status==nil{await model.loadStatus()}}}
 @ViewBuilder private var content:some View{
  switch model.phase{
  case .idle: ScrollView{VStack(spacing:14){if let s=model.status{HSKGlassCard(cornerRadius:26,padding:18,tint:HSKColors.auroraMint){VStack(spacing:6){Text("voice_remaining").font(.caption);Text(s.isPaid ? "∞":"\(s.remainingVoiceLimit)").font(.title.bold())}}};ForEach(roles,id:\.0){role in Button{Task{await model.start(role:role.0,account:account)}}label:{HSKGlassCard(cornerRadius:22,padding:16){HStack{Image(systemName:role.1).foregroundStyle(HSKColors.cinnabar);Text(LocalizedStringKey("voice_role_\(role.0)")).font(.headline).foregroundStyle(HSKColors.ink);Spacer();Image(systemName:"chevron.right")}}}.buttonStyle(.plain)};if let e=model.errorKey{Text(LocalizedStringKey(e)).foregroundStyle(HSKColors.flame)}}.padding(16)}
  case .loading,.ending: ProgressView().tint(HSKColors.cinnabar)
  case .active: VStack(spacing:10){ScrollView{LazyVStack(spacing:12){ForEach(model.turns){t in HSKGlassCard(cornerRadius:20,padding:14,tint:HSKColors.auroraBlue){VStack(alignment:.leading,spacing:5){if !t.user.isEmpty{Text(t.user).font(.caption).foregroundStyle(HSKColors.inkSecondary)};Text(t.chinese).font(.title3.bold()).foregroundStyle(HSKColors.ink);Text(t.pinyin).font(.caption).foregroundStyle(HSKColors.cinnabarDark);Text(t.translation).font(.subheadline).foregroundStyle(HSKColors.inkSecondary);if let c=t.correction,!c.isEmpty{Text(c).font(.caption).foregroundStyle(HSKColors.flame)}}}}}.padding(16)};ScrollView(.horizontal,showsIndicators:false){HStack{ForEach(model.suggestions){s in Button(s.hanzi){Task{await model.send(text:s.hanzi)}}.buttonStyle(HSKGlassSecondaryButtonStyle())}}.padding(.horizontal,16)};HStack{TextField("voice_type_placeholder",text:$text).textFieldStyle(.roundedBorder);Button{let v=text;text="";Task{await model.send(text:v)}}label:{Image(systemName:"paperplane.fill")}.buttonStyle(HSKGlassIconButtonStyle());Button{Task{await model.speak()}}label:{Image(systemName:model.isRecording ? "waveform":"mic.fill")}.buttonStyle(HSKGlassIconButtonStyle())}.padding(.horizontal,16);Button("voice_end"){Task{await model.end()}}.buttonStyle(HSKGlassSecondaryButtonStyle()).padding(.bottom,12)}
  case .finished: VStack{Spacer();HSKGlassCard(cornerRadius:28,padding:24,tint:HSKColors.jade){VStack(spacing:10){Text("voice_complete").font(.title2.bold());if let s=model.summary{Text("\(s.goodCount) ✓  ·  \(s.mistakeCount) △").font(.title3.monospacedDigit())};Button("action_done",action:onClose).buttonStyle(HSKPrimaryButtonStyle())}}.padding(24);Spacer()}
  }
 }
}
