/* Builds app/static/course_v3_data/memo_lv.js: hanzi char -> min HSK level (1-4),
   derived from hsk-data.js WORDS ("lv" field). The memorize Mini App uses it to
   pick mnemonic cards matching the user's own HSK level.
   Run after hsk-data.js changes:  node scripts/gen_memo_lv.js  */
const fs = require("fs");
const path = require("path");

const staticDir = path.join(__dirname, "..", "app", "static");
eval(
  fs
    .readFileSync(path.join(staticDir, "hsk-data.js"), "utf8")
    .replace("const WORDS=", "globalThis.WORDS=")
);

const lvNum = (s) => parseInt(String(s || "").replace(/[^0-9]/g, "").slice(0, 1)) || 0;
const map = {};
for (const w of WORDS) {
  const n = lvNum(w.lv);
  if (!n) continue;
  for (const ch of String(w.h)) {
    if (/[一-鿿]/.test(ch) && (!map[ch] || n < map[ch])) map[ch] = n;
  }
}

const out =
  "/* GENERATED by scripts/gen_memo_lv.js — hanzi -> min HSK level (from hsk-data.js). Do not hand-edit. */\n" +
  "window.MEMO_LV=" + JSON.stringify(map) + ";\n";
fs.writeFileSync(path.join(staticDir, "course_v3_data", "memo_lv.js"), out);
console.log("wrote memo_lv.js:", Object.keys(map).length, "chars");
