def _word(no, zh, pinyin, pos, uz, ru, tj):
    return {"no": no, "zh": zh, "pinyin": pinyin, "pos": pos, "uz": uz, "ru": ru, "tj": tj}


def _line(speaker, zh, pinyin, uz, ru, tj):
    return {"speaker": speaker, "zh": zh, "pinyin": pinyin, "uz": uz, "ru": ru, "tj": tj}


def _grammar(no, title_zh, title_uz, title_ru, title_tj, rule_uz, rule_ru, rule_tj, example_zh, example_pinyin, example_uz, example_ru, example_tj):
    return {
        "no": no,
        "title_zh": title_zh,
        "title_uz": title_uz,
        "title_ru": title_ru,
        "title_tj": title_tj,
        "rule_uz": rule_uz,
        "rule_ru": rule_ru,
        "rule_tj": rule_tj,
        "formula": title_zh,
        "examples": [
            {
                "zh": example_zh,
                "pinyin": example_pinyin,
                "uz": example_uz,
                "ru": example_ru,
                "tj": example_tj,
            }
        ],
    }


HSK4_UPPER_PDF_MATERIALS_7_10 = {
    7: {
        "title": "最好的医生是自己",
        "goal": {
            "uz": "sog'liq, odatlar va sport haqida gapirish; 估计, 来不及, 离合词重叠, 要是 va 既...又 grammatikalarini ishlatish",
            "ru": "говорить о здоровье, привычках и спорте; использовать 估计, 来不及, удвоение разделяемых слов, 要是 и 既...又",
            "tj": "дар бораи саломатӣ, одатҳо ва варзиш гуфтугӯ кардан; истифодаи 估计, 来不及, такрори калимаҳои ҷудошаванда, 要是 ва 既...又",
        },
        "intro_text": {
            "uz": "Bu darsda shamollash, chekish, kompyuter oldida uzoq o'tirish va sog'lom hayot haqida gapirishni o'rganasiz. Har qismda o'sha matndagi yangi so'zlar, pinyin, tarjima va kerakli grammatika beriladi.",
            "ru": "В этом уроке вы научитесь говорить о простуде, курении, долгой работе за компьютером и здоровом образе жизни. В каждой части есть слова, pinyin, перевод и нужная грамматика именно к своему тексту.",
            "tj": "Дар ин дарс дар бораи шамолхӯрӣ, тамокукашӣ, дароз нишастан назди компютер ва зиндагии солим гуфтугӯ карданро меомӯзед. Дар ҳар қисм калимаҳо, pinyin, тарҷума ва грамматикаи лозими ҳамон матн дода мешавад.",
        },
        "vocabulary": [
            _word(1, "流血", "liú xiě", "v.", "qon ketmoq", "кровоточить", "хун рафтан"),
            _word(2, "擦", "cā", "v.", "artmoq", "вытирать", "пок кардан, молидан"),
            _word(3, "气候", "qìhòu", "n.", "iqlim", "климат", "иқлим"),
            _word(4, "估计", "gūjì", "v.", "taxmin qilmoq", "предполагать, оценивать", "тахмин кардан"),
            _word(5, "咳嗽", "késou", "v.", "yo'talmoq", "кашлять", "сулфа кардан"),
            _word(6, "严重", "yánzhòng", "adj.", "jiddiy, og'ir", "серьёзный", "ҷиддӣ, вазнин"),
            _word(7, "窗户", "chuānghu", "n.", "deraza", "окно", "тиреза"),
            _word(8, "空气", "kōngqì", "n.", "havo", "воздух", "ҳаво"),
            _word(9, "抽烟", "chōu yān", "v.", "chekmoq", "курить", "тамоку кашидан"),
            _word(10, "动作", "dòngzuò", "n.", "harakat", "движение, действие", "ҳаракат"),
            _word(11, "帅", "shuài", "adj.", "kelishgan", "красивый, стильный", "зебо, хушсурат"),
            _word(12, "出现", "chūxiàn", "v.", "paydo bo'lmoq", "появляться", "пайдо шудан"),
            _word(13, "后悔", "hòuhuǐ", "v.", "pushaymon bo'lmoq", "сожалеть", "пушаймон шудан"),
            _word(14, "来不及", "láibují", "v.", "ulgurmaslik, kech bo'lmoq", "не успеть, быть поздно", "вақт нарасидан, дер шудан"),
            _word(15, "反对", "fǎnduì", "v.", "qarshi bo'lmoq", "быть против", "муқобил будан"),
            _word(16, "大夫", "dàifu", "n.", "shifokor", "врач", "духтур"),
            _word(17, "植物", "zhíwù", "n.", "o'simlik", "растение", "растанӣ"),
            _word(18, "研究", "yánjiū", "v.", "tadqiq qilmoq", "исследовать", "таҳқиқ кардан"),
            _word(19, "超过", "chāoguò", "v.", "oshib ketmoq", "превышать", "зиёд шудан"),
            _word(20, "散步", "sàn bù", "v.", "sayr qilmoq", "гулять", "сайругашт кардан"),
            _word(21, "指", "zhǐ", "v.", "nazarda tutmoq", "указывать, означать", "ишора кардан, маъно додан"),
            _word(22, "精神", "jīngshén", "n.", "ruhiy holat, ruh", "дух, психика", "руҳ, ҳолати равонӣ"),
            _word(23, "教授", "jiàoshòu", "n.", "professor", "профессор", "профессор"),
            _word(24, "数字", "shùzì", "n.", "raqam", "цифра, число", "рақам"),
            _word(25, "说明", "shuōmíng", "v.", "tushuntirmoq, ko'rsatmoq", "объяснять, показывать", "фаҳмондан, нишон додан"),
            _word(26, "要是", "yàoshi", "conj.", "agar", "если", "агар"),
            _word(27, "既", "jì", "adv.", "既...又: ham...ham", "и..., и...", "ҳам...ҳам"),
            _word(28, "减肥", "jiǎn féi", "v.", "ozmoq", "худеть", "вазн кам кардан"),
            _word(29, "辛苦", "xīnkǔ", "adj.", "mashaqqatli", "тяжёлый, утомительный", "заҳматнок"),
            _word(30, "肚子", "dùzi", "n.", "qorin", "живот", "шикам"),
            _word(31, "感情", "gǎnqíng", "n.", "his-tuyg'u, munosabat", "чувства, отношения", "эҳсос, муносибат"),
            _word(32, "烦恼", "fánnǎo", "adj./n.", "tashvish, xafa bo'lish", "забота, тревога", "ташвиш, ғам"),
            _word(33, "掉", "diào", "v.", "tushib ketmoq; yo'qolmoq", "падать; исчезать", "афтидан; гум шудан"),
        ],
        "grammar": [
            _grammar(
                1,
                "估计",
                "taxmin qilish",
                "предполагать",
                "тахмин кардан",
                "Aniq dalil bo'lmaganda sabab yoki natijani ehtimol sifatida aytadi.",
                "Используется, когда причина или результат называются как предположение.",
                "Вақте сабаб ё натиҷа тахминӣ гуфта мешавад, истифода мешавад.",
                "我还不习惯北方的气候，估计是天气太干。",
                "Wǒ hái bù xíguàn běifāng de qìhòu, gūjì shì tiānqì tài gān.",
                "Men hali shimol iqlimiga ko'nikmadim, taxminan havo juda quruq.",
                "Я ещё не привык к северному климату, наверное, воздух слишком сухой.",
                "Ман ҳанӯз ба иқлими шимол одат накардаам, шояд ҳаво хеле хушк аст.",
            ),
            _grammar(
                2,
                "来不及",
                "ulgurmaslik, kech bo'lish",
                "не успеть, быть слишком поздно",
                "вақт нарасидан, дер шудан",
                "Biror ishni qilishga vaqt yetmasligini yoki keyin pushaymon bo'lish kech bo'lishini bildiradi.",
                "Показывает, что времени на действие не хватит или сожалеть будет уже поздно.",
                "Нишон медиҳад, ки барои амал вақт намерасад ё баъд пушаймон шудан дер мешавад.",
                "等你身体出现问题了，后悔就来不及了。",
                "Děng nǐ shēntǐ chūxiàn wèntí le, hòuhuǐ jiù láibují le.",
                "Tanangda muammo paydo bo'lgandan keyin pushaymon bo'lish kech bo'ladi.",
                "Когда со здоровьем появятся проблемы, сожалеть будет уже поздно.",
                "Вақте дар саломатият мушкил пайдо шавад, пушаймон шудан дер мешавад.",
            ),
            _grammar(
                3,
                "离合词重叠",
                "ajraladigan fe'lni takrorlash",
                "удвоение разделяемых глаголов",
                "такрори феълҳои ҷудошаванда",
                "散步 kabi ajraladigan fe'llarda birinchi bo'g'in takrorlanib, harakatni yengil va qisqa ko'rsatadi.",
                "В разделяемых глаголах вроде 散步 первый компонент повторяется, показывая лёгкое короткое действие.",
                "Дар феълҳои ҷудошаванда мисли 散步 қисми аввал такрор шуда, амали сабук ва кӯтоҳро нишон медиҳад.",
                "咱们午饭后就去附近的公园散散步吧。",
                "Zánmen wǔfàn hòu jiù qù fùjìn de gōngyuán sàn san bù ba.",
                "Tushlikdan keyin yaqin bog'ga biroz sayr qilgani boraylik.",
                "После обеда давай немного прогуляемся в ближайшем парке.",
                "Баъди хӯроки нисфирӯзӣ ба боғи наздик каме сайр кунем.",
            ),
            _grammar(
                4,
                "要是",
                "agar, mabodo",
                "если",
                "агар",
                "Shart kiritadi; ko'pincha natija keyingi qismda keladi.",
                "Вводит условие; результат обычно стоит во второй части.",
                "Шартро меорад; натиҷа одатан дар қисми дуюм меояд.",
                "要是健康是1，其他都是1后面的0。",
                "Yàoshi jiànkāng shì yī, qítā dōu shì yī hòumian de líng.",
                "Agar sog'liq 1 bo'lsa, qolgan narsalar 1 ortidagi nollar.",
                "Если здоровье это 1, всё остальное - нули после единицы.",
                "Агар саломатӣ 1 бошад, чизҳои дигар сифрҳои баъди онанд.",
            ),
            _grammar(
                5,
                "既……又/也/还……",
                "ham..., ham...",
                "и..., и...",
                "ҳам..., ҳам...",
                "Bir narsaning ikki ijobiy tomoni borligini bog'lab ko'rsatadi.",
                "Соединяет два положительных качества или результата одного действия.",
                "Ду тарафи мусбати як чизро пайваст нишон медиҳад.",
                "散步是生活中最简单的锻炼方法，既可以活动身体，又可以减肥。",
                "Sànbù shì shēnghuó zhōng zuì jiǎndān de duànliàn fāngfǎ, jì kěyǐ huódòng shēntǐ, yòu kěyǐ jiǎnféi.",
                "Sayr qilish eng oddiy mashq usuli: ham tanani harakatlantiradi, ham ozishga yordam beradi.",
                "Прогулка - самый простой способ тренировки: и тело двигается, и худеть помогает.",
                "Сайр содатарин усули машқ аст: ҳам баданро ҳаракат медиҳад, ҳам ба кам кардани вазн ёрӣ мекунад.",
            ),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "小李 va 小林 iqlim, shamollash va havo almashtirish haqida gaplashadi",
                "scene_ru": "小李 и 小林 говорят о климате, простуде и проветривании",
                "scene_tj": "小李 ва 小林 дар бораи иқлим, шамолхӯрӣ ва ҳавои тоза гуфтугӯ мекунанд",
                "word_nos": [1, 2, 3, 4, 5, 6, 7, 8],
                "grammar_nos": [1],
                "dialogue": [
                    _line("小李", "你的鼻子怎么流血了？快用纸擦擦。", "Nǐ de bízi zěnme liúxiě le? Kuài yòng zhǐ cā ca.", "Burningdan nega qon ketyapti? Tez qog'oz bilan art.", "Почему у тебя кровь из носа? Быстро вытри бумагой.", "Чаро аз биният хун меравад? Зуд бо коғаз пок кун."),
                    _line("小林", "我还不习惯北方的气候，估计是天气太干。今天天气不是很冷，你怎么穿这么多？", "Wǒ hái bù xíguàn běifāng de qìhòu, gūjì shì tiānqì tài gān. Jīntiān tiānqì bú shì hěn lěng, nǐ zěnme chuān zhème duō?", "Men hali shimol iqlimiga ko'nikmadim, taxminan havo juda quruq. Bugun havo uncha sovuq emas, nega bunchalik ko'p kiyinding?", "Я ещё не привык к северному климату, наверное, слишком сухо. Сегодня не очень холодно, почему ты так тепло оделся?", "Ман ҳанӯз ба иқлими шимол одат накардаам, шояд ҳаво хеле хушк аст. Имрӯз ҳаво он қадар сард нест, чаро ин қадар бисёр пӯшидаӣ?"),
                    _line("小李", "就是因为昨天穿得太少，我都感冒了。", "Jiù shì yīnwèi zuótiān chuān de tài shǎo, wǒ dōu gǎnmào le.", "Aynan kecha kam kiyinganim uchun shamollab qoldim.", "Именно потому что вчера я оделся слишком легко, я простудился.", "Маҳз барои он ки дирӯз кам пӯшидам, шамол хӯрдам."),
                    _line("小林", "最近感冒的人特别多。你去看医生了吗？", "Zuìjìn gǎnmào de rén tèbié duō. Nǐ qù kàn yīshēng le ma?", "So'nggi payt shamollaganlar juda ko'p. Shifokorga bordingmi?", "В последнее время простуженных особенно много. Ты ходил к врачу?", "Вақтҳои охир одамони шамолхӯрда хеле зиёданд. Ба духтур рафтӣ?"),
                    _line("小李", "没有，我只是咳嗽，有点儿头疼，不严重，多喝点儿水就好了。", "Méiyǒu, wǒ zhǐshì késou, yǒudiǎnr tóuténg, bù yánzhòng, duō hē diǎnr shuǐ jiù hǎo le.", "Yo'q, faqat yo'talyapman, boshim biroz og'riyapti, jiddiy emas, ko'proq suv ichsam bo'ladi.", "Нет, я только кашляю, немного болит голова, не серьёзно, побольше воды - и пройдёт.", "Не, танҳо сулфа мекунам, каме сарам дард мекунад, ҷиддӣ нест, бештар об нӯшам хуб мешавад."),
                    _line("小林", "春天天气时冷时热，特别容易感冒。这时候一定要多注意保暖，另外，最好经常打开窗户换换空气。", "Chūntiān tiānqì shí lěng shí rè, tèbié róngyì gǎnmào. Zhè shíhou yídìng yào duō zhùyì bǎonuǎn, lìngwài, zuìhǎo jīngcháng dǎkāi chuānghu huàn huan kōngqì.", "Bahorda havo goh sovuq, goh issiq bo'ladi, juda oson shamollab qolasan. Bu paytda issiq yurishga e'tibor berish kerak, yana derazani tez-tez ochib havoni almashtirgan yaxshi.", "Весной погода то холодная, то тёплая, очень легко простудиться. В это время важно беречь тепло, а ещё лучше часто открывать окна и проветривать.", "Баҳор ҳаво гоҳ сард, гоҳ гарм мешавад, зуд шамол хӯрдан мумкин. Дар ин вақт бояд гармиро нигоҳ дошт, инчунин беҳтар аст тирезаҳоро зуд-зуд кушода ҳаворо иваз кард."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "小夏 va 小雨 chekishning zararini muhokama qiladi",
                "scene_ru": "小夏 и 小雨 обсуждают вред курения",
                "scene_tj": "小夏 ва 小雨 зарари тамокукаширо муҳокима мекунанд",
                "word_nos": [9, 10, 11, 12, 13, 14, 15],
                "grammar_nos": [2],
                "dialogue": [
                    _line("小夏", "你咳嗽好点儿了吗？医生怎么说的？", "Nǐ késou hǎo diǎnr le ma? Yīshēng zěnme shuō de?", "Yo'taling yaxshiroq bo'ldimi? Shifokor nima dedi?", "Кашель стал лучше? Что сказал врач?", "Сулфаат беҳтар шуд? Духтур чӣ гуфт?"),
                    _line("小雨", "还是老样子，他让我以后不要再抽烟了。", "Háishi lǎo yàngzi, tā ràng wǒ yǐhòu búyào zài chōuyān le.", "Hali ham o'sha holat, u menga bundan keyin chekmaslikni aytdi.", "Всё по-старому, он сказал мне больше не курить.", "Ҳоло ҳам ҳамон хел, ӯ гуфт, ки минбаъд тамоку накашам."),
                    _line("小夏", "抽烟对身体一点儿好处也没有。", "Chōuyān duì shēntǐ yìdiǎnr hǎochù yě méiyǒu.", "Chekishning tanaga biror foydasi ham yo'q.", "Курение совсем не приносит пользы здоровью.", "Тамокукашӣ ба бадан ҳеҷ фоида надорад."),
                    _line("小雨", "我也知道，可是我觉得抽烟这个动作看上去很帅。", "Wǒ yě zhīdào, kěshì wǒ juéde chōuyān zhège dòngzuò kàn shangqu hěn shuài.", "Men ham bilaman, lekin chekish harakati ko'rinishidan juda kelishgan tuyuladi.", "Я тоже знаю, но мне кажется, что жест курения выглядит стильно.", "Ман ҳам медонам, вале ба назарам ҳаракати тамокукашӣ зебо менамояд."),
                    _line("小夏", "等你身体出现问题了，后悔就来不及了。", "Děng nǐ shēntǐ chūxiàn wèntí le, hòuhuǐ jiù láibují le.", "Tanangda muammo paydo bo'lgandan keyin pushaymon bo'lish kech bo'ladi.", "Когда появятся проблемы со здоровьем, сожалеть будет поздно.", "Вақте дар саломатият мушкил пайдо шавад, пушаймон шудан дер мешавад."),
                    _line("小雨", "其实家人也一直反对我抽烟，我自己却觉得没什么。但最近总是咳嗽，所以我有些担心了。", "Qíshí jiārén yě yìzhí fǎnduì wǒ chōuyān, wǒ zìjǐ què juéde méi shénme. Dàn zuìjìn zǒng shì késou, suǒyǐ wǒ yǒuxiē dānxīn le.", "Aslida oilam ham doim chekishimga qarshi, men esa buni hech narsa emas deb o'ylardim. Lekin oxirgi payt doim yo'talyapman, shuning uchun biroz xavotirdaman.", "Вообще семья всегда была против моего курения, а я думал, что это ничего страшного. Но в последнее время я всё время кашляю, поэтому начал беспокоиться.", "Дар асл оилаам ҳамеша зидди тамокукашии ман буд, вале худам фикр мекардам ҳеҷ гап нест. Аммо вақтҳои охир ҳамеша сулфа мекунам, бинобар ин каме хавотир шудам."),
                    _line("小夏", "抽烟不仅对自己没好处，还会影响周围人的身体健康。为了你和你的家人，别再抽了。", "Chōuyān bùjǐn duì zìjǐ méi hǎochù, hái huì yǐngxiǎng zhōuwéi rén de shēntǐ jiànkāng. Wèile nǐ hé nǐ de jiārén, bié zài chōu le.", "Chekish nafaqat o'zingga foydasiz, atrofdagilar sog'lig'iga ham ta'sir qiladi. O'zing va oilang uchun boshqa chekma.", "Курение не только тебе не полезно, оно ещё влияет на здоровье окружающих. Ради себя и семьи больше не кури.", "Тамокукашӣ на танҳо ба худат фоида надорад, ба саломатии атрофиён ҳам таъсир мекунад. Барои худат ва оилаат дигар накаш."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "小李 va 小林 kompyuter oldida uzoq o'tirish haqida gaplashadi",
                "scene_ru": "小李 и 小林 говорят о долгой работе за компьютером",
                "scene_tj": "小李 ва 小林 дар бораи дароз нишастан назди компютер гуфтугӯ мекунанд",
                "word_nos": [16, 17, 18, 19, 20],
                "grammar_nos": [3],
                "dialogue": [
                    _line("小李", "我最近眼睛总是跳，大夫说是因为我长时间看电脑，眼睛太累。", "Wǒ zuìjìn yǎnjing zǒng shì tiào, dàifu shuō shì yīnwèi wǒ cháng shíjiān kàn diànnǎo, yǎnjing tài lèi.", "Oxirgi payt ko'zim tez-tez uchyapti, shifokor uzoq vaqt kompyuterga qaraganim uchun ko'zim juda charchaganini aytdi.", "В последнее время у меня часто дёргается глаз, врач сказал, что это из-за долгой работы за компьютером: глаза слишком устали.", "Вақтҳои охир чашмам зуд-зуд мепарад, духтур гуфт, ки аз дароз ба компютер нигоҳ кардан аст, чашмҳо хеле хаста шудаанд."),
                    _line("小林", "长时间坐在电脑前面工作，眼睛很容易累。最好是每过一小时就休息休息，然后再开始工作。", "Cháng shíjiān zuò zài diànnǎo qiánmian gōngzuò, yǎnjing hěn róngyì lèi. Zuìhǎo shì měi guò yì xiǎoshí jiù xiūxi xiūxi, ránhòu zài kāishǐ gōngzuò.", "Kompyuter oldida uzoq ishlaganda ko'z oson charchaydi. Har bir soatdan keyin biroz dam olib, keyin yana ishlagan yaxshi.", "Если долго сидеть за компьютером, глаза легко устают. Лучше каждый час немного отдыхать, а потом снова работать.", "Агар муддати дароз назди компютер кор кунӣ, чашм зуд хаста мешавад. Беҳтар аст ҳар як соат каме истироҳат карда, баъд корро давом диҳӣ."),
                    _line("小李", "医生也这么说，他还告诉我要多向远处看看，尤其是多看看绿色的植物。", "Yīshēng yě zhème shuō, tā hái gàosu wǒ yào duō xiàng yuǎnchù kàn kan, yóuqí shì duō kàn kan lǜsè de zhíwù.", "Shifokor ham shunday dedi, u yana ko'proq uzoqqa, ayniqsa yashil o'simliklarga qarashim kerakligini aytdi.", "Врач тоже так сказал, ещё посоветовал чаще смотреть вдаль, особенно на зелёные растения.", "Духтур ҳам ҳаминро гуфт, боз маслиҳат дод, ки бештар ба дурӣ, хусусан ба растаниҳои сабз нигоҳ кунам."),
                    _line("小林", "长时间对着电脑不仅对眼睛不好，身体也会不舒服。研究发现，如果人一天静坐超过6小时，就会影响身体健康。", "Cháng shíjiān duì zhe diànnǎo bùjǐn duì yǎnjing bù hǎo, shēntǐ yě huì bù shūfu. Yánjiū fāxiàn, rúguǒ rén yì tiān jìngzuò chāoguò liù xiǎoshí, jiù huì yǐngxiǎng shēntǐ jiànkāng.", "Kompyuterga uzoq tikilish nafaqat ko'zga yomon, tana ham noqulay bo'ladi. Tadqiqotga ko'ra, odam bir kunda 6 soatdan ortiq jim o'tirsa, sog'lig'iga ta'sir qiladi.", "Долго сидеть перед компьютером плохо не только для глаз, тело тоже чувствует дискомфорт. Исследования показывают: если человек сидит неподвижно больше 6 часов в день, это влияет на здоровье.", "Дароз назди компютер будан на танҳо барои чашм бад аст, бадан ҳам нороҳат мешавад. Таҳқиқот нишон медиҳад: агар одам дар як рӯз зиёда аз 6 соат беҳаракат нишинад, ба саломатӣ таъсир мекунад."),
                    _line("小李", "是啊！像咱们这些久坐办公室的人要注意，有时间应该多站起来活动活动。", "Shì a! Xiàng zánmen zhèxiē jiǔ zuò bàngōngshì de rén yào zhùyì, yǒu shíjiān yīnggāi duō zhàn qǐlai huódòng huódòng.", "Ha! Biz kabi ofisda uzoq o'tiradigan odamlar e'tibor berishi kerak, vaqt bo'lsa ko'proq turib harakat qilish kerak.", "Да! Людям вроде нас, которые долго сидят в офисе, нужно быть внимательнее; когда есть время, надо вставать и двигаться.", "Ҳа! Одамоне мисли мо, ки дар офис дер менишинанд, бояд диққат кунанд; вақт бошад, бештар хеста ҳаракат кардан лозим."),
                    _line("小林", "好，咱们午饭后就去附近的公园散散步吧。", "Hǎo, zánmen wǔfàn hòu jiù qù fùjìn de gōngyuán sàn san bù ba.", "Mayli, tushlikdan keyin yaqin bog'ga biroz sayr qilgani boraylik.", "Хорошо, после обеда пойдём немного прогуляемся в ближайший парк.", "Хуб, баъди хӯроки нисфирӯзӣ ба боғи наздик каме сайр кунем."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Sog'liq faqat kasal bo'lmaslik emasligi haqida matn",
                "scene_ru": "Текст о том, что здоровье - это не только отсутствие болезни",
                "scene_tj": "Матн дар бораи он ки саломатӣ танҳо бемор набудан нест",
                "word_nos": [21, 22, 23, 24, 25, 26],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "每个人都希望自己健康，那么什么才是健康呢？过去，人们认为健康就是指身体不生病。但是，现在人们认识到，健康还指精神上的健康。只有身体和精神都健康，才算是真正的健康。有一位教授用数字来说明健康有多么重要：要是健康是1，其他都是1后面的0；如果没有1，不管有多少0也没用。所以我们平时一定要注意锻炼，别等健康出问题了才后悔。", "Měi ge rén dōu xīwàng zìjǐ jiànkāng, nàme shénme cái shì jiànkāng ne? Guòqù, rénmen rènwéi jiànkāng jiùshì zhǐ shēntǐ bù shēngbìng. Dànshì, xiànzài rénmen rènshi dào, jiànkāng hái zhǐ jīngshén shàng de jiànkāng.", "Har bir odam sog'lom bo'lishni xohlaydi, unda sog'liq nima? Avvallari odamlar sog'liq tananing kasal bo'lmasligi deb o'ylardi. Hozir esa sog'liq ruhiy sog'liqni ham anglatishini tushunishadi. Tana ham ruh ham sog'lom bo'lsagina haqiqiy sog'liq bo'ladi. Bir professor sog'liq muhimligini raqam bilan tushuntirgan: agar sog'liq 1 bo'lsa, qolgan hammasi uning ortidagi 0; 1 bo'lmasa, qancha 0 bo'lsa ham foydasi yo'q. Shuning uchun odatda mashq qilishga e'tibor berish kerak, sog'liq muammoga aylangandan keyin pushaymon bo'lmang.", "Каждый хочет быть здоровым. Но что такое здоровье? Раньше люди думали, что здоровье - это когда тело не болеет. Сейчас люди понимают, что здоровье включает и психическое состояние. Только когда здоровы и тело, и дух, это настоящее здоровье. Один профессор объяснил важность здоровья цифрами: если здоровье - это 1, всё остальное - нули после него; если нет 1, сколько бы нулей ни было, пользы нет. Поэтому обычно нужно заниматься физической активностью и не ждать проблем со здоровьем, чтобы сожалеть.", "Ҳар кас мехоҳад солим бошад. Пас саломатӣ чист? Пештар одамон фикр мекарданд, саломатӣ яъне бадан бемор нест. Ҳоло одамон мефаҳманд, ки саломатӣ ҳолати равониро ҳам дар бар мегирад. Танҳо вақте бадан ва руҳ ҳарду солиманд, саломатии ҳақиқӣ аст. Як профессор бо рақамҳо фаҳмонд, ки саломатӣ чӣ қадар муҳим аст: агар саломатӣ 1 бошад, дигар чизҳо сифрҳои баъди онанд; агар 1 набошад, ҳар қадар сифр бошад ҳам фоида надорад. Бинобар ин одатан бояд ба машқ диққат кунем ва мунтазир нашавем, ки мушкил пайдо шуда баъд пушаймон шавем."),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Sayr qilish eng oddiy mashq ekanligi haqida matn",
                "scene_ru": "Текст о прогулке как самом простом виде тренировки",
                "scene_tj": "Матн дар бораи сайр ҳамчун содатарин машқ",
                "word_nos": [27, 28, 29, 30, 31, 32, 33],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "我听一位医生说过一句话：“最好的医生是自己，最好的药是时间，最好的运动是散步。”前两条我理解得不深，最后一条我完全同意。散步是生活中最简单的锻炼方法，既可以活动身体，又可以减肥，而且不会像跑步那样辛苦。晚饭后，一家人一起出去散散步，是一件很幸福的事情。肚子吃饱了需要活动，家人忙了一天需要交流，夫妻说说一天的工作能加深感情，听孩子谈谈学校里有意思的事，一天的烦恼就都跑掉了。", "Wǒ tīng yí wèi yīshēng shuōguo yí jù huà: Zuì hǎo de yīshēng shì zìjǐ, zuì hǎo de yào shì shíjiān, zuì hǎo de yùndòng shì sànbù.", "Men bir shifokordan shunday gap eshitganman: eng yaxshi shifokor - o'zing, eng yaxshi dori - vaqt, eng yaxshi sport - sayr. Birinchi ikki fikrni chuqur tushunmayman, lekin oxirgisiga to'liq qo'shilaman. Sayr hayotdagi eng oddiy mashq: ham tanani harakatlantiradi, ham ozishga yordam beradi, yugurishdek mashaqqatli emas. Kechki ovqatdan keyin oila bilan sayr qilish juda baxtli ish. Qorin to'yganda harakat kerak, oila a'zolari kun bo'yi band bo'lgach muloqot kerak, er-xotin ish haqida gaplashsa munosabat chuqurlashadi, bola maktabdagi qiziq voqealarni aytsa, kunlik tashvishlar yo'qoladi.", "Я слышал от одного врача фразу: лучший врач - ты сам, лучшее лекарство - время, лучший спорт - прогулка. Первые две мысли я понимаю не глубоко, но с последней полностью согласен. Прогулка - самый простой способ тренировки: она двигает тело, помогает худеть и не такая тяжёлая, как бег. После ужина всей семьёй выйти погулять - очень счастливое дело. После еды телу нужно движение, семье после занятого дня нужно общение; разговор супругов о работе укрепляет отношения, рассказы ребёнка о школе уносят дневные заботы.", "Ман аз як духтур чунин сухан шунидаам: беҳтарин духтур худат ҳастӣ, беҳтарин дору вақт аст, беҳтарин варзиш сайр аст. Ду фикри аввалро чандон чуқур намефаҳмам, вале бо охирин пурра розиям. Сайр содатарин машқ аст: ҳам баданро ҳаракат медиҳад, ҳам вазнро кам мекунад ва мисли давидан заҳматнок нест. Баъди шом оила якҷоя сайр кунад, кори хушбахтона аст. Баъди сер шудан бадан ҳаракат мехоҳад, аҳли оила баъди рӯзи серкор муошират мехоҳанд; гуфтугӯи ҳамсарҳо муносибатро амиқ мекунад, сухани кӯдак аз мактаб ташвишҳои рӯзро мебарад."),
                ],
            },
        ],
    },
    8: {
        "title": "生活中不缺少美",
        "goal": {
            "uz": "kayfiyat, go'zallik va hayotga munosabat haqida gapirish; 使, 只要, 可不是, 因此 va 往往 grammatikalarini ishlatish",
            "ru": "говорить о настроении, красоте и отношении к жизни; использовать 使, 只要, 可不是, 因此 и 往往",
            "tj": "дар бораи кайфият, зебоӣ ва муносибат ба зиндагӣ гуфтугӯ кардан; истифодаи 使, 只要, 可不是, 因此 ва 往往",
        },
        "intro_text": {
            "uz": "Bu darsda shokolad va kayfiyat, sportdagi bosim, tirbandlik va hayotdagi go'zallikni ko'rish haqida gapirishni o'rganasiz. Har qismda yangi so'zlar, pinyin, tarjima va o'sha matnga mos grammatika beriladi.",
            "ru": "В этом уроке вы научитесь говорить о шоколаде и настроении, давлении в спорте, пробках и умении видеть красоту в жизни. В каждой части есть слова, pinyin, перевод и грамматика по тексту.",
            "tj": "Дар ин дарс дар бораи шоколад ва кайфият, фишори варзиш, роҳбандӣ ва дидани зебоӣ дар зиндагӣ гуфтугӯ карданро меомӯзед. Дар ҳар қисм калимаҳо, pinyin, тарҷума ва грамматикаи мувофиқи матн ҳаст.",
        },
        "vocabulary": [
            _word(1, "巧克力", "qiǎokèlì", "n.", "shokolad", "шоколад", "шоколад"),
            _word(2, "亲戚", "qīnqi", "n.", "qarindosh", "родственник", "хешованд"),
            _word(3, "伤心", "shāngxīn", "adj.", "xafa, g'amgin", "грустный", "ғамгин"),
            _word(4, "使", "shǐ", "v.", "qilmoq, sabab bo'lmoq", "заставлять, делать", "сабаб шудан, кардан"),
            _word(5, "心情", "xīnqíng", "n.", "kayfiyat", "настроение", "кайфият"),
            _word(6, "愉快", "yúkuài", "adj.", "xursand, yoqimli", "радостный, приятный", "хурсанд, хуш"),
            _word(7, "景色", "jǐngsè", "n.", "manzara", "пейзаж, вид", "манзара"),
            _word(8, "放松", "fàngsōng", "v.", "bo'shashmoq, dam olmoq", "расслабляться", "ором шудан"),
            _word(9, "压力", "yālì", "n.", "bosim", "давление, стресс", "фишор"),
            _word(10, "回忆", "huíyì", "v./n.", "eslamoq; xotira", "вспоминать; воспоминание", "ба ёд овардан; хотира"),
            _word(11, "发生", "fāshēng", "v.", "sodir bo'lmoq", "происходить", "рӯй додан"),
            _word(12, "成为", "chéngwéi", "v.", "bo'lib qolmoq", "становиться", "шудан"),
            _word(13, "只要", "zhǐyào", "conj.", "faqat ... bo'lsa", "если только", "то даме ки, агар"),
            _word(14, "师傅", "shīfu", "n.", "usta; haydovchiga murojaat", "мастер; обращение к водителю", "усто; муроҷиат ба ронанда"),
            _word(15, "大使馆", "dàshǐguǎn", "n.", "elchixona", "посольство", "сафорат"),
            _word(16, "堵车", "dǔ chē", "v.", "tirbandlik bo'lmoq", "быть пробке", "роҳбандӣ шудан"),
            _word(17, "距离", "jùlí", "n.", "masofa", "расстояние", "масофа"),
            _word(18, "耐心", "nàixīn", "n.", "sabr", "терпение", "сабр"),
            _word(19, "生命", "shēngmìng", "n.", "hayot", "жизнь", "ҳаёт"),
            _word(20, "缺少", "quēshǎo", "v.", "kam bo'lmoq, yetishmaslik", "недоставать", "камӣ кардан"),
            _word(21, "到处", "dàochù", "adv.", "hamma joyda", "повсюду", "ҳама ҷо"),
            _word(22, "态度", "tàidu", "n.", "munosabat", "отношение", "муносибат"),
            _word(23, "因此", "yīncǐ", "conj.", "shuning uchun", "поэтому", "бинобар ин"),
            _word(24, "科学", "kēxué", "n.", "fan, ilm", "наука", "илм"),
            _word(25, "证明", "zhèngmíng", "v.", "isbotlamoq", "доказывать", "исбот кардан"),
            _word(26, "往往", "wǎngwǎng", "adv.", "ko'pincha", "часто, как правило", "аксар вақт"),
            _word(27, "阳光", "yángguāng", "adj./n.", "quyoshli; ijobiy", "солнечный; позитивный", "офтобӣ; мусбат"),
            _word(28, "积极", "jījí", "adj.", "faol, ijobiy", "активный, позитивный", "фаъол, мусбат"),
            _word(29, "特点", "tèdiǎn", "n.", "xususiyat", "особенность", "хусусият"),
        ],
        "grammar": [
            _grammar(1, "使", "sabab bo'lmoq", "делать, вызывать", "сабаб шудан", "A 使 B + sifat/fe'l shaklida A ning B holatini o'zgartirishini bildiradi.", "В конструкции A 使 B + прилагательное/глагол A вызывает изменение состояния B.", "Дар қолиби A 使 B + сифат/феъл A ҳолати B-ро тағйир медиҳад.", "听说伤心难过的时候吃块儿巧克力，还能使人的心情变得愉快。", "Tīngshuō shāngxīn nánguò de shíhou chī kuàir qiǎokèlì, hái néng shǐ rén de xīnqíng biàn de yúkuài.", "Eshitishimcha, xafa paytda shokolad yeyish odam kayfiyatini yaxshilashi mumkin.", "Говорят, когда грустно, кусочек шоколада может сделать настроение лучше.", "Мегӯянд, вақте ғамгин ҳастӣ, як порча шоколад метавонад кайфиятро хуш кунад."),
            _grammar(2, "只要……就……", "faqat ... bo'lsa, ...", "если только..., то...", "то даме ки..., пас...", "Yetarli shartni bildiradi: shart bajarilsa, natija paydo bo'ladi.", "Выражает достаточное условие: если условие выполняется, появляется результат.", "Шарти кофиро нишон медиҳад: агар шарт иҷро шавад, натиҷа пайдо мешавад.", "只要这次你好好儿准备，一定能把比赛踢好。", "Zhǐyào zhè cì nǐ hǎohāor zhǔnbèi, yídìng néng bǎ bǐsài tī hǎo.", "Bu safar yaxshi tayyorlansang, albatta musobaqani yaxshi o'ynaysan.", "Если в этот раз хорошо подготовишься, обязательно хорошо сыграешь матч.", "Агар ин дафъа хуб тайёр шавӣ, ҳатман бозиро хуб мегузаронӣ."),
            _grammar(3, "可不是", "ha, aynan shunday", "ещё бы, именно так", "ҳа, айнан ҳамин", "Suhbatdosh fikriga kuchli rozilik bildiradi.", "Выражает сильное согласие с собеседником.", "Розигии қавӣ ба фикри ҳамсуҳбатро нишон медиҳад.", "可不是！上班堵车怕迟到，下班堵车怕回家晚。", "Kěbúshì! Shàngbān dǔchē pà chídào, xiàbān dǔchē pà huí jiā wǎn.", "Ha, aynan shunday! Ishga ketishda tirbandlikdan kech qolishdan, qaytishda uyga kech borishdan qo'rqasan.", "Ещё бы! По дороге на работу боишься опоздать, после работы - поздно вернуться домой.", "Ҳа, айнан ҳамин! Ба кор рафтанда аз дер мондан, аз кор баргаштанда аз дер расидан метарсӣ."),
            _grammar(4, "因此", "shuning uchun", "поэтому", "бинобар ин", "Oldingi sababdan kelib chiqqan natijani bog'laydi.", "Связывает результат с предыдущей причиной.", "Натиҷаро бо сабаби пешина мепайвандад.", "生活的态度要自己选择，因此，遇到烦恼时，你应该想一些办法让自己从不高兴的心情中走出来。", "Shēnghuó de tàidu yào zìjǐ xuǎnzé, yīncǐ, yùdào fánnǎo shí, nǐ yīnggāi xiǎng yìxiē bànfǎ.", "Hayotga munosabatni o'zing tanlaysan, shuning uchun tashvishga duch kelsang, kayfiyatni chiqarish yo'lini topish kerak.", "Отношение к жизни выбираешь сам, поэтому при тревогах нужно найти способ выйти из плохого настроения.", "Муносибат ба зиндагиро худ интихоб мекунӣ, бинобар ин ҳангоми ташвиш бояд роҳи баромадан аз кайфияти бадро ёфт."),
            _grammar(5, "往往", "ko'pincha", "часто, как правило", "аксар вақт", "Odatda takrorlanadigan yoki umumiy kuzatiladigan holatni bildiradi.", "Показывает обычно повторяющееся или типичное явление.", "Ҳолати такроршаванда ё маъмулро нишон медиҳад.", "女孩子对衣服颜色的选择往往与她们的性格有关。", "Nǚháizi duì yīfu yánsè de xuǎnzé wǎngwǎng yǔ tāmen de xìnggé yǒuguān.", "Qizlarning kiyim rangi tanlovi ko'pincha ularning xarakteri bilan bog'liq.", "Выбор цвета одежды у девушек часто связан с их характером.", "Интихоби ранги либос дар духтарон аксаран бо характери онҳо вобаста аст."),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "李老师 va 高老师 shokolad va kayfiyat haqida gaplashadi",
                "scene_ru": "李老师 и 高老师 говорят о шоколаде и настроении",
                "scene_tj": "李老师 ва 高老师 дар бораи шоколад ва кайфият гуфтугӯ мекунанд",
                "word_nos": [1, 2, 3, 4, 5, 6],
                "grammar_nos": [1],
                "dialogue": [
                    _line("李老师", "这种巧克力味道不错，你在哪儿买的？", "Zhè zhǒng qiǎokèlì wèidao búcuò, nǐ zài nǎr mǎi de?", "Bu shokoladning ta'mi yaxshi ekan, qayerdan oldingiz?", "У этого шоколада хороший вкус, где вы его купили?", "Маззаи ин шоколад хуб аст, аз куҷо харидед?"),
                    _line("高老师", "不是我买的，是我女儿给我从国外带回来的礼物。", "Bú shì wǒ mǎi de, shì wǒ nǚ'ér gěi wǒ cóng guówài dài huílai de lǐwù.", "Men olmaganman, qizim chet eldan olib kelgan sovg'a.", "Это не я купила, это подарок, который дочь привезла мне из-за границы.", "Ман нахаридаам, ин туҳфаест, ки духтарам аз хориҷ овардааст."),
                    _line("李老师", "很多人出国后常常会买外国的巧克力，回来送给亲戚朋友。", "Hěn duō rén chūguó hòu chángcháng huì mǎi wàiguó de qiǎokèlì, huílai sòng gěi qīnqi péngyou.", "Ko'p odamlar chet elga chiqqach xorijiy shokolad olib, qaytgach qarindosh-do'stlarga sovg'a qiladi.", "Многие после поездки за границу покупают иностранный шоколад и дарят родственникам и друзьям.", "Бисёриҳо баъди хориҷ рафтан шоколади хориҷӣ харида, ба хешу дӯстҳо туҳфа мекунанд."),
                    _line("高老师", "是啊，因为很多人都爱吃巧克力，尤其是女性。", "Shì a, yīnwèi hěn duō rén dōu ài chī qiǎokèlì, yóuqí shì nǚxìng.", "Ha, chunki ko'pchilik shokoladni yaxshi ko'radi, ayniqsa ayollar.", "Да, потому что многие любят шоколад, особенно женщины.", "Ҳа, чун бисёриҳо шоколадро дӯст медоранд, хусусан занон."),
                    _line("李老师", "这是为什么呢？", "Zhè shì wèishénme ne?", "Nega shunday?", "Почему так?", "Чаро чунин?"),
                    _line("高老师", "巧克力大多是甜的，而很多女性都喜欢吃甜的。而且，听说伤心难过的时候吃块儿巧克力，还能使人的心情变得愉快。", "Qiǎokèlì dàduō shì tián de, ér hěn duō nǚxìng dōu xǐhuan chī tián de. Érqiě, tīngshuō shāngxīn nánguò de shíhou chī kuàir qiǎokèlì, hái néng shǐ rén de xīnqíng biàn de yúkuài.", "Shokoladning ko'pi shirin, ko'p ayollar esa shirinlikni yoqtiradi. Yana eshitishimcha, xafa bo'lganda bir bo'lak shokolad yeyish kayfiyatni yaxshilaydi.", "Шоколад в основном сладкий, а многие женщины любят сладкое. К тому же говорят, когда грустно, кусочек шоколада может улучшить настроение.", "Шоколад асосан ширин аст, бисёр занон шириниро дӯст медоранд. Боз мегӯянд, вақте ғамгин ҳастӣ, як порча шоколад кайфиятро хуш мекунад."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "小夏 va 马克 futbol o'yini va bosim haqida gaplashadi",
                "scene_ru": "小夏 и 马克 говорят о матче и давлении",
                "scene_tj": "小夏 ва 马克 дар бораи бозӣ ва фишор гуфтугӯ мекунанд",
                "word_nos": [7, 8, 9, 10, 11, 12, 13],
                "grammar_nos": [2],
                "dialogue": [
                    _line("小夏", "这里的景色真美，空气也好。", "Zhèli de jǐngsè zhēn měi, kōngqì yě hǎo.", "Bu yerning manzarasi juda chiroyli, havosi ham yaxshi.", "Здесь очень красивый вид и хороший воздух.", "Манзараи ин ҷо бисёр зебо аст, ҳавояш ҳам хуб."),
                    _line("马克", "怎么样，心情好些了吗？", "Zěnmeyàng, xīnqíng hǎo xiē le ma?", "Qalay, kayfiyating yaxshilandi-mi?", "Ну как, настроение стало лучше?", "Чӣ хел, кайфиятат беҳтар шуд?"),
                    _line("小夏", "好多了，上次足球比赛后，好久都没这么放松了。", "Hǎo duō le, shàng cì zúqiú bǐsài hòu, hǎojiǔ dōu méi zhème fàngsōng le.", "Ancha yaxshi, o'tgan futbol o'yinidan beri anchadan buyon bunchalik bo'shashmagan edim.", "Намного лучше, после прошлой футбольной игры я давно так не расслаблялся.", "Хеле беҳтар, баъди бозии футболи гузашта дер боз ин қадар ором нашуда будам."),
                    _line("马克", "你不要有压力，好好儿准备下次比赛就好了。", "Nǐ búyào yǒu yālì, hǎohāor zhǔnbèi xià cì bǐsài jiù hǎo le.", "Bosim qilma, keyingi o'yinga yaxshi tayyorlansang bo'ldi.", "Не дави на себя, просто хорошо подготовься к следующему матчу.", "Фишор нагир, танҳо ба бозии навбатӣ хуб тайёр шав."),
                    _line("小夏", "这段时间我总是一个人坐在房间里回忆那次比赛。如果我们能再努力一点儿，就一定会多进一个球。", "Zhè duàn shíjiān wǒ zǒng shì yí ge rén zuò zài fángjiān li huíyì nà cì bǐsài. Rúguǒ wǒmen néng zài nǔlì yìdiǎnr, jiù yídìng huì duō jìn yí ge qiú.", "Bu vaqtda doim xonada yolg'iz o'tirib o'sha o'yinni eslayman. Agar yana biroz harakat qilganimizda, albatta yana bitta gol urardik.", "В последнее время я всё время один сижу в комнате и вспоминаю тот матч. Если бы мы постарались ещё немного, точно забили бы ещё один гол.", "Ин вақтҳо ҳамеша танҳо дар ҳуҷра нишаста он бозиро ба ёд меорам. Агар каме бештар кӯшиш мекардем, ҳатман боз як гол мезадем."),
                    _line("马克", "事情已经发生了，过去的就让它成为过去吧。只要这次你好好儿准备，一定能把比赛踢好。", "Shìqing yǐjīng fāshēng le, guòqù de jiù ràng tā chéngwéi guòqù ba. Zhǐyào zhè cì nǐ hǎohāor zhǔnbèi, yídìng néng bǎ bǐsài tī hǎo.", "Ish allaqachon bo'ldi, o'tgan narsa o'tmishda qolsin. Bu safar yaxshi tayyorlansang, albatta o'yinni yaxshi o'tkaza olasan.", "Это уже произошло, пусть прошлое останется прошлым. Если в этот раз хорошо подготовишься, обязательно сыграешь хорошо.", "Кор аллакай шуд, бигзор гузашта гузашта монад. Агар ин дафъа хуб тайёр шавӣ, ҳатман бозиро хуб мегузаронӣ."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "马克 va haydovchi tirbandlik haqida gaplashadi",
                "scene_ru": "马克 и водитель говорят о пробках",
                "scene_tj": "马克 ва ронанда дар бораи роҳбандӣ гуфтугӯ мекунанд",
                "word_nos": [14, 15, 16, 17, 18],
                "grammar_nos": [3],
                "dialogue": [
                    _line("马克", "师傅，我去大使馆，你是不是走错了？", "Shīfu, wǒ qù dàshǐguǎn, nǐ shì bú shì zǒu cuò le?", "Usta, men elchixonaga boraman, adashib ketmadingizmi?", "Водитель, мне в посольство, вы не туда поехали?", "Усто, ман ба сафорат меравам, магар роҳро хато нарафтед?"),
                    _line("师傅", "现在是上班时间，前面有点儿堵车，我们走另外一条路，距离差不多。", "Xiànzài shì shàngbān shíjiān, qiánmian yǒudiǎnr dǔchē, wǒmen zǒu lìngwài yì tiáo lù, jùlí chàbuduō.", "Hozir ishga borish vaqti, oldinda biroz tirbandlik bor. Boshqa yo'ldan yuramiz, masofa deyarli bir xil.", "Сейчас время поездки на работу, впереди пробка. Поедем другой дорогой, расстояние почти такое же.", "Ҳоло вақти ба кор рафтан аст, пеш каме роҳбандӣ ҳаст. Аз роҳи дигар меравем, масофа қариб як хел."),
                    _line("马克", "那就好，堵车浪费时间，遇到堵车，心情也“堵”。", "Nà jiù hǎo, dǔchē làngfèi shíjiān, yùdào dǔchē, xīnqíng yě dǔ.", "Unda yaxshi, tirbandlik vaqtni isrof qiladi, tirbandlikka duch kelsang kayfiyat ham 'tiqilib' qoladi.", "Тогда хорошо. Пробки тратят время, а когда попадаешь в пробку, настроение тоже будто застревает.", "Пас хуб. Роҳбандӣ вақтро беҳуда мекунад, ба роҳбандӣ афтидан кайфиятро ҳам 'мебандад'."),
                    _line("师傅", "可不是！上班堵车怕迟到，下班堵车怕回家晚。每天在马路上开车，要想不遇到堵车，还真难。", "Kěbúshì! Shàngbān dǔchē pà chídào, xiàbān dǔchē pà huí jiā wǎn. Měitiān zài mǎlù shang kāichē, yào xiǎng bù yùdào dǔchē, hái zhēn nán.", "Ha, aynan shunday! Ishga ketayotganda kech qolishdan, ishdan qaytayotganda uyga kech borishdan qo'rqasan. Har kuni yo'lda mashina haydasang, tirbandlikka uchramaslik rostdan qiyin.", "Ещё бы! Утром боишься опоздать, вечером - поздно вернуться домой. Если каждый день водить по дорогам, не попасть в пробку действительно трудно.", "Ҳа, айнан ҳамин! Ба кор рафтанда аз дер мондан, аз кор баргаштанда аз дер расидан метарсӣ. Ҳар рӯз дар роҳ рондан бошад, ба роҳбандӣ наафтодан воқеан душвор."),
                    _line("马克", "一遇到堵车，人们就容易变得没有耐心。长期这样，还会影响脾气甚至性格。但是您的心情为什么这么好呢？", "Yí yùdào dǔchē, rénmen jiù róngyì biàn de méiyǒu nàixīn. Chángqī zhèyàng, hái huì yǐngxiǎng píqi shènzhì xìnggé. Dànshì nín de xīnqíng wèishénme zhème hǎo ne?", "Tirbandlikka duch kelsa, odamlar oson sabrsiz bo'lib qoladi. Uzoq vaqt shunday bo'lsa, fe'lga, hatto xarakterga ham ta'sir qiladi. Lekin sizning kayfiyatingiz nega bunchalik yaxshi?", "Когда попадаешь в пробку, люди легко теряют терпение. Если так долго, это влияет на нрав и даже характер. Но почему у вас такое хорошее настроение?", "Ба роҳбандӣ афтад, одамон зуд бесабр мешаванд. Агар дароз чунин бошад, ба феъл ва ҳатто характер таъсир мекунад. Аммо чаро кайфияти шумо ин қадар хуб аст?"),
                    _line("师傅", "我们改变不了堵车，但是可以试着改变自己的心情。堵车时正好可以休息一下，还可以听听自己喜欢的音乐。", "Wǒmen gǎibiàn bùliǎo dǔchē, dànshì kěyǐ shì zhe gǎibiàn zìjǐ de xīnqíng. Dǔchē shí zhènghǎo kěyǐ xiūxi yíxià, hái kěyǐ tīng ting zìjǐ xǐhuan de yīnyuè.", "Tirbandlikni o'zgartira olmaymiz, lekin o'z kayfiyatimizni o'zgartirib ko'rishimiz mumkin. Tirbandlik paytida aynan dam olish, yoqtirgan musiqani tinglash mumkin.", "Пробку мы изменить не можем, но можем попробовать изменить своё настроение. Во время пробки как раз можно отдохнуть и послушать любимую музыку.", "Мо роҳбандиро тағйир дода наметавонем, вале кайфияти худро тағйир додан мумкин. Ҳангоми роҳбандӣ маҳз дам гирифтан ва мусиқии дӯстдоштаро шунидан мумкин."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Hayotdagi go'zallikni ko'rish haqida matn",
                "scene_ru": "Текст о том, как видеть красоту в жизни",
                "scene_tj": "Матн дар бораи дидани зебоӣ дар зиндагӣ",
                "word_nos": [19, 20, 21, 22, 23],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "草绿了，那是生命的颜色；花开了，那是大自然的礼物。生活中不缺少美，缺少的是发现美的眼睛。只要有心，生活中的美到处都是。生活的态度要自己选择，因此，遇到烦恼时，你应该想一些办法让自己从不高兴的心情中走出来。窗外是什么样子，我们无法改变，但我们可以选择站在哪个窗户前。选择一个能够带给我们快乐的窗户，这样才能选对心情，选对生活的态度。", "Cǎo lǜ le, nà shì shēngmìng de yánsè; huā kāi le, nà shì dà zìrán de lǐwù.", "Maysa yashillansa, bu hayot rangi; gul ochilsa, bu tabiat sovg'asi. Hayotda go'zallik kam emas, kam narsa - go'zallikni ko'ra oladigan ko'z. Ko'ngil bo'lsa, hayotdagi go'zallik hamma joyda. Hayotga munosabatni o'zing tanlaysan, shuning uchun tashvishga duch kelsang, yomon kayfiyatdan chiqish yo'lini topishing kerak. Deraza tashqarisi qandayligini o'zgartira olmaymiz, lekin qaysi deraza oldida turishni tanlay olamiz. Bizga quvonch olib keladigan derazani tanlasak, kayfiyat va hayotga munosabatni to'g'ri tanlagan bo'lamiz.", "Трава зеленеет - это цвет жизни; цветы распускаются - это подарок природы. В жизни хватает красоты, не хватает глаз, которые её находят. Если есть желание, красота повсюду. Отношение к жизни выбираешь сам, поэтому при тревогах нужно найти способ выйти из плохого настроения. Мы не можем изменить то, что за окном, но можем выбрать, у какого окна стоять. Выбрав окно, которое приносит радость, мы выбираем правильное настроение и отношение к жизни.", "Сабза сабз мешавад - ин ранги ҳаёт аст; гул мешукуфад - ин туҳфаи табиат аст. Дар зиндагӣ зебоӣ кам нест, чашме кам аст, ки онро ёбад. Агар дил бошад, зебоӣ ҳама ҷо ҳаст. Муносибат ба зиндагиро худ интихоб мекунӣ, бинобар ин ҳангоми ташвиш бояд роҳи баромадан аз кайфияти бадро ёбӣ. Мо намуди беруни тирезаро дигар карда наметавонем, вале метавонем интихоб кунем назди кадом тиреза истем. Тирезаеро интихоб кунем, ки хурсандӣ меорад, пас кайфият ва муносибати зиндагиро дуруст интихоб мекунем."),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Rang tanlovi va xarakter haqida matn",
                "scene_ru": "Текст о выборе цвета и характере",
                "scene_tj": "Матн дар бораи интихоби ранг ва характер",
                "word_nos": [24, 25, 26, 27, 28, 29],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "科学研究证明，女孩子对衣服颜色的选择往往与她们的性格有关。喜欢穿白色衣服的女孩子性格比较阳光，生活态度积极向上是她们的共同特点；而喜欢穿红色衣服的女孩子性格比较浪漫。颜色也会影响人的心情，不同的颜色会给我们带来不同的感情变化。红色让人变得热情；黄色和白色让人心情愉快；黑色却容易让人感到伤心；人们在看到蓝色时会觉得很舒服，变得安静下来；绿色让我们的眼睛得到休息。", "Kēxué yánjiū zhèngmíng, nǚháizi duì yīfu yánsè de xuǎnzé wǎngwǎng yǔ tāmen de xìnggé yǒuguān.", "Ilmiy tadqiqotlar qizlarning kiyim rangi tanlovi ko'pincha xarakteri bilan bog'liq ekanini isbotlaydi. Oq kiyimni yoqtiradigan qizlar xarakteri quyoshdek ochiqroq, hayotga faol va ijobiy munosabat ularning umumiy xususiyati; qizil kiyimni yoqtiradigan qizlar esa romantikroq bo'ladi. Ranglar ham odam kayfiyatiga ta'sir qiladi, turli ranglar turli hissiy o'zgarishlar olib keladi. Qizil odamni jo'shqin qiladi; sariq va oq kayfiyatni ko'taradi; qora esa oson g'amgin qiladi; ko'kni ko'rganda odam o'zini qulay sezadi va tinchlanadi; yashil ko'zimizni dam oldiradi.", "Научные исследования доказывают, что выбор цвета одежды у девушек часто связан с их характером. Девушки, любящие белую одежду, обычно более солнечные, их общая черта - активное и позитивное отношение к жизни; девушки, любящие красный, более романтичные. Цвета тоже влияют на настроение и приносят разные эмоциональные изменения. Красный делает людей более страстными; жёлтый и белый улучшают настроение; чёрный легко вызывает грусть; синий даёт ощущение комфорта и спокойствия; зелёный даёт глазам отдых.", "Таҳқиқоти илмӣ исбот мекунад, ки интихоби ранги либос дар духтарон аксаран бо характери онҳо вобаста аст. Духтароне, ки либоси сафедро дӯст медоранд, одатан кушодадилтаранд, муносибати фаъол ва мусбат ба зиндагӣ хусусияти умумии онҳост; духтароне, ки сурхро дӯст медоранд, бештар романтикӣ мешаванд. Рангҳо ба кайфият ҳам таъсир мекунанд ва эҳсосоти гуногун меоранд. Сурх одамро пурҳарорат мекунад; зард ва сафед кайфиятро хуш мекунанд; сиёҳ осон ғамгин мекунад; кабуд роҳат ва оромӣ медиҳад; сабз чашмро дам медиҳад."),
                ],
            },
        ],
    },
    9: {
        "title": "阳光总在风雨后",
        "goal": {
            "uz": "urinish, muvaffaqiyat va qiyinchiliklarga munosabat haqida gapirish; 难道, 通过, 可是, 结果 va 上 grammatikalarini ishlatish",
            "ru": "говорить об усилиях, успехе и отношении к трудностям; использовать 难道, 通过, 可是, 结果 и 上",
            "tj": "дар бораи кӯшиш, муваффақият ва муносибат ба мушкилӣ гуфтугӯ кардан; истифодаи 难道, 通过, 可是, 结果 ва 上",
        },
        "intro_text": {
            "uz": "Bu darsda vazn tashlash, mashqdagi qat'iyat, kasb tanlovi va muvaffaqiyatdan oldingi qiyinchiliklar haqida gapirishni o'rganasiz. Har qismda matnga mos yangi so'zlar, pinyin, tarjima va grammatika bor.",
            "ru": "В этом уроке вы научитесь говорить о похудении, настойчивости в тренировках, выборе профессии и трудностях перед успехом. В каждой части есть слова, pinyin, перевод и грамматика по своему тексту.",
            "tj": "Дар ин дарс дар бораи кам кардани вазн, устуворӣ дар машқ, интихоби касб ва мушкилиҳои пеш аз муваффақият гуфтугӯ карданро меомӯзед. Дар ҳар қисм калимаҳо, pinyin, тарҷума ва грамматикаи мувофиқи матн ҳаст.",
        },
        "vocabulary": [
            _word(1, "饼干", "bǐnggān", "n.", "pechenye", "печенье", "печенье"),
            _word(2, "难道", "nándào", "adv.", "nahotki", "неужели", "магар"),
            _word(3, "得", "děi", "v.", "kerak, majbur bo'lmoq", "нужно, придётся", "лозим аст, бояд"),
            _word(4, "坚持", "jiānchí", "v.", "qat'iy davom etmoq", "настаивать, продолжать", "истодагарӣ кардан"),
            _word(5, "放弃", "fàngqì", "v.", "voz kechmoq", "отказываться, бросать", "даст кашидан"),
            _word(6, "主意", "zhǔyi", "n.", "fikr, qaror", "идея, решение", "фикр, қарор"),
            _word(7, "网球", "wǎngqiú", "n.", "tennis", "теннис", "теннис"),
            _word(8, "国际", "guójì", "adj.", "xalqaro", "международный", "байналмилалӣ"),
            _word(9, "轻松", "qīngsōng", "adj.", "oson, yengil", "лёгкий, расслабленный", "осон, сабук"),
            _word(10, "赢", "yíng", "v.", "yutmoq", "выигрывать", "бурдан"),
            _word(11, "随便", "suíbiàn", "adj.", "xohlagancha, beparvo", "как угодно, случайно", "ихтиёрӣ, бепарво"),
            _word(12, "汗", "hàn", "n.", "ter", "пот", "арақ"),
            _word(13, "通过", "tōngguò", "prep./v.", "orqali; o'tmoq", "через; проходить", "тавассути; гузаштан"),
            _word(14, "篇", "piān", "m.", "maqola/matn uchun hisob so'zi", "счётное слово для статей", "ҳисобвожа барои мақола"),
            _word(15, "作家", "zuòjiā", "n.", "yozuvchi", "писатель", "нависанда"),
            _word(16, "当时", "dāngshí", "n.", "o'sha payt", "тогда, в то время", "он вақт"),
            _word(17, "可是", "kěshì", "conj.", "lekin, ammo", "но, однако", "аммо, вале"),
            _word(18, "正确", "zhèngquè", "adj.", "to'g'ri", "правильный", "дуруст"),
            _word(19, "理想", "lǐxiǎng", "n.", "orzu, ideal", "идеал, мечта", "орзу, идеал"),
            _word(20, "勇敢", "yǒnggǎn", "adj.", "jasur", "смелый", "ҷасур"),
            _word(21, "结果", "jiéguǒ", "n.", "natija", "результат", "натиҷа"),
            _word(22, "失败", "shībài", "v./n.", "muvaffaqiyatsizlik, yutqazmoq", "провал, потерпеть неудачу", "нокомӣ, мағлуб шудан"),
            _word(23, "过程", "guòchéng", "n.", "jarayon", "процесс", "раванд"),
            _word(24, "至少", "zhìshǎo", "adv.", "kamida", "по крайней мере", "ҳадди ақал"),
            _word(25, "总结", "zǒngjié", "v.", "xulosa qilmoq", "подводить итог", "хулоса кардан"),
            _word(26, "取", "qǔ", "v.", "olmoq, qo'lga kiritmoq", "получать, брать", "гирифтан"),
            _word(27, "经历", "jīnglì", "v./n.", "boshdan kechirmoq; tajriba", "переживать; опыт", "аз сар гузаронидан; таҷриба"),
            _word(28, "许多", "xǔduō", "num.", "ko'p", "много", "бисёр"),
            _word(29, "区别", "qūbié", "n.", "farq", "разница", "фарқ"),
            _word(30, "暂时", "zànshí", "n.", "vaqtincha", "временно", "муваққатан"),
            _word(31, "面对", "miànduì", "v.", "yuzma-yuz kelmoq", "сталкиваться, смотреть в лицо", "рӯ ба рӯ шудан"),
        ],
        "grammar": [
            _grammar(1, "难道", "nahotki", "неужели", "магар", "Ritorik savolda gapiruvchi hayrat yoki qarshi fikrni kuchli bildiradi.", "В риторическом вопросе выражает удивление или несогласие.", "Дар саволи риторикӣ ҳайрат ё норозигиро қавӣ нишон медиҳад.", "怎么又买了这么多饼干和巧克力？难道你不减肥了？", "Zěnme yòu mǎi le zhème duō bǐnggān hé qiǎokèlì? Nándào nǐ bù jiǎnféi le?", "Yana shuncha pechenye va shokolad oldingmi? Nahotki ozishni tashlading?", "Ты опять купила столько печенья и шоколада? Неужели больше не худеешь?", "Боз ин қадар печенье ва шоколад харидӣ? Магар дигар вазн кам намекунӣ?"),
            _grammar(2, "通过", "orqali", "через, благодаря", "тавассути", "Biror natijaga qaysi yo'l yoki vosita bilan erishilishini bildiradi.", "Показывает способ или средство, с помощью которого достигается результат.", "Роҳ ё воситаеро нишон медиҳад, ки тавассути он натиҷа ба даст меояд.", "任何成功都要通过努力才能得到。", "Rènhé chénggōng dōu yào tōngguò nǔlì cái néng dédào.", "Har qanday muvaffaqiyatga faqat mehnat orqali erishiladi.", "Любой успех можно получить только через усилия.", "Ҳар гуна муваффақият танҳо тавассути кӯшиш ба даст меояд."),
            _grammar(3, "可是", "lekin, ammo", "но, однако", "аммо, вале", "Oldingi fikrga qarama-qarshi yoki kutilmagan holatni bog'laydi.", "Соединяет с предыдущей мыслью противоположную или неожиданную ситуацию.", "Ҳолати муқобил ё ногаҳониро ба фикри пешина мепайвандад.", "当时她的父母和亲戚都不支持她，可是她坚持自己的选择。", "Dāngshí tā de fùmǔ hé qīnqi dōu bù zhīchí tā, kěshì tā jiānchí zìjǐ de xuǎnzé.", "O'sha payt ota-onasi va qarindoshlari uni qo'llamagan, lekin u o'z tanlovida turib olgan.", "Тогда родители и родственники её не поддерживали, но она настояла на своём выборе.", "Он вақт падару модар ва хешовандонаш ӯро дастгирӣ накарданд, вале ӯ интихоби худро нигоҳ дошт."),
            _grammar(4, "结果", "natija", "результат", "натиҷа", "Ishning yakuniy natijasini bildiradi; darsda natijadan qo'rqmay jarayonga e'tibor berish aytiladi.", "Обозначает итог; в уроке подчёркивается внимание к процессу, а не страх перед результатом.", "Натиҷаи ниҳоиро нишон медиҳад; дар дарс таъкид мешавад, ки аз натиҷа натарсида ба раванд диққат диҳем.", "如果你想做什么事情，那就勇敢地去做，不要担心结果。", "Rúguǒ nǐ xiǎng zuò shénme shìqing, nà jiù yǒnggǎn de qù zuò, búyào dānxīn jiéguǒ.", "Biror ish qilmoqchi bo'lsang, jasorat bilan qil, natijadan xavotir olma.", "Если хочешь что-то сделать, смело делай и не переживай о результате.", "Агар мехоҳӣ коре кунӣ, ҷасурона кун ва аз натиҷа хавотир нашав."),
            _grammar(5, "上", "sondan oldin: undan ortiq", "перед числом: свыше", "пеш аз шумора: беш аз", "上 + son taxminan 'undan ortiq' ma'nosini beradi.", "上 + число означает приблизительно 'свыше, больше чем'.", "上 + шумора маънои тахминан 'беш аз'-ро медиҳад.", "爱迪生就是在找了上千种材料后才找到了能点亮电灯的材料。", "Àidíshēng jiùshì zài zhǎo le shàng qiān zhǒng cáiliào hòu cái zhǎodào le néng diǎnliàng diàndēng de cáiliào.", "Edison mingdan ortiq materialni qidirgandan keyingina elektr chiroqni yoqa oladigan materialni topgan.", "Эдисон нашёл материал для электрической лампы только после поиска более тысячи материалов.", "Эдисон танҳо баъди ҷустуҷӯи беш аз ҳазор навъ мавод маводи чароғро ёфт."),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "王静 va 孙月 vazn tashlashni davom ettirish haqida gaplashadi",
                "scene_ru": "王静 и 孙月 говорят о продолжении похудения",
                "scene_tj": "王静 ва 孙月 дар бораи идома додани кам кардани вазн гуфтугӯ мекунанд",
                "word_nos": [1, 2, 3, 4, 5, 6],
                "grammar_nos": [1],
                "dialogue": [
                    _line("王静", "怎么又买了这么多饼干和巧克力？难道你不减肥了？", "Zěnme yòu mǎi le zhème duō bǐnggān hé qiǎokèlì? Nándào nǐ bù jiǎnféi le?", "Yana nega shuncha pechenye va shokolad olding? Nahotki ozishni tashlading?", "Почему опять купила столько печенья и шоколада? Неужели больше не худеешь?", "Чаро боз ин қадар печенье ва шоколад харидӣ? Магар дигар вазн кам намекунӣ?"),
                    _line("孙月", "减了一个月都没瘦下来，我实在没有信心了。", "Jiǎn le yí ge yuè dōu méi shòu xiàlai, wǒ shízài méiyǒu xìnxīn le.", "Bir oy ozishga harakat qildim ham ozmadim, rostdan ishonchim qolmadi.", "Целый месяц худела и не похудела, я правда потеряла уверенность.", "Як моҳ вазн кам кардам ҳам лоғар нашудам, ростӣ бовариям намонд."),
                    _line("王静", "如果你想减肥，就得少吃东西，而且要多运动。", "Rúguǒ nǐ xiǎng jiǎnféi, jiù děi shǎo chī dōngxi, érqiě yào duō yùndòng.", "Ozmoqchi bo'lsang, kamroq yeyishing va ko'proq sport qilishing kerak.", "Если хочешь похудеть, нужно меньше есть и больше заниматься спортом.", "Агар вазн кам кардан хоҳӣ, бояд камтар бихӯрӣ ва бештар варзиш кунӣ."),
                    _line("孙月", "我就是这么做的，但这一个月下来，我只轻了一公斤。", "Wǒ jiù shì zhème zuò de, dàn zhè yí ge yuè xiàlai, wǒ zhǐ qīng le yì gōngjīn.", "Men aynan shunday qildim, lekin bir oyda atigi bir kilo yengillashdim.", "Я именно так и делала, но за месяц стала легче только на один килограмм.", "Ман ҳамин тавр кардам, вале дар як моҳ танҳо як кило кам шудам."),
                    _line("王静", "一个月太短了。要想减肥成功，只能坚持，才会慢慢有效果。", "Yí ge yuè tài duǎn le. Yào xiǎng jiǎnféi chénggōng, zhǐ néng jiānchí, cái huì mànmàn yǒu xiàoguǒ.", "Bir oy juda qisqa. Ozishda muvaffaqiyatga erishmoqchi bo'lsang, faqat davom etsang asta-sekin natija bo'ladi.", "Один месяц слишком короткий. Чтобы успешно похудеть, нужно только продолжать, тогда постепенно будет эффект.", "Як моҳ хеле кӯтоҳ аст. Барои муваффақ шудан дар кам кардани вазн бояд давом диҳӣ, баъд оҳиста натиҷа мешавад."),
                    _line("孙月", "我本来已经打算放弃了，但是你刚才的话让我改变了主意。这些饼干和巧克力送给你了。", "Wǒ běnlái yǐjīng dǎsuàn fàngqì le, dànshì nǐ gāngcái de huà ràng wǒ gǎibiàn le zhǔyi. Zhèxiē bǐnggān hé qiǎokèlì sòng gěi nǐ le.", "Aslida voz kechmoqchi edim, lekin hozirgi gaplaring fikrimni o'zgartirdi. Bu pechenye va shokoladlarni senga berdim.", "Я уже собиралась сдаться, но твои слова изменили моё решение. Это печенье и шоколад дарю тебе.", "Ман аллакай мехостам даст кашам, вале суханҳои ту фикрамро дигар кард. Ин печенье ва шоколадҳоро ба ту медиҳам."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "李进 va 张远 tennisdagi muvaffaqiyat haqida gaplashadi",
                "scene_ru": "李进 и 张远 говорят об успехе в теннисе",
                "scene_tj": "李进 ва 张远 дар бораи муваффақият дар теннис гуфтугӯ мекунанд",
                "word_nos": [7, 8, 9, 10, 11, 12, 13],
                "grammar_nos": [2],
                "dialogue": [
                    _line("李进", "你网球打得真好，还得过那么多国际大奖！每次看你比赛，感觉你轻轻松松就赢了。", "Nǐ wǎngqiú dǎ de zhēn hǎo, hái déguo nàme duō guójì dàjiǎng! Měi cì kàn nǐ bǐsài, gǎnjué nǐ qīngqīngsōngsōng jiù yíng le.", "Tennisni juda yaxshi o'ynaysan, shuncha xalqaro mukofot ham olgansan! Har safar o'yiningni ko'rsam, osonlik bilan yutgandek tuyuladi.", "Ты отлично играешь в теннис и получил столько международных наград! Каждый раз кажется, что ты выигрываешь совсем легко.", "Ту теннисро бисёр хуб бозӣ мекунӣ, ин қадар ҷоизаи байналмилалӣ гирифтаӣ! Ҳар бор бозиятро мебинам, гӯё хеле осон мебарӣ."),
                    _line("张远", "哪里啊！那是你没有看到我辛苦练习的一面，没有人随随便便就能成功的。", "Nǎli a! Nà shì nǐ méiyǒu kàndào wǒ xīnkǔ liànxí de yí miàn, méiyǒu rén suí suí biàn biàn jiù néng chénggōng de.", "Qayoqda! Sen mening mashaqqatli mashq qilgan tomonimni ko'rmagansan, hech kim shunchaki muvaffaqiyatga erishmaydi.", "Да что ты! Ты просто не видел, как тяжело я тренировался; никто не добивается успеха просто так.", "Не, ту тарафи сахт машқ кардани маро надидаӣ; ҳеҷ кас тасодуфан муваффақ намешавад."),
                    _line("李进", "我从小也对网球感兴趣，但是到现在还是打得不怎么样。", "Wǒ cóng xiǎo yě duì wǎngqiú gǎn xìngqù, dànshì dào xiànzài háishi dǎ de bù zěnmeyàng.", "Men ham bolaligimdan tennisga qiziqqanman, lekin hozirgacha uncha yaxshi o'ynolmayman.", "Я тоже с детства интересуюсь теннисом, но до сих пор играю не очень.", "Ман ҳам аз хурдӣ ба теннис шавқ доштам, вале то ҳол хуб бозӣ намекунам."),
                    _line("张远", "你知道吗？不管春夏秋冬，我练球从来没有休息过一天。", "Nǐ zhīdào ma? Bùguǎn chūn xià qiū dōng, wǒ liàn qiú cónglái méiyǒu xiūxi guo yì tiān.", "Bilasanmi? Bahor, yoz, kuz, qish bo'lishidan qat'i nazar, mashqdan bir kun ham dam olmaganman.", "Знаешь? Весной, летом, осенью и зимой я ни дня не отдыхал от тренировок.", "Медонӣ? Баҳор, тобистон, тирамоҳ ё зимистон бошад ҳам, ман аз машқ як рӯз ҳам истироҳат накардаам."),
                    _line("李进", "真是不容易啊！看来我只看到了你成功时获得的鲜花，却没注意到你成功前流下的汗水。", "Zhēn shì bù róngyì a! Kànlai wǒ zhǐ kàndào le nǐ chénggōng shí huòdé de xiānhuā, què méi zhùyì dào nǐ chénggōng qián liú xià de hànshuǐ.", "Rostdan oson emas ekan! Men faqat muvaffaqiyat paytidagi gullarni ko'ribman, undan oldingi teringga e'tibor bermabman.", "Это действительно нелегко! Похоже, я видел только цветы твоего успеха, но не замечал пот, пролитый до него.", "Ростӣ осон нест! Маълум шуд ман танҳо гулҳои вақти муваффақиятатро дидаам, арақи пеш аз онро надидаам."),
                    _line("张远", "任何成功都要通过努力才能得到。只要你坚持练习，我相信你也会越打越好的。", "Rènhé chénggōng dōu yào tōngguò nǔlì cái néng dédào. Zhǐyào nǐ jiānchí liànxí, wǒ xiāngxìn nǐ yě huì yuè dǎ yuè hǎo de.", "Har qanday muvaffaqiyatga mehnat orqali erishiladi. Mashqni davom ettirsang, sen ham tobora yaxshiroq o'ynaysan deb ishonaman.", "Любой успех приходит через усилия. Если будешь продолжать тренироваться, уверен, ты тоже будешь играть всё лучше.", "Ҳар гуна муваффақият тавассути кӯшиш ба даст меояд. Агар машқро давом диҳӣ, бовар дорам ту ҳам ҳарчи беҳтар бозӣ мекунӣ."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "小林 va 小李 yozuvchi bo'lgan 王红 haqida gaplashadi",
                "scene_ru": "小林 и 小李 говорят о 王红, ставшей писателем",
                "scene_tj": "小林 ва 小李 дар бораи 王红, ки нависанда шуд, гуфтугӯ мекунанд",
                "word_nos": [14, 15, 16, 17, 18, 19],
                "grammar_nos": [3],
                "dialogue": [
                    _line("小林", "你还记得王红吗？我在报纸上看到一篇关于她的新闻，她现在已经是一个有名的作家了。", "Nǐ hái jìde Wáng Hóng ma? Wǒ zài bàozhǐ shang kàndào yì piān guānyú tā de xīnwén, tā xiànzài yǐjīng shì yí ge yǒumíng de zuòjiā le.", "王红 esingdami? Gazetada u haqda bir xabar ko'rdim, u hozir allaqachon mashhur yozuvchi bo'libdi.", "Помнишь 王红? Я видел в газете статью о ней, она уже стала известной писательницей.", "王红-ро дар ёд дорӣ? Дар рӯзнома дар бораи ӯ як хабар дидам, ӯ ҳоло аллакай нависандаи маъруф шудааст."),
                    _line("小李", "听说她毕业后放弃了律师的工作，开始专门写小说，没想到她竟然成功了。", "Tīngshuō tā bìyè hòu fàngqì le lǜshī de gōngzuò, kāishǐ zhuānmén xiě xiǎoshuō, méi xiǎngdào tā jìngrán chénggōng le.", "Eshitishimcha, bitirgandan keyin advokat ishidan voz kechib, maxsus roman yozishni boshlagan, kutilmaganda muvaffaqiyatga erishibdi.", "Слышал, после выпуска она отказалась от работы юриста и начала писать романы, неожиданно добилась успеха.", "Шунидам баъди хатм аз кори ҳуқуқшиносӣ даст кашида, махсус роман навиштанро сар кардааст, ғайричашмдошт муваффақ шудааст."),
                    _line("小林", "当时她的父母和亲戚都不支持她，可是她坚持自己的选择，现在终于向所有人证明了她的选择是正确的。", "Dāngshí tā de fùmǔ hé qīnqi dōu bù zhīchí tā, kěshì tā jiānchí zìjǐ de xuǎnzé, xiànzài zhōngyú xiàng suǒyǒu rén zhèngmíng le tā de xuǎnzé shì zhèngquè de.", "O'sha payt ota-onasi va qarindoshlari uni qo'llamagan, lekin u o'z tanlovida turib oldi, endi nihoyat tanlovi to'g'ri ekanini hammaga isbotladi.", "Тогда родители и родственники её не поддерживали, но она настояла на своём выборе и теперь доказала всем, что её выбор был правильным.", "Он вақт падару модар ва хешовандонаш ӯро дастгирӣ намекарданд, вале ӯ интихоби худро нигоҳ дошт ва ҳоло ба ҳама дуруст будани онро исбот кард."),
                    _line("小李", "看来为了自己的理想，放弃一些东西也是值得的。", "Kànlai wèile zìjǐ de lǐxiǎng, fàngqì yìxiē dōngxi yě shì zhíde de.", "Demak, orzu uchun ba'zi narsalardan voz kechish ham arziydi.", "Похоже, ради своей мечты стоит отказаться от некоторых вещей.", "Маълум мешавад, барои орзуи худ аз баъзе чизҳо даст кашидан ҳам арзанда аст."),
                    _line("小林", "一个人只有两只手，不可能得到所有想要的东西，所以有时候放弃是一种聪明的选择。", "Yí ge rén zhǐ yǒu liǎng zhī shǒu, bù kěnéng dédào suǒyǒu xiǎng yào de dōngxi, suǒyǐ yǒu shíhou fàngqì shì yì zhǒng cōngming de xuǎnzé.", "Odamning ikki qo'li bor, xohlagan hamma narsani ololmaydi, shuning uchun ba'zan voz kechish aqlli tanlovdir.", "У человека только две руки, невозможно получить всё желаемое, поэтому иногда отказаться - умный выбор.", "Одам танҳо ду даст дорад, ҳамаи чизҳои хостаашро гирифта наметавонад, бинобар ин баъзан даст кашидан интихоби оқилона аст."),
                    _line("小李", "是啊，只有学会放弃，才能把自己的能力用到最该做的事情上，最后获得成功。", "Shì a, zhǐyǒu xuéhuì fàngqì, cái néng bǎ zìjǐ de nénglì yòng dào zuì gāi zuò de shìqing shang, zuìhòu huòdé chénggōng.", "Ha, faqat voz kechishni o'rgansang, qobiliyatingni eng kerakli ishga sarflab, oxirida muvaffaqiyatga erishasan.", "Да, только научившись отказываться, можно направить способности на самое нужное дело и в итоге добиться успеха.", "Ҳа, танҳо даст кашиданро ёд гирифта, қобилиятро ба кори аз ҳама лозим равона мекунӣ ва дар охир муваффақ мешавӣ."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Natijadan qo'rqmasdan jarayonga e'tibor berish haqida matn",
                "scene_ru": "Текст о внимании к процессу, а не страхе перед результатом",
                "scene_tj": "Матн дар бораи диққат ба раванд, на тарс аз натиҷа",
                "word_nos": [20, 21, 22, 23, 24, 25],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "如果你想做什么事情，那就勇敢地去做，不要担心结果，不要考虑会不会失败。要是太看重结果，失败就会给人们带来很多烦恼。我们应该把注意力放在做事情的过程上，这样你会在做的过程中发现解决问题的快乐，这是其他任何东西都给不了的。即使最后失败了也没有关系，因为至少你已经努力过，而且我们还可以从失败中总结出有用的经验，有了这些积累，成功自然离我们越来越近。", "Rúguǒ nǐ xiǎng zuò shénme shìqing, nà jiù yǒnggǎn de qù zuò, búyào dānxīn jiéguǒ.", "Agar biror ish qilmoqchi bo'lsang, jasorat bilan qil, natijadan yoki muvaffaqiyatsizlikdan qo'rqma. Natijani juda muhim deb bilsang, muvaffaqiyatsizlik ko'p tashvish olib keladi. E'tiborni ish jarayoniga qaratish kerak, shunda muammo yechish quvonchini topasan. Oxirida muvaffaqiyatsiz bo'lsang ham muammo emas, chunki kamida harakat qilgansan va muvaffaqiyatsizlikdan foydali tajriba chiqarish mumkin. Shunday yig'ilgan tajriba bilan muvaffaqiyat tabiiy ravishda yaqinlashadi.", "Если хочешь что-то сделать, смело делай и не переживай о результате или возможной неудаче. Если слишком ценить результат, неудача принесёт много тревог. Нужно переносить внимание на процесс, тогда в процессе найдёшь радость решения проблем. Даже если в конце будет неудача, это не страшно: по крайней мере ты старался, а из неудачи можно сделать полезные выводы. С таким накоплением опыта успех естественно становится ближе.", "Агар мехоҳӣ коре кунӣ, ҷасурона кун ва аз натиҷа ё нокомӣ хавотир нашав. Агар натиҷаро зиёд муҳим донӣ, нокомӣ ташвиши зиёд меорад. Бояд диққатро ба раванди кор гузошт, он вақт дар раванди ҳалли масъала хурсандӣ меёбӣ. Ҳатто дар охир ноком шавӣ ҳам, муҳим нест: ҳадди ақал кӯшиш кардаӣ ва аз нокомӣ таҷрибаи фоиданок мегирӣ. Бо чунин ҷамъшавии таҷриба муваффақият наздиктар мешавад."),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Qiyinchilikdan keyin muvaffaqiyat kelishi haqida matn",
                "scene_ru": "Текст о том, что успех приходит после трудностей",
                "scene_tj": "Матн дар бораи он ки муваффақият баъди мушкилӣ меояд",
                "word_nos": [26, 27, 28, 29, 30, 31],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "每一个人都希望成功，可是很多时候，在成功之前会遇到很多困难。有些人遇到困难就放弃，而有些人遇到困难却想办法解决它。对困难的态度不同，结果也是不一样的。爱迪生就是在找了上千种材料后才找到了能点亮电灯的材料。取得成功的人往往都经历过许多失败，他们和普通人的区别就是他们都坚持了下来。所以就算只有1%的希望，我们也要做出100%的努力。困难只是暂时的，“阳光总在风雨后”，只有我们勇敢地面对困难，才能有希望取得成功。", "Měi yí ge rén dōu xīwàng chénggōng, kěshì hěn duō shíhou, zài chénggōng zhīqián huì yùdào hěn duō kùnnan.", "Har bir odam muvaffaqiyatni xohlaydi, lekin ko'p payt muvaffaqiyatdan oldin ko'p qiyinchilik uchraydi. Ba'zilar qiyinchilik ko'rsa voz kechadi, boshqalar esa uni yechish yo'lini topadi. Qiyinchilikka munosabat turlicha bo'lsa, natija ham turlicha bo'ladi. Edison mingdan ortiq materialni sinagandan keyingina elektr chiroqni yoqadigan material topgan. Muvaffaqiyatga erishganlar ko'pincha ko'p muvaffaqiyatsizliklarni boshdan kechirgan; ularning oddiy odamlardan farqi - davom etganida. Shuning uchun 1% umid bo'lsa ham, 100% harakat qilish kerak. Qiyinchilik vaqtinchalik, 'quyosh doim yomg'irdan keyin chiqadi'; faqat jasorat bilan yuzlashsak, muvaffaqiyat umidi bo'ladi.", "Каждый хочет успеха, но часто до успеха встречается много трудностей. Одни при трудностях сдаются, другие ищут способ решить их. Отношение к трудностям разное, и результат тоже разный. Эдисон нашёл материал для электрической лампы после поиска более тысячи материалов. Успешные люди часто пережили много неудач; их отличие от обычных людей в том, что они продолжили. Поэтому даже при 1% надежды нужно приложить 100% усилий. Трудности временны: солнце всегда после дождя. Только смело встречая трудности, можно надеяться на успех.", "Ҳар кас муваффақият мехоҳад, вале бисёр вақт пеш аз муваффақият мушкилиҳои зиёд меоянд. Баъзеҳо мушкилро дида даст мекашанд, баъзеҳо роҳи ҳалли онро меҷӯянд. Муносибат ба мушкилӣ гуногун аст, натиҷа ҳам гуногун мешавад. Эдисон баъди ҷустуҷӯи беш аз ҳазор мавод маводи чароғро ёфт. Одамони муваффақ аксаран нокомиҳои зиёдро аз сар гузарондаанд; фарқашон аз одамони оддӣ он аст, ки онҳо давом доданд. Барои ҳамин ҳатто 1% умед бошад ҳам, бояд 100% кӯшиш кунем. Мушкилӣ муваққатист: офтоб баъди борон меояд. Танҳо бо ҷасорат рӯ ба рӯ шавем, умеди муваффақият дорем."),
                ],
            },
        ],
    },
    10: {
        "title": "幸福的标准",
        "goal": {
            "uz": "baxt, oila, ish tanlovi va hayot sharoiti haqida gapirish; 不过, 确实, 在...看来, 由于 va 比如 grammatikalarini ishlatish",
            "ru": "говорить о счастье, семье, выборе работы и условиях жизни; использовать 不过, 确实, 在...看来, 由于 и 比如",
            "tj": "дар бораи хушбахтӣ, оила, интихоби кор ва шароити зиндагӣ гуфтугӯ кардан; истифодаи 不过, 确实, 在...看来, 由于 ва 比如",
        },
        "intro_text": {
            "uz": "Bu darsda baxtning turli ko'rinishlari, oiladagi mas'uliyat, kasb tanlash va pulning hayotdagi o'rni haqida gapirishni o'rganasiz. Har qismda yangi so'zlar, pinyin, tarjima va matnga mos grammatika bor.",
            "ru": "В этом уроке вы научитесь говорить о разных видах счастья, семейной ответственности, выборе профессии и роли денег в жизни. В каждой части есть слова, pinyin, перевод и грамматика по тексту.",
            "tj": "Дар ин дарс дар бораи шаклҳои гуногуни хушбахтӣ, масъулияти оила, интихоби касб ва нақши пул дар зиндагӣ гуфтугӯ карданро меомӯзед. Дар ҳар қисм калимаҳо, pinyin, тарҷума ва грамматикаи мувофиқи матн ҳаст.",
        },
        "vocabulary": [
            _word(1, "礼拜天", "lǐbàitiān", "n.", "yakshanba", "воскресенье", "якшанбе"),
            _word(2, "空儿", "kòngr", "n.", "bo'sh vaqt", "свободное время", "вақти холӣ"),
            _word(3, "母亲", "mǔqīn", "n.", "ona", "мать", "модар"),
            _word(4, "不过", "búguò", "conj.", "lekin, biroq", "однако, но", "аммо, вале"),
            _word(5, "永远", "yǒngyuǎn", "adv.", "abadiy, doim", "навсегда, всегда", "ҳамеша, абадӣ"),
            _word(6, "方向", "fāngxiàng", "n.", "yo'nalish", "направление", "самт"),
            _word(7, "优秀", "yōuxiù", "adj.", "a'lo, zo'r", "выдающийся, отличный", "аъло, беҳтарин"),
            _word(8, "硕士", "shuòshì", "n.", "magistr", "магистр", "магистр"),
            _word(9, "翻译", "fānyì", "n./v.", "tarjimon; tarjima qilmoq", "переводчик; переводить", "тарҷумон; тарҷума кардан"),
            _word(10, "确实", "quèshí", "adv.", "haqiqatan", "действительно", "воқеан"),
            _word(11, "兴奋", "xīngfèn", "adj.", "hayajonli, xursand", "возбуждённый, радостный", "ҳаяҷонзада, хурсанд"),
            _word(12, "拉", "lā", "v.", "tortmoq, olib bormoq", "тянуть, вести", "кашидан, бурдан"),
            _word(13, "建议", "jiànyì", "n./v.", "maslahat, taklif", "совет, предложение", "маслиҳат, пешниҳод"),
            _word(14, "职业", "zhíyè", "n.", "kasb", "профессия", "касб"),
            _word(15, "关键", "guānjiàn", "n./adj.", "kalit, asosiy", "ключевой", "асосӣ, калидӣ"),
            _word(16, "将来", "jiānglái", "n.", "kelajak", "будущее", "оянда"),
            _word(17, "发展", "fāzhǎn", "v./n.", "rivojlanmoq; rivojlanish", "развиваться; развитие", "рушд кардан; рушд"),
            _word(18, "躺", "tǎng", "v.", "yotmoq", "лежать", "дароз кашидан"),
            _word(19, "困", "kùn", "adj.", "uyqusi kelgan", "сонный", "хоболуд"),
            _word(20, "经济", "jīngjì", "n.", "iqtisod", "экономика", "иқтисод"),
            _word(21, "条件", "tiáojiàn", "n.", "sharoit", "условие", "шароит"),
            _word(22, "富", "fù", "adj.", "boy", "богатый", "бой"),
            _word(23, "穷", "qióng", "adj.", "kambag'al", "бедный", "камбағал"),
            _word(24, "等", "děng", "part.", "va boshqalar", "и так далее", "ва ғайра"),
            _word(25, "由于", "yóuyú", "prep./conj.", "sababli, tufayli", "из-за, вследствие", "бинобар, аз сабаби"),
            _word(26, "比如", "bǐrú", "v.", "masalan", "например", "масалан"),
            _word(27, "橡皮", "xiàngpí", "n.", "o'chirg'ich", "ластик", "хатпоккунак"),
            _word(28, "糖", "táng", "n.", "shakar, konfet", "сахар, конфета", "шакар, қанд"),
            _word(29, "低", "dī", "adj.", "past", "низкий", "паст"),
            _word(30, "答案", "dá'àn", "n.", "javob", "ответ", "ҷавоб"),
        ],
        "grammar": [
            _grammar(1, "不过", "lekin, biroq", "однако, но", "аммо, вале", "Oldingi fikrdan keyin yumshoq burilish yoki qarama-qarshi fikr beradi.", "После предыдущей мысли вводит мягкое противопоставление.", "Баъди фикри пешина муқобили мулоим меорад.", "不过现在我很幸福。", "Búguò xiànzài wǒ hěn xìngfú.", "Lekin hozir men juda baxtliman.", "Однако сейчас я очень счастлива.", "Аммо ҳоло ман хеле хушбахтам."),
            _grammar(2, "确实", "haqiqatan", "действительно", "воқеан", "Fikrni tasdiqlab, gapiruvchi rostdan shunday deb bilishini bildiradi.", "Подтверждает мысль и показывает, что говорящий действительно так считает.", "Фикрро тасдиқ карда нишон медиҳад, ки гӯянда воқеан ҳамин тавр мешуморад.", "我女儿确实不错。", "Wǒ nǚ'ér quèshí búcuò.", "Qizim haqiqatan ham yaxshi.", "Моя дочь действительно хорошая.", "Духтарам воқеан хуб аст."),
            _grammar(3, "在……看来", "... nazarida", "с точки зрения...", "аз назари...", "Kimningdir shaxsiy qarashi yoki bahosini kiritadi.", "Вводит личную точку зрения или оценку.", "Нуқтаи назар ё баҳодиҳии шахсиро меорад.", "在我看来，赚钱多少不是最重要的，兴趣才是关键。", "Zài wǒ kànlai, zhuànqián duōshǎo bú shì zuì zhòngyào de, xìngqù cái shì guānjiàn.", "Mening nazarimda, qancha pul topish eng muhimi emas, qiziqish asosiy.", "На мой взгляд, сколько зарабатывать - не самое важное, ключевое - интерес.", "Аз назари ман, чӣ қадар пул ёфтан муҳимтарин нест, шавқ асосӣ аст."),
            _grammar(4, "由于", "sababli", "из-за, вследствие", "аз сабаби", "Sababni rasmiyroq uslubda beradi; keyin natija keladi.", "В более официальном стиле указывает причину, после которой идёт результат.", "Сабабро бо услуби расмитар медиҳад; баъд натиҷа меояд.", "如果由于缺钱而不能及时去看医生，你的健康都很难得到保证。", "Rúguǒ yóuyú quē qián ér bù néng jíshí qù kàn yīshēng, nǐ de jiànkāng dōu hěn nán dédào bǎozhèng.", "Agar pul yetishmasligi sababli vaqtida shifokorga borolmasang, sog'lig'ingni kafolatlash qiyin.", "Если из-за нехватки денег нельзя вовремя обратиться к врачу, здоровье трудно гарантировать.", "Агар аз сабаби камии пул сари вақт ба духтур рафта натавонӣ, кафолати саломатӣ душвор мешавад."),
            _grammar(5, "比如", "masalan", "например", "масалан", "Oldingi umumiy fikrga aniq misol beradi.", "Даёт конкретный пример к предыдущей общей мысли.", "Ба фикри умумии пешина мисоли мушаххас медиҳад.", "比如一块橡皮、一块糖，得到了就很幸福。", "Bǐrú yí kuài xiàngpí, yí kuài táng, dédào le jiù hěn xìngfú.", "Masalan, bir dona o'chirg'ich yoki konfetni olsang, juda baxtli bo'lasan.", "Например, получишь ластик или конфету - и уже счастлив.", "Масалан, як хатпоккунак ё як қанд гирӣ, хеле хушбахт мешавӣ."),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "孙月 va 王静 oila mas'uliyati va baxt haqida gaplashadi",
                "scene_ru": "孙月 и 王静 говорят о семейной ответственности и счастье",
                "scene_tj": "孙月 ва 王静 дар бораи масъулияти оила ва хушбахтӣ гуфтугӯ мекунанд",
                "word_nos": [1, 2, 3, 4, 5, 6],
                "grammar_nos": [1],
                "dialogue": [
                    _line("孙月", "礼拜天有空儿吗？陪我去逛街怎么样？我想去给丈夫买个生日礼物。", "Lǐbàitiān yǒu kòngr ma? Péi wǒ qù guàngjiē zěnmeyàng? Wǒ xiǎng qù gěi zhàngfu mǎi ge shēngrì lǐwù.", "Yakshanba bo'sh vaqting bormi? Men bilan ko'cha aylangani borsang-chi? Erimga tug'ilgan kun sovg'asi olmoqchiman.", "В воскресенье есть время? Как насчёт сходить со мной по магазинам? Хочу купить мужу подарок на день рождения.", "Якшанбе вақти холӣ дорӣ? Бо ман ба дӯконгардӣ равӣ чӣ? Ба шавҳарам туҳфаи зодрӯз харидан мехоҳам."),
                    _line("王静", "我可能去不了，最近事情多。", "Wǒ kěnéng qù bùliǎo, zuìjìn shìqing duō.", "Bora olmasam kerak, oxirgi payt ishlarim ko'p.", "Наверное, не смогу, в последнее время много дел.", "Эҳтимол рафта наметавонам, вақтҳои охир корам зиёд."),
                    _line("孙月", "你最近是不是工作特别忙？", "Nǐ zuìjìn shì bú shì gōngzuò tèbié máng?", "Oxirgi payt ishing juda bandmi?", "Ты в последнее время особенно занята на работе?", "Вақтҳои охир корат хеле серкор аст?"),
                    _line("王静", "我现在上有老，下有小。除了工作以外，家里还有母亲和儿子需要照顾。", "Wǒ xiànzài shàng yǒu lǎo, xià yǒu xiǎo. Chúle gōngzuò yǐwài, jiā li hái yǒu mǔqīn hé érzi xūyào zhàogu.", "Hozir tepamda kattalar, pastimda bolalar bor. Ishdan tashqari uyda onam va o'g'limga qarashim kerak.", "У меня сейчас старшие и младшие в семье. Кроме работы, дома нужно заботиться о матери и сыне.", "Ҳоло дар хона калонсол ва кӯдак дорам. Ғайр аз кор, дар хона модарам ва писарамро нигоҳубин кардан лозим."),
                    _line("孙月", "真是辛苦啊！你最近脸色不太好，是不是哪儿不舒服？要注意身体啊。", "Zhēn shì xīnkǔ a! Nǐ zuìjìn liǎnsè bú tài hǎo, shì bú shì nǎr bù shūfu? Yào zhùyì shēntǐ a.", "Rostdan mashaqqatli ekan! Oxirgi payt yuzing yaxshi emas, qayeringdir noqulaymi? Sog'lig'ingga e'tibor ber.", "Это правда тяжело! В последнее время у тебя неважный цвет лица, тебе нездоровится? Береги здоровье.", "Ростӣ заҳматнок аст! Вақтҳои охир ранги рӯят хуб нест, ҷое нороҳат аст? Ба саломатият диққат кун."),
                    _line("王静", "没事儿，谢谢！不过现在我很幸福，因为在母亲面前我可以做一个永远长不大的孩子；在孩子面前我又是个能照顾他的母亲，这让我有了努力的方向。", "Méishìr, xièxie! Búguò xiànzài wǒ hěn xìngfú, yīnwèi zài mǔqīn miànqián wǒ kěyǐ zuò yí ge yǒngyuǎn zhǎng bù dà de háizi; zài háizi miànqián wǒ yòu shì ge néng zhàogu tā de mǔqīn, zhè ràng wǒ yǒu le nǔlì de fāngxiàng.", "Hech narsa emas, rahmat! Lekin hozir men baxtliman: onam oldida abadiy katta bo'lmaydigan bola bo'la olaman; bolam oldida esa unga qaray oladigan onaman. Bu menga harakat yo'nalishini berdi.", "Ничего, спасибо! Но сейчас я счастлива: перед матерью я могу быть ребёнком, который никогда не вырастает; перед ребёнком я мать, которая может о нём заботиться. Это дало мне направление для усилий.", "Ҳеҷ гап нест, раҳмат! Аммо ҳоло ман хушбахтам: назди модарам метавонам кӯдаке бошам, ки ҳамеша калон намешавад; назди фарзандам бошад модаре ҳастам, ки ӯро нигоҳубин мекунад. Ин ба ман самти кӯшиш дод."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "高老师 va 李老师 boshqalarga havas qilish haqida gaplashadi",
                "scene_ru": "高老师 и 李老师 говорят о зависти к чужому счастью",
                "scene_tj": "高老师 ва 李老师 дар бораи ҳавас ба хушбахтии дигарон гуфтугӯ мекунанд",
                "word_nos": [7, 8, 9, 10, 11, 12],
                "grammar_nos": [2],
                "dialogue": [
                    _line("高老师", "你看人家王老师，刚来这儿工作三年就当了教授，还有个好妻子，真让人羡慕！", "Nǐ kàn rénjiā Wáng lǎoshī, gāng lái zhèr gōngzuò sān nián jiù dāng le jiàoshòu, hái yǒu ge hǎo qīzi, zhēn ràng rén xiànmù!", "Qarang, 王 ustoz bu yerga kelib atigi uch yil ishladi-yu professor bo'ldi, yana yaxshi xotini bor, odam havas qiladi!", "Посмотрите на учителя Вана: всего три года работает здесь и уже стал профессором, ещё и хорошая жена, прямо завидно!", "Ба устод Ван нигоҳ кунед: ҳамагӣ се сол ин ҷо кор кард ва профессор шуд, боз зани хуб дорад, одам ҳавас мекунад!"),
                    _line("李老师", "其实，你在别人眼中也是很幸福的，只是你自己没有发现。", "Qíshí, nǐ zài biérén yǎn zhōng yě shì hěn xìngfú de, zhǐshì nǐ zìjǐ méiyǒu fāxiàn.", "Aslida boshqalar nazarida siz ham juda baxtlisiz, faqat o'zingiz payqamadingiz.", "На самом деле в глазах других вы тоже очень счастливы, просто сами этого не заметили.", "Дар асл дар назари дигарон шумо ҳам хеле хушбахтед, танҳо худатон пай набурдаед."),
                    _line("高老师", "是吗？我哪能跟王老师比啊？", "Shì ma? Wǒ nǎ néng gēn Wáng lǎoshī bǐ a?", "Rostdanmi? Men qayoqda 王 ustoz bilan tenglashaman?", "Правда? Разве я могу сравниться с учителем Ваном?", "Ростӣ? Ман чӣ хел бо устод Ван муқоиса шавам?"),
                    _line("李老师", "你有一个漂亮的女儿，还那么优秀，硕士毕业后就当了翻译。", "Nǐ yǒu yí ge piàoliang de nǚ'ér, hái nàme yōuxiù, shuòshì bìyè hòu jiù dāng le fānyì.", "Sizning chiroyli qizingiz bor, yana shunchalik zo'r, magistraturani bitirib tarjimon bo'ldi.", "У вас красивая дочь, к тому же такая способная: после магистратуры стала переводчиком.", "Шумо духтари зебо доред, боз ин қадар аъло: баъди магистратура тарҷумон шуд."),
                    _line("高老师", "我女儿确实不错，记得她刚拿到第一个月工资时，就兴奋地拉着我和她爸俩去商场，给我们买礼物，那时我和她爸心里别提多美了！", "Wǒ nǚ'ér quèshí búcuò, jìde tā gāng nádào dì yī ge yuè gōngzī shí, jiù xīngfèn de lā zhe wǒ hé tā bà liǎ qù shāngchǎng, gěi wǒmen mǎi lǐwù, nà shí wǒ hé tā bà xīnli biétí duō měi le!", "Qizim haqiqatan ham yaxshi. Esimda, birinchi oyligini olganda hayajon bilan meni va otasini savdo markaziga olib borib, bizga sovg'a olgan edi; o'shanda men va otasi ich-ichimizdan juda xursand bo'lganmiz!", "Моя дочь действительно хорошая. Помню, когда она получила первую зарплату, радостно потащила меня и её отца в торговый центр купить нам подарки; тогда мы с её отцом были невероятно счастливы!", "Духтарам воқеан хуб аст. Дар ёдам, вақте маоши аввалашро гирифт, бо ҳаяҷон ману падарашро ба маркази савдо бурда, ба мо туҳфа харид; он вақт ману падараш хеле хушҳол будем!"),
                    _line("李老师", "所以说每个人有每个人的生活，不用羡慕别人。你羡慕别人的时候，他们可能也正在羡慕你呢。", "Suǒyǐ shuō měi ge rén yǒu měi ge rén de shēnghuó, búyòng xiànmù biérén. Nǐ xiànmù biérén de shíhou, tāmen kěnéng yě zhèngzài xiànmù nǐ ne.", "Shuning uchun har kimning o'z hayoti bor, boshqalarga havas qilish shart emas. Siz boshqalarga havas qilganingizda, ular ham balki sizga havas qilayotgandir.", "Поэтому у каждого своя жизнь, не нужно завидовать другим. Когда вы завидуете другим, они, возможно, тоже завидуют вам.", "Бинобар ин ҳар кас зиндагии худро дорад, ба дигарон ҳавас кардан шарт нест. Вақте шумо ба дигарон ҳавас мекунед, шояд онҳо ҳам ба шумо ҳавас доранд."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "小雨 va 小夏 kasb tanlashda pul va qiziqish haqida gaplashadi",
                "scene_ru": "小雨 и 小夏 говорят о деньгах и интересе при выборе профессии",
                "scene_tj": "小雨 ва 小夏 дар бораи пул ва шавқ ҳангоми интихоби касб гуфтугӯ мекунанд",
                "word_nos": [13, 14, 15, 16, 17, 18, 19],
                "grammar_nos": [3],
                "dialogue": [
                    _line("小雨", "时间过得真快，马上就要毕业了。毕业后你打算做什么？", "Shíjiān guò de zhēn kuài, mǎshàng jiù yào bìyè le. Bìyè hòu nǐ dǎsuàn zuò shénme?", "Vaqt juda tez o'tyapti, tez orada bitiramiz. Bitirgandan keyin nima qilmoqchisan?", "Время летит быстро, скоро выпуск. Что собираешься делать после выпуска?", "Вақт бисёр тез мегузарад, ба зудӣ хатм мекунем. Баъди хатм чӣ кор кардан мехоҳӣ?"),
                    _line("小夏", "我还没想好呢，正想听听你的建议。你觉得在选择职业时，收入重要吗？", "Wǒ hái méi xiǎng hǎo ne, zhèng xiǎng tīng ting nǐ de jiànyì. Nǐ juéde zài xuǎnzé zhíyè shí, shōurù zhòngyào ma?", "Hali aniq o'ylamadim, aynan sening maslahatingni eshitmoqchiman. Kasb tanlashda daromad muhim deb o'ylaysanmi?", "Я ещё не решил, как раз хочу услышать твой совет. Как думаешь, при выборе профессии доход важен?", "Ҳанӯз хуб фикр накардаам, мехоҳам маслиҳати туро шунавам. Ба фикрат, ҳангоми интихоби касб даромад муҳим аст?"),
                    _line("小雨", "在我看来，赚钱多少不是最重要的，兴趣才是关键。只有做自己喜欢的事，才会觉得幸福，将来也会有更好的发展。", "Zài wǒ kànlai, zhuànqián duōshǎo bú shì zuì zhòngyào de, xìngqù cái shì guānjiàn. Zhǐyǒu zuò zìjǐ xǐhuan de shì, cái huì juéde xìngfú, jiānglái yě huì yǒu gèng hǎo de fāzhǎn.", "Mening nazarimda qancha pul topish eng muhimi emas, qiziqish asosiy. Faqat o'zing yoqtirgan ishni qilsang baxtni his qilasan va kelajakda yaxshiroq rivojlanasan.", "На мой взгляд, сколько зарабатывать - не самое важное, ключевой фактор - интерес. Только занимаясь любимым делом, чувствуешь счастье и в будущем развиваешься лучше.", "Аз назари ман, чӣ қадар пул ёфтан муҳимтарин нест, шавқ калид аст. Танҳо кори дӯстдоштаатро кунӣ, хушбахтӣ ҳис мекунӣ ва дар оянда рушди беҳтар мешавад."),
                    _line("小夏", "我也这么想。如果我带着热情去做自己喜欢的工作，就不会感到累。不过，现在什么东西都那么贵，生活压力太大了，没有钱也不会过得幸福啊！", "Wǒ yě zhème xiǎng. Rúguǒ wǒ dài zhe rèqíng qù zuò zìjǐ xǐhuan de gōngzuò, jiù bú huì gǎndào lèi. Búguò, xiànzài shénme dōngxi dōu nàme guì, shēnghuó yālì tài dà le, méiyǒu qián yě bú huì guò de xìngfú a!", "Men ham shunday o'ylayman. Agar yoqtirgan ishimni ishtiyoq bilan qilsam, charchoq sezmayman. Lekin hozir hamma narsa qimmat, hayot bosimi juda katta, pulsiz ham baxtli yashab bo'lmaydi-ku!", "Я тоже так думаю. Если с энтузиазмом заниматься любимой работой, не будешь чувствовать усталость. Но сейчас всё дорого, давление жизни огромное, без денег тоже счастливым не будешь!", "Ман ҳам ҳамин тавр фикр мекунам. Агар кори дӯстдоштаамро бо шавқ кунам, хаста намешавам. Аммо ҳоло ҳама чиз қимат аст, фишори зиндагӣ зиёд, бе пул ҳам хушбахт зиндагӣ карда намешавад!"),
                    _line("小雨", "幸福其实很简单，它不是只要有钱就能买到的。我觉得工作结束回家后，洗个热水澡，然后躺在床上看看书、听听音乐，困了睡睡觉，就很幸福。", "Xìngfú qíshí hěn jiǎndān, tā bú shì zhǐyào yǒu qián jiù néng mǎi dào de. Wǒ juéde gōngzuò jiéshù huí jiā hòu, xǐ ge rèshuǐzǎo, ránhòu tǎng zài chuáng shang kàn kan shū, tīng ting yīnyuè, kùn le shuì shuì jiào, jiù hěn xìngfú.", "Baxt aslida juda oddiy, uni faqat pul bo'lsa sotib olib bo'lmaydi. Menimcha, ishdan uyga qaytib, issiq dush qabul qilish, keyin karavotda yotib kitob o'qish, musiqa tinglash, uyqu kelganda uxlash - juda baxt.", "Счастье на самом деле простое, его нельзя купить только потому, что есть деньги. По-моему, после работы вернуться домой, принять горячий душ, лечь на кровать, почитать, послушать музыку и поспать, когда сонно, - это уже счастье.", "Хушбахтӣ дар асл хеле содда аст, онро танҳо бо пул харида намешавад. Ба назарам, баъди кор ба хона баргашта, души гарм гирифтан, баъд дар кат хобида китоб хондану мусиқӣ шунидан, хоболуд шавӣ хобидан - ҳамин хушбахтист."),
                    _line("小夏", "你说的也对。如果能找到一份自己既感兴趣，收入又不错的工作，那就最好了。", "Nǐ shuō de yě duì. Rúguǒ néng zhǎodào yí fèn zìjǐ jì gǎn xìngqù, shōurù yòu búcuò de gōngzuò, nà jiù zuì hǎo le.", "Gaping ham to'g'ri. Agar o'zim qiziqadigan va daromadi ham yaxshi ish topsam, eng yaxshi bo'lardi.", "Ты тоже прав. Если найти работу, которая и интересна, и с хорошим доходом, это было бы лучше всего.", "Гапат ҳам дуруст. Агар коре ёбам, ки ҳам ба он шавқ дорам, ҳам даромадаш хуб аст, беҳтарин мешавад."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Pul va baxt o'rtasidagi munosabat haqida matn",
                "scene_ru": "Текст о связи денег и счастья",
                "scene_tj": "Матн дар бораи робитаи пул ва хушбахтӣ",
                "word_nos": [20, 21, 22, 23, 24, 25],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "有的人希望穿得再好一些，房子再大一些，认为经济条件越好人就越幸福。其实有很多富人过得并不愉快，而有些穷人却过得很快乐。有钱不一定幸福，因为很多东西都是不能用钱买到的，例如时间、感情、生活经历等。但是，从另外一个方面看，如果没钱，也很难过得幸福。当你生病了，如果由于缺钱而不能及时去看医生，你的健康都很难得到保证，就更别说幸福了。", "Yǒu de rén xīwàng chuān de zài hǎo yìxiē, fángzi zài dà yìxiē, rènwéi jīngjì tiáojiàn yuè hǎo rén jiù yuè xìngfú.", "Ba'zi odamlar yaxshiroq kiyinishni, kattaroq uyda yashashni xohlaydi va iqtisodiy sharoit qancha yaxshi bo'lsa, odam shuncha baxtli deb o'ylaydi. Aslida ko'p boylar xursand yashamaydi, ba'zi kambag'allar esa juda quvonchli yashaydi. Pul bo'lishi shartli ravishda baxt emas, chunki vaqt, his-tuyg'u, hayot tajribasi kabi ko'p narsani pulga sotib olib bo'lmaydi. Lekin boshqa tomondan qaralsa, pul bo'lmasa ham baxtli yashash qiyin. Kasal bo'lganda, pul yetishmagani sababli vaqtida shifokorga bora olmasang, sog'lig'ing ham kafolatlanmaydi, baxtni-ku aytmasa ham bo'ladi.", "Некоторые хотят одеваться лучше, иметь дом побольше и считают: чем лучше экономические условия, тем счастливее человек. На самом деле многие богатые живут нерадостно, а некоторые бедные очень счастливы. Деньги не обязательно дают счастье, потому что время, чувства, жизненный опыт и многое другое нельзя купить. Но с другой стороны, без денег тоже трудно быть счастливым. Если заболел и из-за нехватки денег не можешь вовремя обратиться к врачу, даже здоровье трудно гарантировать, не говоря уже о счастье.", "Баъзеҳо мехоҳанд беҳтар пӯшанд, хонаи калонтар дошта бошанд ва фикр мекунанд ҳар қадар шароити иқтисодӣ хуб бошад, одам ҳамон қадар хушбахт аст. Дар асл бисёр бойҳо хуш зиндагӣ намекунанд, баъзе камбағалон бошанд хеле хурсанданд. Пул ҳатман хушбахтӣ нест, зеро вақт, эҳсос, таҷрибаи зиндагӣ ва бисёр чизҳоро бо пул харида намешавад. Аммо аз тарафи дигар, бе пул ҳам хушбахт зиндагӣ кардан душвор аст. Вақте бемор мешавӣ, агар аз сабаби камии пул сари вақт ба духтур рафта натавонӣ, саломатият ҳам кафолат надорад, хушбахтӣ бошад ҷойи худ."),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Baxtning yagona standarti yo'qligi haqida matn",
                "scene_ru": "Текст о том, что у счастья нет единого стандарта",
                "scene_tj": "Матн дар бораи он ки хушбахтӣ стандарти ягона надорад",
                "word_nos": [26, 27, 28, 29, 30],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "什么是幸福？有的人认为，工资高、能赚钱就是幸福；有的人认为，心情放松、身体健康才是幸福；也有人认为，能帮助别人就是一种幸福。还有人说，小时候幸福是一件东西，比如一块橡皮、一块糖，得到了就很幸福；长大后幸福是一种态度，生活的态度决定了我们幸福感的高低。那怎样才算是真正的幸福？其实，幸福并没有一个标准答案，每个人对幸福都有不同的理解。不管你认为幸福是什么，只要你用心去找，就一定能发现它。", "Shénme shì xìngfú? Yǒu de rén rènwéi, gōngzī gāo, néng zhuànqián jiù shì xìngfú.", "Baxt nima? Ba'zilar yuqori maosh va pul topish baxt deb o'ylaydi; ba'zilar kayfiyat xotirjam, tana sog'lom bo'lishi baxt deb biladi; yana boshqalarga yordam bera olish ham baxt deydiganlar bor. Yana kimdir aytadi: bolalikda baxt bir narsa, masalan bir dona o'chirg'ich yoki konfet - olsang baxtli bo'lasan; ulg'ayganda esa baxt bir munosabat, hayotga munosabat baxt hissi baland-pastligini belgilaydi. Unda haqiqiy baxt nima? Aslida baxtning standart javobi yo'q, har kim uni turlicha tushunadi. Baxtni nima deb bilishingdan qat'i nazar, chin dildan izlasang, albatta topasan.", "Что такое счастье? Одни считают, что высокая зарплата и возможность зарабатывать - это счастье; другие считают, что спокойное настроение и здоровое тело - счастье; третьи думают, что помогать другим - тоже счастье. Ещё говорят: в детстве счастье - это вещь, например ластик или конфета, получил - и счастлив; во взрослом возрасте счастье - это отношение, отношение к жизни определяет уровень ощущения счастья. Что же считать настоящим счастьем? На самом деле у счастья нет стандартного ответа, каждый понимает его по-своему. Что бы ты ни считал счастьем, если будешь искать сердцем, обязательно найдёшь.", "Хушбахтӣ чист? Баъзеҳо фикр мекунанд маоши баланд ва пул ёфтан хушбахтист; баъзеҳо кайфияти ором ва бадани солимро хушбахтӣ медонанд; баъзеҳо ёрӣ ба дигаронро ҳам хушбахтӣ мешуморанд. Боз мегӯянд: дар кӯдакӣ хушбахтӣ як чиз аст, масалан як хатпоккунак ё як қанд, онро гирӣ хушбахт мешавӣ; калон шавӣ, хушбахтӣ як муносибат аст, муносибат ба зиндагӣ дараҷаи ҳисси хушбахтиро муайян мекунад. Пас хушбахтии ҳақиқӣ чист? Дар асл хушбахтӣ ҷавоби стандартӣ надорад, ҳар кас онро гуногун мефаҳмад. Новобаста аз он ки хушбахтиро чӣ медонӣ, агар бо дил ҷустуҷӯ кунӣ, ҳатман меёбӣ."),
                ],
            },
        ],
    },
}
