def _word(no, zh, pinyin, pos, uz, ru, tj):
    return {"no": no, "zh": zh, "pinyin": pinyin, "pos": pos, "uz": uz, "ru": ru, "tj": tj}


def _line(speaker, zh, pinyin, uz, ru, tj):
    return {"speaker": speaker, "zh": zh, "pinyin": pinyin, "uz": uz, "ru": ru, "tj": tj}


def _grammar(no, title_zh, title_uz, title_ru, title_tj, rule_uz, rule_ru, rule_tj, example_zh, example_pinyin, example_uz, example_ru, example_tj):
    return {
        "no": no,
        "title_zh": title_zh,
        "title_uz": title_uz,
        "title_ru": title_ru,
        "title_tj": title_tj,
        "rule_uz": rule_uz,
        "rule_ru": rule_ru,
        "rule_tj": rule_tj,
        "formula": title_zh,
        "examples": [
            {
                "zh": example_zh,
                "pinyin": example_pinyin,
                "uz": example_uz,
                "ru": example_ru,
                "tj": example_tj,
            }
        ],
    }


HSK4_UPPER_PDF_MATERIALS_4_6 = {
    4: {
        "title": "不要太着急赚钱",
        "goal": {
            "uz": "ish, daromad va tajriba haqida gapirish; 以为, 原来, 并, 按照 va 甚至 grammatikalarini ishlatish",
            "ru": "говорить о работе, доходе и опыте; использовать 以为, 原来, 并, 按照 и 甚至",
            "tj": "дар бораи кор, даромад ва таҷриба гуфтугӯ кардан; истифодаи 以为, 原来, 并, 按照 ва 甚至",
        },
        "intro_text": {
            "uz": "Bu darsda ishni tez-tez almashtirish, reja bo'yicha ishlash, tajriba yig'ish va mas'uliyat haqida gapirishni o'rganasiz. Har qismda o'sha matndagi yangi so'zlar, pinyin, tarjima va kerakli grammatika beriladi.",
            "ru": "В этом уроке вы научитесь говорить о смене работы, работе по плану, накоплении опыта и ответственности. В каждой части есть слова, pinyin, перевод и нужная грамматика именно к своему тексту.",
            "tj": "Дар ин дарс дар бораи иваз кардани кор, кор аз рӯи нақша, ҷамъ кардани таҷриба ва масъулият гуфтугӯ карданро меомӯзед. Дар ҳар қисм калимаҳо, pinyin, тарҷума ва грамматикаи лозими ҳамон матн дода мешавад.",
        },
        "vocabulary": [
            _word(1, "提", "tí", "v.", "tilga olmoq, aytmoq", "упоминать, говорить", "зикр кардан, гуфтан"),
            _word(2, "以为", "yǐwéi", "v.", "deb o'ylamoq, yanglish hisoblamoq", "думать, ошибочно полагать", "фикр кардан, ғалат пиндоштан"),
            _word(3, "份", "fèn", "m.", "ish kabi narsalar uchun hisob so'zi", "счётное слово для работы и др.", "ҳисобвожа барои кор ва ғайра"),
            _word(4, "完全", "wánquán", "adv.", "butunlay, to'liq", "полностью, совершенно", "пурра, комилан"),
            _word(5, "赚", "zhuàn", "v.", "pul topmoq", "зарабатывать", "пул даромад кардан"),
            _word(6, "调查", "diàochá", "v.", "tekshirmoq, tadqiq qilmoq", "исследовать, проводить опрос", "таҳқиқ кардан, пурсиш гузаронидан"),
            _word(7, "原来", "yuánlái", "adj.", "asl, oldingi", "первоначальный, прежний", "аввала, пешина"),
            _word(8, "计划", "jìhuà", "n./v.", "reja; rejalamoq", "план; планировать", "нақша; нақша кардан"),
            _word(9, "提前", "tíqián", "v.", "oldindan, muddatidan avval bajarmoq", "сделать заранее, раньше срока", "пешакӣ, пеш аз муҳлат кардан"),
            _word(10, "保证", "bǎozhèng", "v.", "kafolat bermoq", "гарантировать", "кафолат додан"),
            _word(11, "提醒", "tíxǐng", "v.", "eslatmoq", "напоминать", "ёдрас кардан"),
            _word(12, "乱", "luàn", "adj.", "tartibsiz, chalkash", "беспорядочный, спутанный", "бетартиб, ошуфта"),
            _word(13, "生意", "shēngyi", "n.", "biznes, savdo", "бизнес, торговля", "тиҷорат, савдо"),
            _word(14, "谈", "tán", "v.", "gaplashmoq, muhokama qilmoq", "разговаривать, обсуждать", "гуфтугӯ кардан, муҳокима кардан"),
            _word(15, "并", "bìng", "adv.", "inkor oldida kuchaytiradi: umuman", "усиливает отрицание: вовсе", "инкорро таъкид мекунад: умуман"),
            _word(16, "积累", "jīlěi", "v.", "to'plamoq, yig'moq", "накапливать", "ҷамъ кардан"),
            _word(17, "经验", "jīngyàn", "n.", "tajriba", "опыт", "таҷриба"),
            _word(18, "一切", "yíqiè", "pron.", "hammasi, barcha narsa", "всё, всякий", "ҳама чиз"),
            _word(19, "按照", "ànzhào", "prep.", "bo'yicha, muvofiq", "согласно, по", "мувофиқи, тибқи"),
            _word(20, "成功", "chénggōng", "adj.", "muvaffaqiyatli", "успешный", "муваффақ"),
            _word(21, "顺利", "shùnlì", "adj.", "ravon, muammosiz", "гладкий, успешный", "равон, бе мушкил"),
            _word(22, "感谢", "gǎnxiè", "v.", "minnatdor bo'lmoq, rahmat aytmoq", "благодарить", "ташаккур гуфтан"),
            _word(23, "消息", "xiāoxi", "n.", "xabar, yangilik", "новость, сообщение", "хабар"),
            _word(24, "按时", "ànshí", "adv.", "o'z vaqtida", "вовремя, по расписанию", "дар вақташ"),
            _word(25, "奖金", "jiǎngjīn", "n.", "mukofot puli, bonus", "премия, бонус", "мукофотпулӣ, бонус"),
            _word(26, "工资", "gōngzī", "n.", "maosh", "зарплата", "маош"),
            _word(27, "方法", "fāngfǎ", "n.", "usul, yo'l", "метод, способ", "усул, роҳ"),
            _word(28, "知识", "zhīshi", "n.", "bilim", "знания", "дониш"),
            _word(29, "不得不", "bùdébù", "", "majbur bo'lmoq", "быть вынужденным", "маҷбур шудан"),
            _word(30, "甚至", "shènzhì", "conj.", "hatto, hattoki", "даже", "ҳатто"),
            _word(31, "责任", "zérèn", "n.", "mas'uliyat, javobgarlik", "ответственность", "масъулият"),
        ],
        "grammar": [
            _grammar(
                1,
                "以为",
                "deb o'ylamoq, lekin fakt boshqacha",
                "думать, но факт другой",
                "фикр кардан, вале воқеият дигар аст",
                "Gapiruvchi avval bir narsani to'g'ri deb o'ylagan, keyin fakt boshqacha ekani bilinadi.",
                "Говорящий сначала считал что-то верным, но потом выяснилось, что факт другой.",
                "Гӯянда аввал чизеро дуруст пиндошт, баъд маълум шуд, ки воқеият дигар аст.",
                "我以为新工作比以前的好，没想到还没有以前好呢。",
                "Wǒ yǐwéi xīn gōngzuò bǐ yǐqián de hǎo, méi xiǎngdào hái méiyǒu yǐqián hǎo ne.",
                "Men yangi ish oldingisidan yaxshi deb o'ylagandim, kutilmaganda oldingisidan ham yaxshi emas ekan.",
                "Я думал, новая работа лучше прежней, но оказалось, что она даже не лучше прежней.",
                "Ман фикр мекардам кори нав аз пешина беҳтар аст, вале маълум шуд, ки ҳатто аз пешина беҳтар нест.",
            ),
            _grammar(
                2,
                "原来",
                "oldingi, asl",
                "прежний, первоначальный",
                "пешина, аввала",
                "Ot oldida kelib oldingi yoki dastlabki holatni bildiradi; ko'pincha 的 bilan otni aniqlaydi.",
                "Перед существительным показывает прежнее или первоначальное состояние; часто оформляется через 的.",
                "Пеш аз исм ҳолати пешина ё аввалаеро нишон медиҳад; аксаран бо 的 меояд.",
                "按原来的计划应该是两周，但是我们可以提前完成。",
                "Àn yuánlái de jìhuà yīnggāi shì liǎng zhōu, dànshì wǒmen kěyǐ tíqián wánchéng.",
                "Oldingi rejaga ko'ra ikki hafta bo'lishi kerak edi, lekin biz oldinroq tugata olamiz.",
                "По первоначальному плану должно быть две недели, но мы можем завершить раньше.",
                "Мувофиқи нақшаи аввал бояд ду ҳафта мешуд, вале мо метавонем пеш аз муҳлат анҷом диҳем.",
            ),
            _grammar(
                3,
                "并",
                "inkorni kuchaytirish",
                "усиление отрицания",
                "таъкиди инкор",
                "并 odatda 不 yoki 没 oldida kelib, 'aslida unday emas' ma'nosida inkorni kuchaytiradi.",
                "并 обычно стоит перед 不 или 没 и усиливает отрицание: 'вовсе не'.",
                "并 одатан пеш аз 不 ё 没 омада, маънои 'умуман не'-ро таъкид мекунад.",
                "后来才发现其实并不容易。",
                "Hòulái cái fāxiàn qíshí bìng bù róngyì.",
                "Keyin bildimki, aslida bu umuman oson emas ekan.",
                "Потом я понял, что на самом деле это вовсе не легко.",
                "Баъд фаҳмидам, ки дар асл ин умуман осон нест.",
            ),
            _grammar(
                4,
                "按照",
                "bo'yicha, muvofiq",
                "согласно, по",
                "мувофиқи, тибқи",
                "按照 + reja/qoidaga ko'ra harakat bajarilishini bildiradi.",
                "按照 + план/правило показывает, что действие выполняется согласно этому.",
                "按照 + нақша/қоида нишон медиҳад, ки амал тибқи он иҷро мешавад.",
                "我们今年的工作都已经按照计划完成了。",
                "Wǒmen jīnnián de gōngzuò dōu yǐjīng ànzhào jìhuà wánchéng le.",
                "Bu yilgi ishlarimizning hammasi reja bo'yicha yakunlandi.",
                "Наша работа за этот год уже завершена согласно плану.",
                "Корҳои имсолаи мо ҳама мувофиқи нақша анҷом ёфтанд.",
            ),
            _grammar(
                5,
                "甚至",
                "hatto, hattoki",
                "даже",
                "ҳатто",
                "Kuchaytirib sanashda oxirgi, kutilmagan yoki kuchliroq holatni kiritadi.",
                "В перечислении усиливает последний, более неожиданный или сильный пункт.",
                "Дар шумориш ҳолати охирин, ногаҳонтар ё қавитарро таъкид мекунад.",
                "我们不得不去做一些自己不愿意做甚至是非常不喜欢的工作。",
                "Wǒmen bùdébù qù zuò yìxiē zìjǐ bú yuànyì zuò shènzhì shì fēicháng bù xǐhuan de gōngzuò.",
                "Biz o'zimiz xohlamaydigan, hatto juda yoqtirmaydigan ishlarni ham qilishga majbur bo'lamiz.",
                "Нам приходится делать работу, которую мы не хотим делать, даже очень не любим.",
                "Мо маҷбур мешавем корҳоеро кунем, ки намехоҳем, ҳатто хеле дӯст намедорем.",
            ),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "小林 va 小李 ish almashtirish haqida gaplashadi",
                "scene_ru": "小林 и 小李 говорят о смене работы",
                "scene_tj": "小林 ва 小李 дар бораи иваз кардани кор гуфтугӯ мекунанд",
                "word_nos": [1, 2, 3, 4, 5],
                "grammar_nos": [1],
                "dialogue": [
                    _line("小林", "听说你又换工作了？今年已经换了三次工作了吧？", "Tīngshuō nǐ yòu huàn gōngzuò le? Jīnnián yǐjīng huànle sān cì gōngzuò le ba?", "Eshitishimcha yana ish almashtiribsan? Bu yil allaqachon uch marta ish almashtirding-a?", "Слышал, ты снова сменил работу? В этом году уже три раза сменил работу, да?", "Шунидам боз коратро иваз кардӣ? Имсол аллакай се бор кор иваз кардӣ, ҳа?"),
                    _line("小李", "别提了！我以为新工作比以前的好，没想到还没有以前好呢。", "Biétí le! Wǒ yǐwéi xīn gōngzuò bǐ yǐqián de hǎo, méi xiǎngdào hái méiyǒu yǐqián hǎo ne.", "Qo'y, gapirma! Yangi ish oldingisidan yaxshi deb o'ylagandim, kutilmaganda oldingisidan ham yaxshi emas ekan.", "Не напоминай! Я думал, новая работа лучше прежней, но оказалось, что она даже не лучше прежней.", "Нагӯй беҳтар! Ман фикр мекардам кори нав аз пешина беҳтар аст, вале маълум шуд, ки ҳатто беҳтар нест."),
                    _line("小林", "上次那份工作你只做了两个月就离开了，其实，完全适应一个新的工作需要一年时间，所以，经常换工作不一定好。", "Shàng cì nà fèn gōngzuò nǐ zhǐ zuòle liǎng ge yuè jiù líkāi le, qíshí, wánquán shìyìng yí ge xīn de gōngzuò xūyào yì nián shíjiān, suǒyǐ, jīngcháng huàn gōngzuò bù yídìng hǎo.", "O'tgan safargi ishda atigi ikki oy ishlab ketding. Aslida yangi ishga to'liq moslashish uchun bir yil kerak, shuning uchun ishni tez-tez almashtirish shart emas yaxshi bo'lavermaydi.", "На прошлой работе ты проработал всего два месяца и ушёл. На самом деле, чтобы полностью привыкнуть к новой работе, нужен год, поэтому часто менять работу не обязательно хорошо.", "Дар кори пешина ҳамагӣ ду моҳ кор карда рафтӣ. Дар асл, барои пурра одат кардан ба кори нав як сол вақт лозим, бинобар ин зуд-зуд кор иваз кардан ҳатман хуб нест."),
                    _line("小李", "我也明白。但是那份工作的收入太少了！", "Wǒ yě míngbai. Dànshì nà fèn gōngzuò de shōurù tài shǎo le!", "Men ham tushunaman. Lekin u ishning daromadi juda kam edi!", "Я тоже понимаю. Но доход на той работе был слишком маленький!", "Ман ҳам мефаҳмам. Аммо даромади он кор хеле кам буд!"),
                    _line("小林", "你才到新公司，不要太急着赚钱，多学习才是最重要的。", "Nǐ cái dào xīn gōngsī, búyào tài jí zhe zhuàn qián, duō xuéxí cái shì zuì zhòngyào de.", "Sen yangi kompaniyaga endi kelding, pul topishga juda shoshilma, ko'proq o'rganish eng muhimi.", "Ты только пришёл в новую компанию, не спеши зарабатывать деньги, важнее больше учиться.", "Ту нав ба ширкати нав омадӣ, ба пул кор кардан зиёд шитоб накун, бештар омӯхтан муҳимтар аст."),
                    _line("小李", "好。我一定会努力把现在这份工作做好。", "Hǎo. Wǒ yídìng huì nǔlì bǎ xiànzài zhè fèn gōngzuò zuòhǎo.", "Yaxshi. Hozirgi ishni albatta astoydil yaxshi bajaraman.", "Хорошо. Я обязательно постараюсь хорошо выполнять нынешнюю работу.", "Хуб. Ман ҳатман кӯшиш мекунам кори ҳозираамро хуб анҷом диҳам."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "王经理 va 小李 ish rejasi haqida gaplashadi",
                "scene_ru": "王经理 и 小李 говорят о рабочем плане",
                "scene_tj": "王经理 ва 小李 дар бораи нақшаи кор гуфтугӯ мекунанд",
                "word_nos": [6, 7, 8, 9, 10, 11, 12],
                "grammar_nos": [2],
                "dialogue": [
                    _line("王经理", "那份调查还要多长时间才能做完？", "Nà fèn diàochá hái yào duō cháng shíjiān cái néng zuòwán?", "U tadqiqotni tugatish uchun yana qancha vaqt kerak?", "Сколько ещё времени нужно, чтобы закончить то исследование?", "Барои анҷом додани он таҳқиқ боз чӣ қадар вақт лозим?"),
                    _line("小李", "按原来的计划应该是两周，但是我们可以提前完成，周末保证做完。", "Àn yuánlái de jìhuà yīnggāi shì liǎng zhōu, dànshì wǒmen kěyǐ tíqián wánchéng, zhōumò bǎozhèng zuòwán.", "Oldingi rejaga ko'ra ikki hafta bo'lishi kerak edi, lekin biz oldinroq tugata olamiz, dam olish kunigacha albatta tugatamiz.", "По первоначальному плану должно быть две недели, но мы можем завершить раньше, к выходным гарантированно закончим.", "Мувофиқи нақшаи аввал бояд ду ҳафта мешуд, вале мо пештар анҷом дода метавонем, то охири ҳафта ҳатман тамом мекунем."),
                    _line("王经理", "虽然最近工作很忙，但你们也要注意身体呀。", "Suīrán zuìjìn gōngzuò hěn máng, dàn nǐmen yě yào zhùyì shēntǐ a.", "So'nggi payt ish juda band bo'lsa ham, sog'lig'ingizga ham e'tibor beringlar.", "Хотя в последнее время работы много, вам тоже нужно беречь здоровье.", "Ҳарчанд вақтҳои охир кор серкор аст, ба саломатиятон ҳам аҳамият диҳед."),
                    _line("小李", "谢谢您！现在有很多事情等着我做，真不知道该先做哪个好。", "Xièxie nín! Xiànzài yǒu hěn duō shìqing děngzhe wǒ zuò, zhēn bù zhīdào gāi xiān zuò nǎge hǎo.", "Rahmat! Hozir juda ko'p ish meni kutyapti, qaysisini avval qilishni bilmayapman.", "Спасибо! Сейчас много дел ждут меня, я правда не знаю, что лучше сделать сначала.", "Ташаккур! Ҳоло корҳои зиёд маро интизоранд, ростӣ намедонам кадомашро аввал кунам."),
                    _line("王经理", "每天早上我都把当天计划要做的事情写在笔记本上，提醒自己安排好时间。你也可以试试这样做。", "Měi tiān zǎoshang wǒ dōu bǎ dàngtiān jìhuà yào zuò de shìqing xiě zài bǐjìběn shang, tíxǐng zìjǐ ānpái hǎo shíjiān. Nǐ yě kěyǐ shìshi zhèyàng zuò.", "Men har kuni ertalab o'sha kuni qilishni rejalagan ishlarimni daftarimga yozib, vaqtni yaxshi taqsimlashni o'zimga eslataman. Sen ham shunday qilib ko'rishing mumkin.", "Каждое утро я записываю в блокнот дела, которые планирую сделать в этот день, и напоминаю себе правильно распределить время. Ты тоже можешь попробовать так делать.", "Ман ҳар саҳар корҳои ҳамон рӯзро ба дафтар менависам ва ба худ вақтро хуб тақсим карданро ёдрас мекунам. Ту ҳам метавонӣ ҳамин тавр санҷӣ."),
                    _line("小李", "这个办法真不错！这样我就不会手忙脚乱了。", "Zhège bànfǎ zhēn búcuò! Zhèyàng wǒ jiù bú huì shǒumáng-jiǎoluàn le.", "Bu usul juda yaxshi! Shunday qilsam, qo'lim-oyog'im chalkashib ketmaydi.", "Этот способ правда хороший! Тогда я не буду суетиться и путаться.", "Ин усул хеле хуб аст! Ҳамин тавр ман саросема ва парешон намешавам."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "王经理 va 马经理 biznes kelishuvi haqida gaplashadi",
                "scene_ru": "王经理 и 马经理 говорят о деловой сделке",
                "scene_tj": "王经理 ва 马经理 дар бораи муомилаи тиҷорӣ гуфтугӯ мекунанд",
                "word_nos": [13, 14, 15, 16, 17, 18],
                "grammar_nos": [3],
                "dialogue": [
                    _line("王经理", "什么事让你这么高兴啊？", "Shénme shì ràng nǐ zhème gāoxìng a?", "Nima seni bunchalik xursand qildi?", "Что тебя так обрадовало?", "Чӣ чиз туро ин қадар хурсанд кард?"),
                    _line("马经理", "我和上次那个公司的生意终于谈成了。", "Wǒmen hé shàng cì nàge gōngsī de shēngyi zhōngyú tánchéng le.", "O'tgan safargi kompaniya bilan biznesimiz nihoyat kelishildi.", "Бизнес с той прошлой компанией наконец удалось согласовать.", "Тиҷорат бо он ширкати дафъаи гузашта ниҳоят ба созиш расид."),
                    _line("王经理", "太好了！你工作那么努力，公司会越来越好的。", "Tài hǎo le! Nǐ gōngzuò nàme nǔlì, gōngsī huì yuè lái yuè hǎo de.", "Juda yaxshi! Sen shunchalik tirishib ishlaysan, kompaniya tobora yaxshilanadi.", "Отлично! Ты так стараешься на работе, компания будет становиться всё лучше.", "Бисёр хуб! Ту ин қадар меҳнат мекунӣ, ширкат рӯз ба рӯз беҳтар мешавад."),
                    _line("马经理", "我原来以为做生意很简单，后来才发现其实并不容易，现在赚钱越来越难了。", "Wǒ yuánlái yǐwéi zuò shēngyi hěn jiǎndān, hòulái cái fāxiàn qíshí bìng bù róngyì, xiànzài zhuàn qián yuè lái yuè nán le.", "Avval biznes qilish juda oddiy deb o'ylagandim, keyin bildimki aslida umuman oson emas, hozir pul topish tobora qiyinlashyapti.", "Раньше я думал, что заниматься бизнесом очень просто, но потом понял, что это вовсе не легко; сейчас зарабатывать деньги всё труднее.", "Аввал фикр мекардам тиҷорат хеле осон аст, баъд фаҳмидам, ки умуман осон нест; ҳоло пул даромад кардан рӯз ба рӯз душвортар мешавад."),
                    _line("王经理", "慢慢来，万事开头难，重要的是要多积累经验。", "Mànman lái, wànshì kāitóu nán, zhòngyào de shì yào duō jīlěi jīngyàn.", "Shoshilma, har ishning boshi qiyin, muhimi ko'proq tajriba yig'ish.", "Не спеши, в любом деле начало трудно, главное - больше накапливать опыт.", "Оҳиста-оҳиста, оғози ҳар кор душвор аст, муҳимаш таҷрибаи зиёд ҷамъ кардан."),
                    _line("马经理", "我相信经过我们大家的努力，公司的生意会越做越大，一切都会好的。", "Wǒ xiāngxìn jīngguò wǒmen dàjiā de nǔlì, gōngsī de shēngyi huì yuè zuò yuè dà, yíqiè dōu huì hǎo de.", "Hammamizning mehnatimiz bilan kompaniyaning biznesi tobora kattalashishiga va hammasi yaxshi bo'lishiga ishonaman.", "Я верю, что благодаря усилиям всех нас бизнес компании будет расти, и всё будет хорошо.", "Бовар дорам бо кӯшиши ҳамаи мо тиҷорати ширкат калонтар мешавад ва ҳама чиз хуб мешавад."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Reja bo'yicha yakunlangan ish haqida nutq",
                "scene_ru": "Речь о работе, завершённой по плану",
                "scene_tj": "Суханронӣ дар бораи кори тибқи нақша анҷомёфта",
                "word_nos": [19, 20, 21, 22, 23, 24, 25],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "我们今年的工作都已经按照计划完成了。这一段时间，尽管工作很紧张，中间也遇到了很多困难，但是因为有大家的努力，我们成功地解决了问题，顺利地完成了工作，非常感谢大家对我的帮助！另外，马经理让我告诉大家一个好消息，因为大家按时完成了工作，公司决定这个月给每个人多发三千元奖金。感谢大家这三个月的努力工作，希望明年能有更大的成绩！", "Wǒmen jīnnián de gōngzuò dōu yǐjīng ànzhào jìhuà wánchéng le. Zhè yí duàn shíjiān, jǐnguǎn gōngzuò hěn jǐnzhāng, zhōngjiān yě yùdàole hěn duō kùnnan, dànshì yīnwèi yǒu dàjiā de nǔlì, wǒmen chénggōng de jiějuéle wèntí, shùnlì de wánchéngle gōngzuò, fēicháng gǎnxiè dàjiā duì wǒ de bāngzhù! Lìngwài, Mǎ jīnglǐ ràng wǒ gàosu dàjiā yí ge hǎo xiāoxi, yīnwèi dàjiā ànshí wánchéngle gōngzuò, gōngsī juédìng zhège yuè gěi měi rén duō fā sānqiān yuán jiǎngjīn. Gǎnxiè dàjiā zhè sān ge duō yuè de nǔlì gōngzuò, xīwàng míngnián néng yǒu gèng dà de chéngjì!", "Bu yilgi ishlarimizning hammasi reja bo'yicha yakunlandi. Shu davrda ish juda tig'iz bo'ldi, o'rtada ko'p qiyinchiliklar ham uchradi, lekin hammaning mehnati bilan muammolarni muvaffaqiyatli hal qildik va ishni muammosiz yakunladik. Yordamlaringiz uchun juda minnatdorman! Bundan tashqari, Ma menejer hammaga yaxshi xabar aytishimni so'radi: hamma ishni vaqtida tugatgani uchun kompaniya bu oy har bir kishiga qo'shimcha uch ming yuan bonus berishga qaror qildi. Shu uch oycha davomida qilgan mehnatingiz uchun rahmat, kelasi yili yanada katta natija bo'lishini tilayman!", "Наша работа за этот год уже завершена согласно плану. В этот период работа была очень напряжённой, возникло много трудностей, но благодаря усилиям всех мы успешно решили проблемы и гладко завершили работу. Большое спасибо всем за помощь! Кроме того, менеджер Ма попросил передать хорошую новость: поскольку все завершили работу вовремя, компания решила в этом месяце выдать каждому дополнительно по три тысячи юаней премии. Спасибо всем за упорную работу за эти три с лишним месяца, надеюсь, в следующем году будут ещё большие результаты!", "Корҳои имсолаи мо ҳама мувофиқи нақша анҷом ёфтанд. Дар ин муддат кор хеле пуршиддат буд, мушкилоти зиёд ҳам пеш омад, аммо бо кӯшиши ҳама мо мушкилотро муваффақона ҳал карда, корро равон анҷом додем. Барои ёрии ҳамаатон хеле миннатдорам! Ғайр аз ин, менеҷер Ма гуфт ба ҳама як хабари хуб расонам: чун ҳама корро дар вақташ анҷом доданд, ширкат қарор кард ин моҳ ба ҳар кас иловатан се ҳазор юан мукофот диҳад. Барои кори сахти ин се моҳи зиёдатон ташаккур, умедворам соли оянда натиҷаҳои калонтар хоҳем дошт!"),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Yoshlar, ish tajribasi va mas'uliyat haqida matn",
                "scene_ru": "Текст о молодёжи, опыте работы и ответственности",
                "scene_tj": "Матн дар бораи ҷавонон, таҷрибаи кор ва масъулият",
                "word_nos": [26, 27, 28, 29, 30, 31],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "年轻人刚开始工作的时候，不要太急着赚钱，不要眼睛里只有工资和奖金。在工作的前几年，重要的是丰富自己的工作经验，学习与同事交流的方法，积累专业知识，这些比收入重要多了。但是很多时候，我们不得不去做一些自己不愿意做甚至是非常不喜欢的工作。这时，我们最需要的就是对工作的责任心。一个人即使能力再高，经验再丰富，如果对工作没有责任心，也很难把工作做好。", "Niánqīng rén gāng kāishǐ gōngzuò de shíhou, búyào tài jízhe zhuàn qián, búyào yǎnjing lǐ zhǐyǒu gōngzī hé jiǎngjīn. Zài gōngzuò de qián jǐ nián, zhòngyào de shì fēngfù zìjǐ de gōngzuò jīngyàn, xuéxí yǔ tóngshì jiāoliú de fāngfǎ, jīlěi zhuānyè zhīshi, zhèxiē bǐ shōurù zhòngyào duō le. Dànshì hěn duō shíhou, wǒmen bùdébù qù zuò yìxiē zìjǐ bú yuànyì zuò shènzhì shì fēicháng bù xǐhuan de gōngzuò. Zhè shí, wǒmen zuì xūyào de jiù shì duì gōngzuò de zérènxīn. Yí ge rén jíshǐ nénglì zài gāo, jīngyàn zài fēngfù, rúguǒ duì gōngzuò méiyǒu zérènxīn, yě hěn nán bǎ gōngzuò zuòhǎo.", "Yoshlar endi ish boshlagan paytda pul topishga juda shoshilmasligi, ko'zida faqat maosh va bonus bo'lmasligi kerak. Ishning dastlabki yillarida o'z ish tajribasini boyitish, hamkasblar bilan muloqot qilish usullarini o'rganish va professional bilim to'plash muhimroq, bular daromaddan ancha muhim. Lekin ko'p hollarda biz o'zimiz xohlamaydigan, hatto juda yoqtirmaydigan ishlarni qilishga majbur bo'lamiz. Bunday paytda eng kerak narsa - ishga mas'uliyat bilan qarash. Insonning qobiliyati qanchalik yuqori, tajribasi qanchalik boy bo'lmasin, ishga mas'uliyati bo'lmasa, ishni yaxshi bajarishi qiyin.", "Когда молодые люди только начинают работать, не нужно слишком спешить зарабатывать деньги, не нужно видеть только зарплату и премии. В первые годы работы важнее обогащать свой рабочий опыт, учиться общаться с коллегами и накапливать профессиональные знания; это гораздо важнее дохода. Но во многих случаях нам приходится делать работу, которую мы не хотим делать, даже очень не любим. В такой момент больше всего нужна ответственность к работе. Какими бы высокими ни были способности человека и каким бы богатым ни был опыт, если у него нет ответственности к работе, хорошо выполнить работу трудно.", "Вақте ҷавонон нав ба кор оғоз мекунанд, набояд ба пул кор кардан зиёд шитоб кунанд ва дар назарашон танҳо маошу мукофот бошад. Дар солҳои аввали кор муҳимтар он аст, ки таҷрибаи кориро бой кунанд, усули муошират бо ҳамкоронро омӯзанд ва донишҳои касбӣ ҷамъ кунанд; инҳо аз даромад хеле муҳимтаранд. Аммо бисёр вақт мо маҷбур мешавем корҳое кунем, ки намехоҳем, ҳатто хеле дӯст намедорем. Дар ин вақт аз ҳама бештар масъулият ба кор лозим аст. Қобилияти инсон ҳар қадар баланд ва таҷрибааш ҳар қадар бой бошад ҳам, агар ба кор масъулият надошта бошад, корро хуб анҷом додан душвор аст."),
                ],
            },
        ],
    },
    5: {
        "title": "只买对的，不买贵的",
        "goal": {
            "uz": "xarid, narx, sifat va onlayn savdo haqida gapirish; 肯定, 再说, 实际, 对……来说 va 尤其 grammatikalarini ishlatish",
            "ru": "говорить о покупках, цене, качестве и онлайн-покупках; использовать 肯定, 再说, 实际, 对……来说 и 尤其",
            "tj": "дар бораи харид, нарх, сифат ва хариди онлайн гуфтугӯ кардан; истифодаи 肯定, 再说, 实际, 对……来说 ва 尤其",
        },
        "intro_text": {
            "uz": "Bu darsda mebel, maishiy texnika, reklama, kiyim tanlash va onlayn xarid haqida gapirishni o'rganasiz. Har qismda matnga mos yangi so'zlar, pinyin, tarjima va qisqa grammatika bor.",
            "ru": "В этом уроке вы научитесь говорить о мебели, бытовой технике, рекламе, выборе одежды и онлайн-покупках. В каждой части есть слова, pinyin, перевод и короткая грамматика по тексту.",
            "tj": "Дар ин дарс дар бораи мебел, техникаи хона, реклама, интихоби либос ва хариди онлайн гуфтугӯ карданро меомӯзед. Дар ҳар қисм калимаҳо, pinyin, тарҷума ва грамматикаи кӯтоҳи мувофиқи матн ҳаст.",
        },
        "vocabulary": [
            _word(1, "家具", "jiājù", "n.", "mebel", "мебель", "мебел"),
            _word(2, "沙发", "shāfā", "n.", "divan", "диван", "диван"),
            _word(3, "打折", "dǎzhé", "v.", "chegirma qilmoq", "делать скидку", "тахфиф кардан"),
            _word(4, "价格", "jiàgé", "n.", "narx", "цена", "нарх"),
            _word(5, "质量", "zhìliàng", "n.", "sifat", "качество", "сифат"),
            _word(6, "肯定", "kěndìng", "adv.", "albatta, aniq", "обязательно, точно", "ҳатман, аниқ"),
            _word(7, "流行", "liúxíng", "v.", "moda bo'lmoq, ommalashmoq", "быть популярным, модным", "мӯд шудан, паҳн шудан"),
            _word(8, "顺便", "shùnbiàn", "adv.", "yo'l-yo'lakay, bir yo'la", "заодно, попутно", "дар ҳамин асно, якбора"),
            _word(9, "台", "tái", "m.", "texnika uchun hisob so'zi", "счётное слово для техники", "ҳисобвожа барои техника"),
            _word(10, "光", "guāng", "adv.", "faqatgina", "только, лишь", "танҳо"),
            _word(11, "实在", "shízài", "adv.", "haqiqatan, juda", "действительно, очень", "воқеан, хеле"),
            _word(12, "制冷", "zhìlěng", "v.", "sovutmoq", "охлаждать", "хунук кардан"),
            _word(13, "效果", "xiàoguǒ", "n.", "natija, effekt", "эффект, результат", "натиҷа, таъсир"),
            _word(14, "现金", "xiànjīn", "n.", "naqd pul", "наличные", "пули нақд"),
            _word(15, "邀请", "yāoqǐng", "v.", "taklif qilmoq", "приглашать", "даъват кардан"),
            _word(16, "葡萄", "pútao", "n.", "uzum", "виноград", "ангур"),
            _word(17, "艺术", "yìshù", "n.", "san'at", "искусство", "санъат"),
            _word(18, "广告", "guǎnggào", "n./v.", "reklama; reklama qilmoq", "реклама; рекламировать", "реклама; реклама кардан"),
            _word(19, "味道", "wèidào", "n.", "ta'm", "вкус", "мазза"),
            _word(20, "优点", "yōudiǎn", "n.", "afzallik", "достоинство, плюс", "бартарӣ"),
            _word(21, "实际", "shíjì", "adj.", "haqiqiy, amaliy", "реальный, практический", "воқеӣ, амалӣ"),
            _word(22, "考虑", "kǎolǜ", "v.", "o'ylab ko'rmoq, hisobga olmoq", "обдумывать, учитывать", "андеша кардан, ба назар гирифтан"),
            _word(23, "标准", "biāozhǔn", "n.", "standart, mezon", "стандарт, критерий", "меъёр, стандарт"),
            _word(24, "样子", "yàngzi", "n.", "ko'rinish, shakl", "вид, форма", "намуд, шакл"),
            _word(25, "年龄", "niánlíng", "n.", "yosh", "возраст", "синну сол"),
            _word(26, "浪费", "làngfèi", "v.", "isrof qilmoq", "тратить впустую", "исроф кардан"),
            _word(27, "购物", "gòuwù", "v.", "xarid qilmoq", "покупать, делать покупки", "харид кардан"),
            _word(28, "尤其", "yóuqí", "adv.", "ayniqsa", "особенно", "хусусан"),
            _word(29, "受到", "shòudào", "v.", "qabul qilmoq, ta'sirga uchramoq", "получать, подвергаться", "гирифтан, дучор шудан"),
            _word(30, "任何", "rènhé", "pron.", "har qanday", "любой, какой угодно", "ҳар гуна"),
            _word(31, "寄", "jì", "v.", "jo'natmoq", "отправлять", "фиристодан"),
        ],
        "grammar": [
            _grammar(1, "肯定", "albatta, aniq", "точно, обязательно", "ҳатман, аниқ", "Fe'l yoki sifat oldida gapiruvchining ishonchini bildiradi.", "Перед глаголом или прилагательным выражает уверенность говорящего.", "Пеш аз феъл ё сифат боварии гӯяндаро нишон медиҳад.", "质量肯定不“打折”。", "Zhìliàng kěndìng bù “dǎ zhé”.", "Sifat albatta 'chegirmaga tushmaydi'.", "Качество точно не 'со скидкой'.", "Сифат ҳатман 'тахфиф' намешавад."),
            _grammar(2, "再说", "qolaversa, bundan tashqari", "к тому же, кроме того", "ғайр аз ин, гузашта аз ин", "Oldingi fikrga yana bir sabab qo'shadi.", "Добавляет ещё одну причину к предыдущей мысли.", "Ба фикри пешина боз як сабаб илова мекунад.", "再说，这个月家里已经花了五千多了。", "Zàishuō, zhège yuè jiā li yǐjīng huāle wǔqiān duō le.", "Qolaversa, bu oy uyda allaqachon besh mingdan ko'p sarfladik.", "К тому же в этом месяце дома уже потратили больше пяти тысяч.", "Гузашта аз ин, ин моҳ дар хона аллакай беш аз панҷ ҳазор сарф шуд."),
            _grammar(3, "实际", "haqiqiy, amaliy; aslida", "реальный, практический; на деле", "воқеӣ, амалӣ; дар асл", "实际 narsa yoki holatning haqiqiy tomonini bildiradi; 实际上 shakli 'aslida' ma'nosida keladi.", "实际 показывает реальную сторону вещи или ситуации; 实际上 значит 'на самом деле'.", "实际 ҷониби воқеии чиз ё ҳолатро нишон медиҳад; 实际上 маънои 'дар асл'-ро дорад.", "实际上，很多东西并不像广告上说的那么好。", "Shíjì shang, hěn duō dōngxi bìng bú xiàng guǎnggào shang shuō de nàme hǎo.", "Aslida ko'p narsalar reklamada aytilgandek yaxshi emas.", "На самом деле многие вещи вовсе не так хороши, как говорится в рекламе.", "Дар асл бисёр чизҳо мисли реклама гуфтагиашон хуб нестанд."),
            _grammar(4, "对……来说", "... uchun, ... nuqtai nazaridan", "для..., с точки зрения...", "барои..., аз нуқтаи назари...", "Biror shaxs yoki narsa nuqtai nazaridan baho berishni bildiradi.", "Показывает оценку с точки зрения человека или предмета.", "Арзёбиро аз нуқтаи назари шахс ё чиз нишон медиҳад.", "对我来说，衣服的样子流行不流行并不是很重要。", "Duì wǒ lái shuō, yīfu de yàngzi liúxíng bu liúxíng bìng bú shì hěn zhòngyào.", "Men uchun kiyimning ko'rinishi moda yoki moda emasligi juda muhim emas.", "Для меня не так важно, модный ли фасон одежды.", "Барои ман мӯд будан ё набудани намуди либос он қадар муҳим нест."),
            _grammar(5, "尤其", "ayniqsa", "особенно", "хусусан", "Umumiy gapdan keyin eng ajralib turadigan guruh yoki holatni ko'rsatadi.", "После общей мысли выделяет особенно заметную группу или ситуацию.", "Баъди фикри умумӣ гурӯҳ ё ҳолати махсусро нишон медиҳад.", "年轻人尤其喜欢在网上买东西。", "Niánqīng rén yóuqí xǐhuan zài wǎng shang mǎi dōngxi.", "Yoshlar ayniqsa internetda xarid qilishni yoqtiradi.", "Молодые люди особенно любят покупать вещи в интернете.", "Ҷавонон хусусан дар интернет харид карданро дӯст медоранд."),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "王静 mebel do'konida divan sotib oladi",
                "scene_ru": "王静 покупает диван в мебельном магазине",
                "scene_tj": "王静 дар мағозаи мебел диван мехарад",
                "word_nos": [1, 2, 3, 4, 5, 6, 7],
                "grammar_nos": [1],
                "dialogue": [
                    _line("售货员", "小姐，您好！您想买什么家具？需要我为您介绍一下吗？", "Xiǎojiě, nín hǎo! Nín xiǎng mǎi shénme jiājù? Xūyào wǒ wèi nín jièshào yíxià ma?", "Assalomu alaykum, xonim! Qanday mebel olmoqchisiz? Sizga tanishtirib berishim kerakmi?", "Здравствуйте, девушка! Какую мебель вы хотите купить? Нужно, чтобы я вам представил?", "Салом, хонум! Шумо чӣ гуна мебел харидан мехоҳед? Лозим аст ман бароятон шинос кунам?"),
                    _line("王静", "谢谢，我想买沙发。", "Xièxie, wǒ xiǎng mǎi shāfā.", "Rahmat, men divan olmoqchiman.", "Спасибо, я хочу купить диван.", "Ташаккур, ман диван харидан мехоҳам."),
                    _line("售货员", "您看这个沙发怎么样？现在正在打折，比平时便宜了一千块。", "Nín kàn zhège shāfā zěnmeyàng? Xiànzài zhèngzài dǎ zhé, bǐ píngshí piányile yìqiān kuài.", "Mana bu divan qanday? Hozir chegirmada, odatdagidan ming yuan arzonroq.", "Как вам этот диван? Сейчас на него скидка, он на тысячу дешевле обычного.", "Ин диван чӣ хел? Ҳоло тахфиф дорад, аз вақти одӣ ҳазор юан арзонтар."),
                    _line("王静", "价格还可以，就是不知道质量有没有保证。", "Jiàgé hái kěyǐ, jiùshì bù zhīdào zhìliàng yǒu méiyǒu bǎozhèng.", "Narxi yomon emas, faqat sifatiga kafolat bormi-yo'qmi bilmayman.", "Цена ещё приемлемая, только не знаю, есть ли гарантия качества.", "Нархаш бад нест, фақат намедонам сифаташ кафолат дорад ё не."),
                    _line("售货员", "您放心，质量肯定不“打折”，这种沙发是今年最流行的。有很多种颜色可以选择，您可以看一下。", "Nín fàng xīn, zhìliàng kěndìng bù “dǎ zhé”, zhè zhǒng shāfā shì jīnnián zuì liúxíng de. Yǒu hěn duō zhǒng yánsè kěyǐ xuǎnzé, nín kěyǐ kàn yíxià.", "Xotirjam bo'ling, sifat albatta 'chegirmaga tushmaydi', bu turdagi divan bu yil eng ommabop. Tanlash uchun ko'p ranglar bor, ko'rib chiqishingiz mumkin.", "Не беспокойтесь, качество точно не 'со скидкой'; такой диван самый модный в этом году. Есть много цветов на выбор, можете посмотреть.", "Хотирҷамъ бошед, сифат ҳатман 'тахфиф' намешавад, ин намуди диван имсол хеле мӯд аст. Рангҳои зиёд барои интихоб ҳаст, метавонед бинед."),
                    _line("王静", "这个蓝色的看上去不错，就要这个吧。", "Zhège lán sè de kàn shangqu búcuò, jiù yào zhège ba.", "Mana bu ko'ki yaxshi ko'rinyapti, shuni olay.", "Этот синий выглядит неплохо, возьму его.", "Ин ранги кабуд хуб менамояд, ҳаминро мегирам."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "王静 va 李进 savdo markazida xarid qiladi",
                "scene_ru": "王静 и 李进 делают покупки в торговом центре",
                "scene_tj": "王静 ва 李进 дар маркази савдо харид мекунанд",
                "word_nos": [8, 9, 10, 11, 12, 13, 14],
                "grammar_nos": [2],
                "dialogue": [
                    _line("王静", "咱家的冰箱太旧了，商场正好打折，我们顺便也买一台吧。", "Zán jiā de bīngxiāng tài jiù le, shāngchǎng zhènghǎo dǎ zhé, wǒmen shùnbiàn yě mǎi yì tái ba.", "Uyimizdagi muzlatkich juda eski, savdo markazida aynan chegirma bor, yo'l-yo'lakay bittasini ham olaylik.", "Наш холодильник слишком старый, в торговом центре как раз скидка, давай заодно купим один.", "Яхдони хонаамон хеле кӯҳна шудааст, дар маркази савдо айни вақт тахфиф аст, якбора якто ҳам бихарем."),
                    _line("李进", "今天买的东西太多了。再说，这个月家里已经花了五千多了。", "Jīntiān mǎi de dōngxi tài duō le. Zàishuō, zhège yuè jiā li yǐjīng huāle wǔqiān duō le.", "Bugun olgan narsalarimiz juda ko'p bo'ldi. Qolaversa, bu oy uyda allaqachon besh mingdan ko'p sarfladik.", "Сегодня мы купили слишком много вещей. К тому же в этом месяце дома уже потратили больше пяти тысяч.", "Имрӯз чизҳои харидаамон хеле зиёд шуд. Гузашта аз ин, ин моҳ дар хона аллакай беш аз панҷ ҳазор сарф шуд."),
                    _line("王静", "这么多？你不会是记错了吧？", "Zhème duō? Nǐ bú huì shì jìcuò le ba?", "Shuncha ko'pmi? Adashib yozib qo'ymagandirsan?", "Так много? Ты ведь не мог ошибиться в подсчётах?", "Ин қадар зиёд? Шояд хато ҳисоб карда бошӣ?"),
                    _line("李进", "没错。上个星期光买沙发就花了两千多。", "Méi cuò. Shàng ge xīngqī guāng mǎi shāfā jiù huāle liǎngqiān duō.", "Xato emas. O'tgan hafta faqat divanning o'ziga ikki mingdan ko'p ketdi.", "Не ошибся. На прошлой неделе только на диван ушло больше двух тысяч.", "Хато нест. Ҳафтаи гузашта танҳо барои диван беш аз ду ҳазор сарф шуд."),
                    _line("王静", "但是咱家的冰箱实在太旧了，制冷效果也不太好了，还是买个新的吧。", "Dànshì zán jiā de bīngxiāng shízài tài jiù le, zhìlěng xiàoguǒ yě bú tài hǎo le, háishi mǎi ge xīn de ba.", "Lekin uyimizdagi muzlatkich haqiqatan juda eski, sovutish effekti ham uncha yaxshi emas, baribir yangisini olaylik.", "Но наш холодильник действительно слишком старый, охлаждает уже не очень хорошо, всё-таки купим новый.", "Аммо яхдони хонаамон воқеан хеле кӯҳна аст, хунуккуниаш ҳам он қадар хуб нест, беҳтараш нав бихарем."),
                    _line("李进", "那好吧，我带的现金不够，用你的信用卡吧。", "Nà hǎo ba, wǒ dài de xiànjīn bú gòu, yòng nǐ de xìnyòngkǎ ba.", "Unda mayli, mendagi naqd pul yetmaydi, sening kredit kartangdan foydalanaylik.", "Ну хорошо, наличных у меня не хватает, воспользуемся твоей кредитной картой.", "Хуб, пули нақди ман намерасад, аз корти кредитии ту истифода мекунем."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "李进 va 王静 sovg'a tanlaydi",
                "scene_ru": "李进 и 王静 выбирают подарок",
                "scene_tj": "李进 ва 王静 тӯҳфа интихоб мекунанд",
                "word_nos": [15, 16, 17, 18, 19, 20, 21],
                "grammar_nos": [3],
                "dialogue": [
                    _line("李进", "李老师邀请咱们去他家做客，给他带点儿什么礼物好呢？", "Lǐ lǎoshī yāoqǐng zánmen qù tā jiā zuò kè, gěi tā dài diǎnr shénme lǐwù hǎo ne?", "Li ustoz bizni uyiga mehmonga taklif qildi, unga qanday sovg'a olib borsak yaxshi?", "Учитель Ли пригласил нас в гости, какой подарок ему лучше взять?", "Муаллим Ли моро ба хонааш меҳмонӣ даъват кард, ба ӯ чӣ тӯҳфа бурдан хуб?"),
                    _line("王静", "他很喜欢葡萄酒，我们就给他买两瓶葡萄酒吧。", "Tā hěn xǐhuan pútaojiǔ, wǒmen jiù gěi tā mǎi liǎng píng pútaojiǔ ba.", "U uzum vinosini juda yaxshi ko'radi, unga ikki shisha vino olaylik.", "Он очень любит виноградное вино, давай купим ему две бутылки.", "Ӯ шароби ангуриро хеле дӯст медорад, ба ӯ ду шиша шароб мехарем."),
                    _line("李进", "可是这里有这么多种，你知道哪种好吗？", "Kěshì zhèli yǒu zhème duō zhǒng, nǐ zhīdào nǎ zhǒng hǎo ma?", "Lekin bu yerda turi juda ko'p, qaysi biri yaxshi bilasanmi?", "Но здесь столько видов, ты знаешь, какой хороший?", "Аммо инҷо навъҳо бисёранд, медонӣ кадомаш хуб аст?"),
                    _line("王静", "我觉得这种不错，你看它酒瓶做得都这么艺术。而且电视上经常有它的广告，我想味道应该不错。", "Wǒ juéde zhè zhǒng búcuò, nǐ kàn tā jiǔpíng zuò de dōu zhème yìshù. Érqiě diànshì shang jīngcháng yǒu tā de guǎnggào, wǒ xiǎng wèidào yīnggāi búcuò.", "Menimcha bu turi yaxshi, qaragin shishasi ham juda san'atkorona ishlangan. Bundan tashqari televizorda uning reklamasi tez-tez chiqadi, ta'mi ham yaxshi bo'lsa kerak.", "Мне кажется, этот неплохой, посмотри, бутылка сделана так художественно. К тому же по телевизору часто идёт его реклама, думаю, вкус должен быть неплохим.", "Ба фикрам ин навъ хуб аст, бин, шишааш хеле санъаткорона сохта шудааст. Ғайр аз ин, дар телевизор рекламааш зиёд мешавад, фикр мекунам маззааш хуб бошад."),
                    _line("李进", "广告只会介绍优点，却不会说它的缺点。实际上，很多东西并不像广告上说的那么好，所以不能完全相信广告。", "Guǎnggào zhǐ huì jièshào yōudiǎn, què bú huì shuō tā de quēdiǎn. Shíjì shang, hěn duō dōngxi bìng bú xiàng guǎnggào shang shuō de nàme hǎo, suǒyǐ bù néng wánquán xiāngxìn guǎnggào.", "Reklama faqat afzalliklarini tanishtiradi, kamchiliklarini aytmaydi. Aslida ko'p narsalar reklamada aytilgandek yaxshi emas, shuning uchun reklamaga to'liq ishonib bo'lmaydi.", "Реклама рассказывает только о плюсах и не говорит о недостатках. На самом деле многие вещи вовсе не так хороши, как говорится в рекламе, поэтому нельзя полностью верить рекламе.", "Реклама танҳо бартариҳоро мегӯяд, камбудиҳоро намегӯяд. Дар асл бисёр чизҳо мисли реклама гуфтагиашон хуб нестанд, бинобар ин ба реклама пурра бовар кардан мумкин нест."),
                    _line("王静", "你说的也对。", "Nǐ shuō de yě duì.", "Gaping ham to'g'ri.", "Ты тоже прав.", "Гапат ҳам дуруст."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Kiyim tanlash mezoni haqida matn",
                "scene_ru": "Текст о критериях выбора одежды",
                "scene_tj": "Матн дар бораи меъёри интихоби либос",
                "word_nos": [22, 23, 24, 25, 26],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "买衣服只考虑价格当然不好，但是只考虑买好看的也不一定对。我买衣服的标准是“只买对的，不买贵的”。第一，自己穿着舒服；第二，衣服的质量要好，而且又不能太贵。对我来说，衣服的样子流行不流行并不是很重要。很多年龄大的人喜欢在打折的时候买便宜的衣服，但对那些衣服是不是适合自己却考虑得不多。这点是我理解不了的，因为如果不适合自己，即使花钱很少，也是一种浪费。", "Mǎi yīfu zhǐ kǎolǜ jiàgé dāngrán bù hǎo, dànshì zhǐ kǎolǜ mǎi hǎokàn de yě bú yídìng duì. Wǒ mǎi yīfu de biāozhǔn shì “zhǐ mǎi duì de, bù mǎi guì de”. Dì yī, zìjǐ chuānzhe shūfu; dì èr, yīfu de zhìliàng yào hǎo, érqiě yòu bù néng tài guì. Duì wǒ lái shuō, yīfu de yàngzi liúxíng bu liúxíng bìng bú shì hěn zhòngyào. Hěn duō niánlíng dà de rén xǐhuan zài dǎ zhé de shíhou mǎi piányi de yīfu, dàn duì nàxiē yīfu shì bu shì shìhé zìjǐ què kǎolǜ de bù duō. Zhè diǎn shì wǒ lǐjiě bù liǎo de, yīnwèi rúguǒ bú shìhé zìjǐ, jíshǐ huā qián hěn shǎo, yě shì yì zhǒng làngfèi.", "Kiyim olayotganda faqat narxni hisobga olish albatta yaxshi emas, lekin faqat chiroylisini olishni o'ylash ham doim to'g'ri bo'lavermaydi. Men kiyim olishda 'faqat mosini olaman, qimmatini olmayman' degan mezonga amal qilaman. Birinchidan, o'zim kiyganda qulay bo'lishi kerak; ikkinchidan, kiyim sifati yaxshi bo'lishi va juda qimmat bo'lmasligi kerak. Men uchun kiyimning ko'rinishi moda yoki moda emasligi juda muhim emas. Yoshi katta odamlarning ko'pi chegirma paytida arzon kiyim olishni yoqtiradi, lekin u kiyimlar o'ziga mos keladimi-yo'qmi ko'p o'ylamaydi. Buni tushunolmayman, chunki agar o'ziga mos kelmasa, juda oz pul sarflasa ham bu isrofdir.", "Покупая одежду, конечно, плохо учитывать только цену, но думать только о красивом тоже не обязательно правильно. Мой стандарт при покупке одежды: 'покупать только подходящее, а не дорогое'. Во-первых, чтобы самому было удобно носить; во-вторых, качество одежды должно быть хорошим, и она не должна быть слишком дорогой. Для меня не так важно, модный ли фасон одежды. Многие люди старшего возраста любят покупать дешёвую одежду во время скидок, но мало думают о том, подходит ли она им. Этого я не понимаю, потому что если вещь тебе не подходит, даже если денег потрачено мало, это всё равно трата впустую.", "Ҳангоми либос харидан танҳо нархро ба назар гирифтан албатта хуб нест, аммо танҳо зебо буданашро фикр кардан ҳам ҳатман дуруст нест. Меъёри ман барои харидани либос чунин аст: 'фақат мувофиқашро мехарам, қиматашро не'. Якум, ҳангоми пӯшидан бароям роҳат бошад; дуввум, сифати либос хуб бошад ва хеле қимат набошад. Барои ман мӯд будан ё набудани намуди либос он қадар муҳим нест. Бисёр одамони калонсол ҳангоми тахфиф либоси арзон хариданро дӯст медоранд, аммо дар бораи мувофиқ буданаш ба худ кам фикр мекунанд. Инро ман фаҳмида наметавонам, зеро агар ба худ мувофиқ набошад, ҳатто пули кам сарф шавад ҳам, ин як навъи исроф аст."),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Onlayn xaridning ommalashuvi haqida matn",
                "scene_ru": "Текст о популярности онлайн-покупок",
                "scene_tj": "Матн дар бораи машҳур шудани хариди онлайн",
                "word_nos": [27, 28, 29, 30, 31],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "现在网上购物变得越来越流行了，年轻人尤其喜欢在网上买东西。在网上几乎什么都可以买到，你可以上网买书、买衣服、买包，还可以买家具、买手机。网上购物能够受到人们的喜爱，原因主要有两个：首先，网上的东西很多，而且比去商店买便宜，这是吸引人们购买的主要原因。其次，人们可以在任何时间上网购买自己喜欢的东西，卖家可以把你买的东西寄到你办公室或者家里，非常方便。", "Xiànzài wǎng shang gòu wù biàn de yuè lái yuè liúxíng le, niánqīng rén yóuqí xǐhuan zài wǎng shang mǎi dōngxi. Zài wǎng shang jīhū shénme dōu kěyǐ mǎidào, nǐ kěyǐ shàng wǎng mǎi shū, mǎi yīfu, mǎi bāo, hái kěyǐ mǎi jiājù, mǎi shǒujī. Wǎng shang gòu wù nénggòu shòudào rénmen de xǐ'ài, yuányīn zhǔyào yǒu liǎng ge: Shǒuxiān, wǎng shang de dōngxi hěn duō, érqiě bǐ qù shāngdiàn mǎi piányi, zhè shì xīyǐn rénmen gòumǎi de zhǔyào yuányīn. Qícì, rénmen kěyǐ zài rènhé shíjiān shàng wǎng gòumǎi zìjǐ xǐhuan de dōngxi, mài jiā kěyǐ bǎ nǐ mǎi de dōngxi jì dào nǐ bàngōngshì huòzhě jiālǐ, fēicháng fāngbiàn.", "Hozir internetda xarid qilish tobora ommalashyapti, yoshlar ayniqsa internetda narsa olishni yoqtiradi. Internetda deyarli hamma narsani topish mumkin: kitob, kiyim, sumka, mebel, telefon. Onlayn xarid odamlar tomonidan yoqtirilishining asosan ikki sababi bor: birinchidan, internetda narsa juda ko'p va do'konga borib olgandan arzonroq, bu odamlarni xaridga jalb qiladigan asosiy sabab. Ikkinchidan, odamlar istalgan vaqtda internetga kirib yoqtirgan narsasini sotib olishi mumkin, sotuvchi esa xarid qilingan narsani ofisingizga yoki uyingizga jo'natadi, juda qulay.", "Сейчас покупки в интернете становятся всё популярнее, молодые люди особенно любят покупать вещи онлайн. В интернете можно купить почти всё: книги, одежду, сумки, мебель, телефоны. Есть две основные причины, почему онлайн-покупки нравятся людям: во-первых, в интернете много товаров, и они дешевле, чем в магазине; это главная причина, которая привлекает людей покупать. Во-вторых, люди могут в любое время купить в интернете то, что им нравится, а продавец может отправить покупку в офис или домой, это очень удобно.", "Ҳоло хариди интернетӣ рӯз ба рӯз маъмултар мешавад, ҷавонон хусусан дар интернет чиз хариданро дӯст медоранд. Дар интернет қариб ҳама чизро харидан мумкин: китоб, либос, сумка, мебел, телефон. Сабаби дӯстдошта шудани хариди онлайн асосан дутост: аввал, дар интернет чизҳо зиёданд ва аз мағоза арзонтаранд, ин сабаби асосии ҷалби одамон ба харид аст. Дуввум, одамон метавонанд дар ҳар вақт чизҳои писандидаашонро онлайн харанд, фурӯшанда бошад чизро ба офис ё хона мефиристад, хеле қулай аст."),
                ],
            },
        ],
    },
    6: {
        "title": "一分钱一分货",
        "goal": {
            "uz": "narx va sifat, chegirma, xizmat va savdo aksiyalari haqida gapirish; 竟然, 倍, 值得, 其中 va （在）……下 grammatikalarini ishlatish",
            "ru": "говорить о цене и качестве, скидках, сервисе и торговых акциях; использовать 竟然, 倍, 值得, 其中 и （在）……下",
            "tj": "дар бораи нарх ва сифат, тахфиф, хизмат ва чорабиниҳои савдо гуфтугӯ кардан; истифодаи 竟然, 倍, 值得, 其中 ва （在）……下",
        },
        "intro_text": {
            "uz": "Bu darsda xarid paytidagi kutilmagan holatlar, narxning necha baravar bo'lishi, arziydigan tanlov va aksiyalar haqida gapirishni o'rganasiz. Har qismda matnga mos yangi so'zlar, pinyin, tarjima va grammatika beriladi.",
            "ru": "В этом уроке вы научитесь говорить о неожиданных ситуациях при покупках, кратности цены, стоящем выборе и акциях. В каждой части есть слова, pinyin, перевод и грамматика по тексту.",
            "tj": "Дар ин дарс дар бораи ҳолатҳои ногаҳонӣ ҳангоми харид, чанд баробар будани нарх, интихоби арзанда ва аксияҳо гуфтугӯ карданро меомӯзед. Дар ҳар қисм калимаҳо, pinyin, тарҷума ва грамматикаи мувофиқи матн дода мешавад.",
        },
        "vocabulary": [
            _word(1, "果汁", "guǒzhī", "n.", "meva sharbati", "фруктовый сок", "шарбати мева"),
            _word(2, "售货员", "shòuhuòyuán", "n.", "sotuvchi", "продавец", "фурӯшанда"),
            _word(3, "袜子", "wàzi", "n.", "paypoq", "носки", "ҷӯроб"),
            _word(4, "打扰", "dǎrǎo", "v.", "bezovta qilmoq", "беспокоить, мешать", "халал расондан, нороҳат кардан"),
            _word(5, "竟然", "jìngrán", "adv.", "kutilmaganda, hayratlanarlisi", "неожиданно, удивительно", "ногаҳон, тааҷҷубовар"),
            _word(6, "西红柿", "xīhóngshì", "n.", "pomidor", "помидор", "помидор"),
            _word(7, "百分之", "bǎi fēn zhī", "", "foiz", "процент", "фоиз"),
            _word(8, "倍", "bèi", "m.", "marta, baravar", "раз, крат", "маротиба, баробар"),
            _word(9, "皮肤", "pífū", "n.", "teri", "кожа", "пӯст"),
            _word(10, "好处", "hǎochu", "n.", "foyda, afzallik", "польза, преимущество", "фоида, бартарӣ"),
            _word(11, "尝", "cháng", "v.", "tatib ko'rmoq", "пробовать на вкус", "чашидан"),
            _word(12, "轻", "qīng", "adj.", "yengil", "лёгкий", "сабук"),
            _word(13, "方面", "fāngmiàn", "n.", "jihat, tomon", "сторона, аспект", "ҷиҳат, тараф"),
            _word(14, "值得", "zhíde", "v.", "arziydigan", "стоить, быть достойным", "арзидан"),
            _word(15, "活动", "huódòng", "n.", "tadbir, aksiya", "мероприятие, акция", "чорабинӣ, аксия"),
            _word(16, "内", "nèi", "n.", "ichida, davomida", "внутри, в течение", "дар дохил, дар давоми"),
            _word(17, "免费", "miǎnfèi", "v.", "bepul", "бесплатный", "ройгон"),
            _word(18, "修理", "xiūlǐ", "v.", "ta'mirlamoq", "ремонтировать", "таъмир кардан"),
            _word(19, "支持", "zhīchí", "v.", "qo'llab-quvvatlamoq", "поддерживать", "дастгирӣ кардан"),
            _word(20, "举行", "jǔxíng", "v.", "o'tkazmoq", "проводить", "баргузор кардан"),
            _word(21, "满", "mǎn", "v.", "to'lmoq, ma'lum summaga yetmoq", "достигать суммы, быть полным", "пур шудан, ба маблағ расидан"),
            _word(22, "其中", "qízhōng", "n.", "ular ichida, shular orasida", "среди них, в том числе", "дар байни онҳо"),
            _word(23, "小说", "xiǎoshuō", "n.", "roman, hikoya", "роман, рассказ", "роман, ҳикоя"),
            _word(24, "会员卡", "huìyuánkǎ", "n.", "a'zolik kartasi", "членская карта", "корти аъзогӣ"),
            _word(25, "所有", "suǒyǒu", "adj.", "barcha, hamma", "все, весь", "ҳама"),
            _word(26, "获得", "huòdé", "v.", "qo'lga kiritmoq, olmoq", "получать, приобретать", "ба даст овардан"),
            _word(27, "情况", "qíngkuàng", "n.", "holat, vaziyat", "ситуация, положение", "ҳолат, вазъият"),
            _word(28, "例如", "lìrú", "v.", "masalan", "например", "масалан"),
            _word(29, "举办", "jǔbàn", "v.", "tashkil qilmoq, o'tkazmoq", "организовывать, проводить", "ташкил кардан, баргузор кардан"),
            _word(30, "各", "gè", "pron.", "har xil, har bir", "каждый, разные", "ҳар, гуногун"),
            _word(31, "降低", "jiàngdī", "v.", "pasaytirmoq", "снижать", "паст кардан"),
        ],
        "grammar": [
            _grammar(1, "竟然", "kutilmaganda", "неожиданно", "ногаҳон", "Kutilmagan, hayratli natijani bildiradi.", "Показывает неожиданный, удивительный результат.", "Натиҷаи ногаҳонӣ ё тааҷҷубоварро нишон медиҳад.", "竟然忘了去商场的超市买果汁！", "Jìngrán wàngle qù shāngchǎng de chāoshì mǎi guǒzhī!", "Kutilmaganda savdo markazidagi supermarketga sharbat olishga borishni unutibman!", "Неожиданно я забыл пойти в супермаркет торгового центра купить сок!", "Ногаҳон фаромӯш кардаам, ки ба супермаркети маркази савдо барои шарбат равам!"),
            _grammar(2, "倍", "marta, baravar", "раз, крат", "маротиба, баробар", "A 是 B 的 N 倍 shakli A ning B dan necha baravar ekanini bildiradi.", "Конструкция A 是 B 的 N 倍 показывает, во сколько раз A больше B.", "Қолиби A 是 B 的 N 倍 нишон медиҳад, ки A аз B чанд баробар аст.", "今天的价格是昨天的两倍。", "Jīntiān de jiàgé shì zuótiān de liǎng bèi.", "Bugungi narx kechagining ikki baravari.", "Сегодняшняя цена в два раза выше вчерашней.", "Нархи имрӯз ду баробари дирӯза аст."),
            _grammar(3, "值得", "arziydi", "стоит", "меарзад", "值得 + fe'l/narsa bir ishni qilishga arziydiganini bildiradi.", "值得 + глагол/предмет означает, что что-то стоит сделать или рассмотреть.", "值得 + феъл/чиз маънои арзанда будани иҷро ё баррасиро медиҳад.", "都是值得考虑的。", "Dōu shì zhíde kǎolǜ de.", "Hammasi ko'rib chiqishga arziydi.", "Всё это стоит рассмотреть.", "Ҳамааш ба баррасӣ меарзад."),
            _grammar(4, "其中", "ular ichida", "среди них", "дар байни онҳо", "Oldin aytilgan guruh ichidagi bir qismini ajratib ko'rsatadi.", "Выделяет часть внутри уже названной группы.", "Як қисмро аз гурӯҳи пеш гуфташуда ҷудо нишон медиҳад.", "其中，小说7.5折，地图8折，留学考试用书6折。", "Qízhōng, xiǎoshuō qīwǔ zhé, dìtú bā zhé, liúxué kǎoshì yòngshū liù zhé.", "Ular ichida romanlar 25% chegirma, xaritalar 20% chegirma, chet elda o'qish imtihoni kitoblari 40% chegirma.", "Среди них романы со скидкой 25%, карты со скидкой 20%, книги для экзаменов на обучение за рубежом со скидкой 40%.", "Дар байни онҳо романҳо 25% тахфиф, харитаҳо 20% тахфиф, китобҳои имтиҳони таҳсил дар хориҷ 40% тахфиф доранд."),
            _grammar(5, "（在）……下", "... sharoitida", "в условиях...", "дар шароити...", "O'rtadagi qism odatda ikki bo'g'inli ot yoki fe'l bo'lib, shart yoki vaziyatni bildiradi.", "Средняя часть обычно двусложное существительное или глагол и обозначает условие или ситуацию.", "Қисми миёна одатан исм ё феъли дуҳиҷоӣ буда, шарт ё вазъиятро нишон медиҳад.", "一般情况下，你花的钱越多，买的东西也就越好。", "Yìbān qíngkuàng xià, nǐ huā de qián yuè duō, mǎi de dōngxi yě jiù yuè hǎo.", "Odatdagi holatda qancha ko'p pul sarflasang, olgan narsang shuncha yaxshi bo'ladi.", "В обычных условиях чем больше денег ты тратишь, тем лучше вещь покупаешь.", "Дар ҳолати одӣ ҳар қадар пули бештар сарф кунӣ, чизе ки мехарӣ ҳамон қадар беҳтар мешавад."),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "张远 va 李进 kechagi xarid haqida gaplashadi",
                "scene_ru": "张远 и 李进 говорят о вчерашних покупках",
                "scene_tj": "张远 ва 李进 дар бораи хариди дирӯза гуфтугӯ мекунанд",
                "word_nos": [1, 2, 3, 4, 5],
                "grammar_nos": [1],
                "dialogue": [
                    _line("张远", "昨天晚上我给你打电话一直没人接，你忙什么呢？", "Zuótiān wǎnshang wǒ gěi nǐ dǎ diànhuà yìzhí méi rén jiē, nǐ máng shénme ne?", "Kecha kechqurun senga telefon qildim, hech kim olmadi, nima bilan band eding?", "Вчера вечером я звонил тебе, но никто не отвечал. Чем ты был занят?", "Дирӯз бегоҳ ба ту занг задам, касе нагирифт. Бо чӣ банд будӣ?"),
                    _line("李进", "昨天妻子让我陪她去超市买果汁。我把手机忘在家里了。", "Zuótiān qīzi ràng wǒ péi tā qù chāoshì mǎi guǒzhī. Wǒ bǎ shǒujī wàng zài jiālǐ le.", "Kecha xotinim meni supermarketga sharbat olishga birga borishga majbur qildi. Telefonimni uyda unutibman.", "Вчера жена попросила меня сходить с ней в супермаркет купить сок. Я забыл телефон дома.", "Дирӯз занам гуфт бо ӯ ба супермаркет барои харидани шарбат равам. Телефонамро дар хона фаромӯш кардаам."),
                    _line("张远", "买这么点儿东西也用不了那么长时间啊！", "Mǎi zhème diǎnr dōngxi yě yòng bù liǎo nàme cháng shíjiān a!", "Shunchagina narsa olishga ham bunchalik ko'p vaqt ketmaydi-ku!", "Чтобы купить так мало вещей, столько времени не нужно!", "Барои харидани ин қадар кам чиз ин қадар вақт лозим нест-ку!"),
                    _line("李进", "我们先去逛了会儿商场。一进门，售货员就热情地为我们介绍这、介绍那，她买了一条裤子、一件衬衫、两双袜子，然后我们就高高兴兴地回家了。", "Wǒmen xiān qù guàngle huìr shāngchǎng. Yí jìn mén, shòuhuòyuán jiù rèqíng de wèi wǒmen jièshào zhè, jièshào nà, tā mǎile yì tiáo kùzi, yí jiàn chènshān, liǎng shuāng wàzi, ránhòu wǒmen jiù gāogāoxìngxìng de huí jiā le.", "Biz avval savdo markazini biroz aylandik. Eshikdan kirishimiz bilan sotuvchi bizga buni ham, unisini ham qizg'in tanishtirdi. U bir shim, bir ko'ylak va ikki juft paypoq oldi, keyin xursand bo'lib uyga qaytdik.", "Сначала мы немного походили по торговому центру. Как только вошли, продавец стал горячо представлять нам то одно, то другое. Она купила брюки, рубашку и две пары носков, потом мы радостно вернулись домой.", "Мо аввал каме маркази савдоро гаштем. Ҳамин ки ворид шудем, фурӯшанда гармона ину онро нишон дод. Ӯ як шим, як курта ва ду ҷуфт ҷӯроб харид, баъд хурсандона ба хона баргаштем."),
                    _line("张远", "买东西时我只看自己想买的，而且喜欢自己看、自己选，不希望被别人打扰。", "Mǎi dōngxi shí wǒ zhǐ kàn zìjǐ xiǎng mǎi de, érqiě xǐhuan zìjǐ kàn, zìjǐ xuǎn, bù xīwàng bèi biérén dǎrǎo.", "Xarid qilayotganda men faqat o'zim olmoqchi bo'lgan narsani ko'raman, o'zim ko'rib, o'zim tanlashni yoqtiraman, boshqalar bezovta qilishini xohlamayman.", "Когда покупаю вещи, я смотрю только то, что сам хочу купить, люблю сам смотреть и сам выбирать, не хочу, чтобы меня беспокоили.", "Ҳангоми харид ман танҳо чизеро мебинам, ки худам мехоҳам харам; дӯст медорам худам бинам, худам интихоб кунам ва намехоҳам касе халал расонад."),
                    _line("李进", "是啊！回家以后，我才发现，竟然忘了去商场的超市买果汁！", "Shì a! Huí jiā yǐhòu, wǒ cái fāxiàn, jìngrán wàngle qù shāngchǎng de chāoshì mǎi guǒzhī!", "Ha! Uyga qaytgandan keyin bildim, kutilmaganda savdo markazidagi supermarketga sharbat olishga borishni unutibman!", "Да! Только вернувшись домой, я обнаружил, что неожиданно забыл сходить в супермаркет торгового центра купить сок!", "Ҳа! Ба хона баргашта фаҳмидам, ки ногаҳон фаромӯш кардаам ба супермаркети маркази савдо барои шарбат равам!"),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "王静 do'konda pomidor sotib oladi",
                "scene_ru": "王静 покупает помидоры в магазине",
                "scene_tj": "王静 дар мағоза помидор мехарад",
                "word_nos": [6, 7, 8, 9, 10, 11],
                "grammar_nos": [2],
                "dialogue": [
                    _line("王静", "西红柿新鲜吗？怎么卖？", "Xīhóngshì xīnxiān ma? Zěnme mài?", "Pomidorlar yangimi? Qancha turadi?", "Помидоры свежие? Почём продаёте?", "Помидорҳо тару тозаанд? Чанд мефурӯшед?"),
                    _line("售货员", "七块钱一斤，您放心，保证百分之百新鲜。", "Qī kuài qián yì jīn, nín fàng xīn, bǎozhèng bǎi fēn zhī bǎi xīnxiān.", "Bir jin yetti yuan, xotirjam bo'ling, yuz foiz yangiligiga kafolat.", "Семь юаней за цзинь, не беспокойтесь, гарантирую стопроцентную свежесть.", "Як ҷин ҳафт юан, хотирҷамъ бошед, сад фоиз тару тоза буданаш кафолат."),
                    _line("王静", "怎么这么贵呀！我记得昨天才三块五一斤，今天的价格是昨天的两倍。", "Zěnme zhème guì ya! Wǒ jìde zuótiān cái sān kuài wǔ yì jīn, jīntiān de jiàgé shì zuótiān de liǎng bèi.", "Nega bunchalik qimmat! Kecha bir jin atigi uch yarim yuan edi deb eslayman, bugungi narx kechagining ikki baravari.", "Почему так дорого! Я помню, вчера было всего три с половиной юаня за цзинь, сегодняшняя цена в два раза выше вчерашней.", "Чаро ин қадар қимат! Ёдам ҳаст дирӯз як ҷин ҳамагӣ сеюним юан буд, нархи имрӯз ду баробари дирӯза аст."),
                    _line("售货员", "您问的这种是“绿色”的。一分钱一分货。每天吃一两个这种新鲜的西红柿，对皮肤有好处。", "Nín wèn de zhè zhǒng shì “lǜsè” de. Yì fēn qián yì fēn huò. Měi tiān chī yì liǎng ge zhè zhǒng xīnxiān de xīhóngshì, duì pífū yǒu hǎochu.", "Siz so'ragan bu turi 'yashil' mahsulot. Bir tiyin - bir tiyinlik sifat. Har kuni bunday yangi pomidordan bir-ikkita yeyish teriga foydali.", "Этот вид, о котором вы спрашиваете, 'зелёный'. За что платишь, то и получаешь. Если каждый день есть один-два таких свежих помидора, это полезно для кожи.", "Ин навъе ки мепурсед, 'сабз' аст. Ҳар қадар пул, ҳамон қадар мол. Ҳар рӯз як-дуто чунин помидори тару тоза хӯрдан барои пӯст фоида дорад."),
                    _line("王静", "好，那我先买几个尝尝。", "Hǎo, nà wǒ xiān mǎi jǐ ge chángchang.", "Yaxshi, unda avval bir nechtasini olib tatib ko'raman.", "Хорошо, тогда сначала куплю несколько попробовать.", "Хуб, пас аввал чандто мехарам, бичашам."),
                    _line("售货员", "好的，给您西红柿，一共两斤，十四块。", "Hǎo de, gěi nín xīhóngshì, yígòng liǎng jīn, shísì kuài.", "Marhamat, pomidoringiz, jami ikki jin, o'n to'rt yuan.", "Хорошо, вот ваши помидоры, всего два цзиня, четырнадцать юаней.", "Хуб, ин помидорҳоятон, ҳамагӣ ду ҷин, чордаҳ юан."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "李进 savdo markazida chamadon tanlaydi",
                "scene_ru": "李进 выбирает чемодан в торговом центре",
                "scene_tj": "李进 дар маркази савдо ҷомадон интихоб мекунад",
                "word_nos": [12, 13, 14, 15, 16, 17, 18],
                "grammar_nos": [3],
                "dialogue": [
                    _line("售货员", "先生，我们店的行李箱都在这里，请问您要什么样的？", "Xiānsheng, wǒmen diàn de xínglixiāng dōu zài zhèli, qǐngwèn nín yào shénme yàng de?", "Janob, do'konimizdagi barcha chamadonlar shu yerda, siz qandayini xohlaysiz?", "Господин, все чемоданы нашего магазина здесь. Какой вам нужен?", "Ҷаноб, ҳама ҷомадонҳои мағозаи мо инҷоянд. Шумо чӣ гуна мехоҳед?"),
                    _line("李进", "我想买一个轻一点儿的。", "Wǒ xiǎng mǎi yí ge qīng yìdiǎnr de.", "Biroz yengilrog'ini olmoqchiman.", "Я хочу купить немного полегче.", "Ман мехоҳам яктои сабуктар харам."),
                    _line("售货员", "您看看这个，不管从价格方面看，还是从质量上看，都是值得考虑的。", "Nín kànkan zhège, bùguǎn cóng jiàgé fāngmiàn kàn, háishi cóng zhìliàng shang kàn, dōu shì zhíde kǎolǜ de.", "Mana bunga qarang, narx jihatidan bo'ladimi yoki sifat jihatidanmi, ko'rib chiqishga arziydi.", "Посмотрите этот: и с точки зрения цены, и с точки зрения качества, его стоит рассмотреть.", "Инро бинед, хоҳ аз ҷиҳати нарх бошад, хоҳ аз ҷиҳати сифат, ба баррасӣ меарзад."),
                    _line("李进", "质量是不错。请问这个多少钱？", "Zhìliàng shì búcuò. Qǐngwèn zhège duōshǎo qián?", "Sifati yaxshi ekan. Bu qancha turadi?", "Качество неплохое. Сколько он стоит?", "Сифаташ хуб аст. Ин чанд пул?"),
                    _line("售货员", "现在我们商场正好有打折活动，打完折是999。另外，一年内我们都负责免费修理。", "Xiànzài wǒmen shāngchǎng zhènghǎo yǒu dǎ zhé huódòng, dǎ wán zhé shì jiǔjiǔjiǔ. Lìngwài, yì nián nèi wǒmen dōu fùzé miǎnfèi xiūlǐ.", "Hozir savdo markazimizda aynan chegirma aksiyasi bor, chegirmadan keyin 999. Bundan tashqari bir yil ichida bepul ta'mirlashga biz javobgarmiz.", "Сейчас в нашем торговом центре как раз акция со скидкой, после скидки - 999. Кроме того, в течение года мы отвечаем за бесплатный ремонт.", "Ҳоло дар маркази савдои мо айни вақт аксияи тахфиф аст, баъди тахфиф 999. Ғайр аз ин, дар давоми як сол мо таъмири ройгонро ба ӯҳда мегирем."),
                    _line("李进", "你们的服务不错，价格也可以，就买这个吧。", "Nǐmen de fúwù búcuò, jiàgé yě kěyǐ, jiù mǎi zhège ba.", "Xizmatingiz yaxshi, narxi ham bo'ladi, shuni olay.", "У вас хороший сервис, цена тоже подходит, возьму этот.", "Хизматрасониатон хуб аст, нархаш ҳам мешавад, ҳаминро мегирам."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Kitob do'konidagi aksiya haqida e'lon",
                "scene_ru": "Объявление об акции в книжном магазине",
                "scene_tj": "Эълон дар бораи аксияи мағозаи китоб",
                "word_nos": [19, 20, 21, 22, 23, 24, 25, 26],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "顾客朋友们，为了感谢大家的支持，我们书店今天举行“购书送好礼”活动，购书满100元送一个笔记本，满200元送一本词典。另外，一些图书还有打折活动，其中，小说7.5折，地图8折，留学考试用书6折。如果购书满500元可免费办会员卡，以后购书可打8折。今天过生日的朋友和所有的小朋友还可以获得一份小礼物。欢迎大家选购！", "Gùkè péngyǒumen, wèile gǎnxiè dàjiā de zhīchí, wǒmen shūdiàn jīntiān jǔxíng “gòu shū sòng hǎo lǐ” huódòng, gòu shū mǎn yìbǎi yuán sòng yí ge bǐjìběn, mǎn èrbǎi yuán sòng yì běn cídiǎn. Lìngwài, yìxiē túshū hái yǒu dǎ zhé huódòng, qízhōng, xiǎoshuō qīwǔ zhé, dìtú bā zhé, liúxué kǎoshì yòngshū liù zhé. Rúguǒ gòu shū mǎn wǔbǎi yuán kě miǎnfèi bàn huìyuánkǎ, yǐhòu gòu shū kě dǎ bā zhé. Jīntiān guò shēngrì de péngyǒu hé suǒyǒu de xiǎopéngyǒu hái kěyǐ huòdé yí fèn xiǎo lǐwù. Huānyíng dàjiā xuǎngòu!", "Hurmatli xaridorlar, qo'llab-quvvatlaganingiz uchun rahmat sifatida kitob do'konimiz bugun 'kitob ol - yaxshi sovg'a ol' aksiyasini o'tkazmoqda: 100 yuanga kitob olsangiz bitta daftar, 200 yuanga olsangiz bitta lug'at beriladi. Bundan tashqari, ayrim kitoblarda chegirma ham bor: romanlar 25% chegirma, xaritalar 20% chegirma, chet elda o'qish imtihoni kitoblari 40% chegirma. Agar 500 yuanga kitob olsangiz, bepul a'zolik kartasi rasmiylashtirasiz, keyingi xaridlarda 20% chegirma bo'ladi. Bugun tug'ilgan kuni bo'lganlar va barcha bolalar kichik sovg'a ham oladi. Tanlab xarid qilishingizni kutamiz!", "Дорогие покупатели, чтобы поблагодарить всех за поддержку, наш книжный магазин сегодня проводит акцию 'купи книгу - получи хороший подарок': при покупке книг на 100 юаней дарим блокнот, на 200 юаней - словарь. Кроме того, на некоторые книги есть скидки: романы 25%, карты 20%, книги для экзаменов на обучение за рубежом 40%. Если купить книг на 500 юаней, можно бесплатно оформить членскую карту, а затем покупать книги со скидкой 20%. Друзья, у кого сегодня день рождения, и все дети также могут получить маленький подарок. Добро пожаловать за покупками!", "Мизоҷони азиз, барои ташаккур аз дастгирии шумо мағозаи китобамон имрӯз аксияи 'китоб харед, тӯҳфаи хуб гиред' баргузор мекунад: агар китоб ба маблағи 100 юан харед, як дафтар, ба 200 юан як луғат дода мешавад. Ғайр аз ин, баъзе китобҳо тахфиф доранд: романҳо 25%, харитаҳо 20%, китобҳои имтиҳони таҳсил дар хориҷ 40%. Агар китоб ба 500 юан харед, метавонед ройгон корти аъзогӣ гиред ва баъд китобҳоро бо 20% тахфиф харед. Дӯстоне, ки имрӯз зодрӯз доранд, ва ҳамаи кӯдакон низ як тӯҳфаи хурд мегиранд. Марҳамат, интихоб кунед!"),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Narx va sifat munosabati haqida matn",
                "scene_ru": "Текст о связи цены и качества",
                "scene_tj": "Матн дар бораи робитаи нарх ва сифат",
                "word_nos": [27, 28, 29, 30, 31],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "人们常说“一分钱一分货”，意思是东西的质量和价格有很大的关系，也可以说“便宜没好货，好货不便宜”，一般情况下，你花的钱越多，买的东西也就越好。其实也不一定都是这样的。有的时候，质量很好的东西也会很便宜。例如，春天来了，冬天的衣服就会打折，质量很好，还很便宜，花很少的钱就可以买到。一到节日，商场也会举办各种各样的活动，降低价格，这个时候我们也可以买到又便宜又好的东西。", "Rénmen cháng shuō “yì fēn qián yì fēn huò”, yìsi shì dōngxi de zhìliàng hé jiàgé yǒu hěn dà de guānxi, yě kěyǐ shuō “piányi méi hǎo huò, hǎo huò bù piányi”, yìbān qíngkuàng xià, nǐ huā de qián yuè duō, mǎi de dōngxi yě jiù yuè hǎo. Qíshí yě bù yídìng dōu shì zhèyàng de. Yǒu de shíhou, zhìliàng hěn hǎo de dōngxi yě huì hěn piányi. Lìrú, chūntiān lái le, dōngtiān de yīfu jiù huì dǎ zhé, zhìliàng hěn hǎo, hái hěn piányi, huā hěn shǎo de qián jiù kěyǐ mǎidào. Yí dào jiérì, shāngchǎng yě huì jǔbàn gè zhǒng gè yàng de huódòng, jiàngdī jiàgé, zhège shíhou wǒmen yě kěyǐ mǎidào yòu piányi yòu hǎo de dōngxi.", "Odamlar ko'p aytadi: 'qancha pul - shuncha mol', ya'ni narsaning sifati va narxi o'rtasida katta aloqa bor; 'arzon mol yaxshi bo'lmaydi, yaxshi mol arzon bo'lmaydi' desa ham bo'ladi. Odatda qancha ko'p pul sarflasangiz, olgan narsangiz shuncha yaxshi bo'ladi. Aslida har doim ham shunday emas. Ba'zan sifati juda yaxshi narsalar ham arzon bo'lishi mumkin. Masalan, bahor kelganda qishki kiyimlar chegirmaga tushadi: sifati yaxshi, narxi ham arzon, juda kam pulga olish mumkin. Bayram payti savdo markazlari ham turli tadbirlar o'tkazib, narxlarni pasaytiradi; shu paytda biz ham arzon va yaxshi narsalarni topa olamiz.", "Люди часто говорят: 'сколько заплатил, такой и товар', то есть качество вещи сильно связано с ценой; можно также сказать: 'дешёвый товар не бывает хорошим, хороший товар не бывает дешёвым'. В обычных условиях чем больше денег тратишь, тем лучше вещь покупаешь. На самом деле это не всегда так. Иногда вещи очень хорошего качества тоже бывают дешёвыми. Например, когда приходит весна, зимняя одежда получает скидки: качество хорошее, цена низкая, можно купить за совсем небольшие деньги. Во время праздников торговые центры тоже проводят разные акции и снижают цены; в это время мы тоже можем купить дешёвые и хорошие вещи.", "Одамон бисёр мегӯянд: 'ҳар қадар пул, ҳамон қадар мол', яъне сифати чиз бо нарх робитаи калон дорад; инчунин метавон гуфт: 'моли арзон хуб нест, моли хуб арзон нест'. Дар ҳолати одӣ ҳар қадар пули бештар сарф кунед, чизи харидаатон ҳамон қадар беҳтар мешавад. Дар асл ҳамеша чунин нест. Баъзан чизҳои сифати хуб ҳам арзон мешаванд. Масалан, баҳор ки омад, либоси зимистона тахфиф мешавад: сифати хуб дорад ва арзон аст, бо пули кам харидан мумкин. Дар рӯзҳои ид марказҳои савдо ҳам чорабиниҳои гуногун баргузор карда, нархро паст мекунанд; дар он вақт мо низ чизҳои ҳам арзон ва ҳам хубро харида метавонем."),
                ],
            },
        ],
    },
}
