def _word(no, zh, pinyin, pos, uz, ru, tj):
    return {"no": no, "zh": zh, "pinyin": pinyin, "pos": pos, "uz": uz, "ru": ru, "tj": tj}


def _line(speaker, zh, pinyin, uz, ru, tj):
    return {"speaker": speaker, "zh": zh, "pinyin": pinyin, "uz": uz, "ru": ru, "tj": tj}


def _grammar(no, title_zh, title_uz, title_ru, title_tj, rule_uz, rule_ru, rule_tj, example_zh, example_pinyin, example_uz, example_ru, example_tj):
    return {
        "no": no,
        "title_zh": title_zh,
        "title_uz": title_uz,
        "title_ru": title_ru,
        "title_tj": title_tj,
        "rule_uz": rule_uz,
        "rule_ru": rule_ru,
        "rule_tj": rule_tj,
        "formula": title_zh,
        "examples": [
            {
                "zh": example_zh,
                "pinyin": example_pinyin,
                "uz": example_uz,
                "ru": example_ru,
                "tj": example_tj,
            }
        ],
    }


HSK4_LOWER_PDF_MATERIALS_14_16 = {
    14: {
        "title": "保护地球母亲",
        "goal": {
            "uz": "atrof-muhitni himoya qilish, tejash va ekologik odatlar haqida gapirish; 够, 以, 既然, 于是/因此 va 只有...才 grammatikalarini ishlatish",
            "ru": "говорить о защите окружающей среды, экономии и экологичных привычках; использовать 够, 以, 既然, 于是/因此 и 只有...才",
            "tj": "дар бораи ҳифзи муҳити зист, сарфа ва одатҳои экологӣ гуфтугӯ кардан; истифодаи 够, 以, 既然, 于是/因此 ва 只有...才",
        },
        "intro_text": {
            "uz": "Bu darsda safarda ortiqcha buyum olmay yurish, restoran tozaligi, \"Yer soati\", plastik paket va kundalik ekologik odatlar haqida gapirishni o'rganasiz.",
            "ru": "В этом уроке вы научитесь говорить о лишних вещах в поездке, чистоте ресторана, «Часе Земли», пластиковых пакетах и бытовых экологичных привычках.",
            "tj": "Дар ин дарс дар бораи ашёи зиёдатӣ дар сафар, тозагии тарабхона, «Соати Замин», халтаҳои пластикӣ ва одатҳои ҳаррӯзаи экологӣ меомӯзед.",
        },
        "vocabulary": [
            _word(1, "出差", "chūchāi", "v.", "xizmat safariga bormoq", "ехать в командировку", "ба сафари хизматӣ рафтан"),
            _word(2, "毛巾", "máojīn", "n.", "sochiq", "полотенце", "дастмол"),
            _word(3, "牙膏", "yágāo", "n.", "tish pastasi", "зубная паста", "хамираи дандон"),
            _word(4, "重", "zhòng", "adj.", "og'ir", "тяжёлый", "вазнин"),
            _word(5, "行", "xíng", "v.", "bo'ladi, mayli", "подходит, хорошо", "мешавад, хуб"),
            _word(6, "省", "shěng", "v.", "tejamoq", "экономить", "сарфа кардан"),
            _word(7, "污染", "wūrǎn", "v.", "ifloslantirmoq", "загрязнять", "ифлос кардан"),
            _word(8, "卫生间", "wèishēngjiān", "n.", "hojatxona", "туалет, уборная", "ҳоҷатхона"),
            _word(9, "脏", "zāng", "adj.", "kir, iflos", "грязный", "ифлос"),
            _word(10, "抱歉", "bàoqiàn", "v.", "uzr so'ramoq, afsuslanmoq", "извиняться, сожалеть", "узр пурсидан"),
            _word(11, "空", "kōng", "adj.", "bo'sh", "пустой", "холӣ"),
            _word(12, "盒子", "hézi", "n.", "quti", "коробка", "қуттӣ"),
            _word(13, "扔", "rēng", "v.", "tashlamoq, uloqtirmoq", "выбрасывать, бросать", "партофтан"),
            _word(14, "以", "yǐ", "prep.", "orqali, vositasida", "через, посредством", "бо воситаи"),
            _word(15, "速度", "sùdù", "n.", "tezlik", "скорость", "суръат"),
            _word(16, "地球", "dìqiú", "n.", "Yer sayyorasi", "Земля, земной шар", "Замин"),
            _word(17, "既然", "jìrán", "conj.", "modomiki, shunday ekan", "раз уж, поскольку", "азбаски, модом ки"),
            _word(18, "停", "tíng", "v.", "to'xtamoq, to'xtatmoq", "останавливаться", "истодан, қатъ кардан"),
            _word(19, "得意", "déyì", "adj.", "o'zidan mamnun", "довольный собой", "худписандона хурсанд"),
            _word(20, "目的", "mùdì", "n.", "maqsad", "цель", "мақсад"),
            _word(21, "暖", "nuǎn", "adj.", "iliq", "тёплый", "гарм"),
            _word(22, "塑料袋", "sùliàodài", "n.", "plastik paket", "пластиковый пакет", "халтаи пластикӣ"),
            _word(23, "于是", "yúshì", "conj.", "shuning uchun, natijada", "поэтому, вследствие этого", "бинобар ин, пас"),
            _word(24, "鼓励", "gǔlì", "v.", "rag'batlantirmoq", "поощрять", "ҳавасманд кардан"),
            _word(25, "拒绝", "jùjué", "v.", "rad etmoq", "отказывать", "рад кардан"),
            _word(26, "减少", "jiǎnshǎo", "v.", "kamaytirmoq", "сокращать", "кам кардан"),
            _word(27, "数量", "shùliàng", "n.", "miqdor", "количество", "миқдор"),
            _word(28, "温度", "wēndù", "n.", "harorat", "температура", "ҳарорат"),
            _word(29, "乘坐", "chéngzuò", "v.", "transportga minmoq", "ехать на транспорте", "савор шудан"),
            _word(30, "丢", "diū", "v.", "tashlamoq, yo'qotmoq", "бросать, терять", "партофтан, гум кардан"),
            _word(31, "垃圾桶", "lājītǒng", "n.", "axlat qutisi", "мусорное ведро", "қуттии партов"),
            _word(32, "美丽", "měilì", "adj.", "go'zal", "красивый", "зебо"),
        ],
        "grammar": [
            _grammar(1, "够", "yetarli darajada", "достаточно", "ба қадри кофӣ", "Sifat yoki fe'l oldida daraja yetganini bildiradi.", "Показывает, что степень уже достигнута.", "Нишон медиҳад, ки дараҷа ба ҳадди кофӣ расидааст.", "箱子已经够重的了！", "Xiāngzi yǐjīng gòu zhòng de le!", "Chamadon allaqachon yetarlicha og'ir bo'libdi!", "Чемодан уже достаточно тяжёлый!", "Ҷомадон аллакай кофӣ вазнин шудааст!"),
            _grammar(2, "以", "orqali, vositasida", "посредством, с помощью", "бо воситаи", "Usul, vosita yoki standartni oldinga chiqaradi.", "Выносит вперёд способ, средство или стандарт.", "Усул, восита ё меъёрро пеш меорад.", "我一定以最快的速度完成。", "Wǒ yídìng yǐ zuì kuài de sùdù wánchéng.", "Men albatta eng tez sur'atda tugataman.", "Я обязательно выполню с максимальной скоростью.", "Ман ҳатман бо суръати баландтарин анҷом медиҳам."),
            _grammar(3, "既然……那么/就……", "modomiki..., unda...", "раз уж..., то...", "модом ки..., пас...", "Birinchi gapda mavjud fakt aytiladi, keyingisida tabiiy xulosa beriladi.", "В первой части дан факт, во второй - логичный вывод.", "Дар қисми аввал факт, дар қисми дуюм хулосаи табиӣ меояд.", "既然明天晚上公司会关灯停电，那么我们肯定不用加班了。", "Jìrán míngtiān wǎnshang gōngsī huì guān dēng tíng diàn, nàme wǒmen kěndìng búyòng jiābān le.", "Modomiki ertaga kechqurun kompaniyada chiroq o'chsa, unda biz albatta qo'shimcha ishlamaymiz.", "Раз завтра вечером в компании выключат свет, значит нам точно не нужно работать сверхурочно.", "Модом ки пагоҳ шаб дар ширкат чароғ хомӯш мешавад, пас мо бешак изофакорӣ намекунем."),
            _grammar(4, "于是/因此", "shuning uchun, natijada", "поэтому, вследствие этого", "бинобар ин, дар натиҷа", "Oldingi sabab yoki vaziyatdan keyingi natijani bog'laydi.", "Связывает предыдущую причину или ситуацию с результатом.", "Сабаб ё вазъияти пешинаро бо натиҷа мепайвандад.", "于是，一些国家规定，超市、商场不能为顾客提供免费塑料袋。", "Yúshì, yìxiē guójiā guīdìng, chāoshì, shāngchǎng bù néng wèi gùkè tígōng miǎnfèi sùliàodài.", "Shuning uchun ayrim davlatlar supermarket va savdo markazlariga bepul plastik paket berishni taqiqladi.", "Поэтому некоторые страны постановили, что супермаркеты и торговые центры не могут бесплатно выдавать пластиковые пакеты.", "Бинобар ин баъзе давлатҳо муқаррар карданд, ки супермаркетҳо ва марказҳои савдо халтаи пластикии ройгон дода наметавонанд."),
            _grammar(5, "只有……才……", "faqat...gina...", "только если..., тогда...", "танҳо агар..., он гоҳ...", "Zarur shartni bildiradi: shart bajarilsa, natija bo'ladi.", "Выражает необходимое условие: результат возможен только при нём.", "Шарти заруриро нишон медиҳад: натиҷа танҳо бо иҷрои он мешавад.", "只有大家共同努力，减少污染，保护环境，才能使我们的家变得更美丽。", "Zhǐyǒu dàjiā gòngtóng nǔlì, jiǎnshǎo wūrǎn, bǎohù huánjìng, cái néng shǐ wǒmen de jiā biàn de gèng měilì.", "Faqat hamma birga harakat qilib, ifloslanishni kamaytirsa va muhitni himoya qilsagina uyimiz yanada go'zal bo'ladi.", "Только если все вместе будут стараться, уменьшать загрязнение и защищать среду, наш дом станет красивее.", "Танҳо агар ҳама якҷо кӯшиш карда, ифлосиро кам ва муҳитро ҳифз кунанд, хонаи мо зеботар мешавад."),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "Li Jin xizmat safariga tayyorlanadi, Wang Jing ekologik odatlarni eslatadi",
                "scene_ru": "Ли Цзинь готовится к командировке, Ван Цзин напоминает об экологичных привычках",
                "scene_tj": "Ли Ҷин ба сафари хизматӣ омода мешавад, Ван Ҷинг одатҳои экологиро ёдрас мекунад",
                "word_nos": [1, 2, 3, 4, 5, 6, 7],
                "grammar_nos": [1],
                "dialogue": [
                    _line("王静", "这是明天你出差要带的毛巾、牙膏和牙刷，把它们放到箱子里吧。", "Zhè shì míngtiān nǐ chūchāi yào dài de máojīn, yágāo hé yáshuā, bǎ tāmen fàngdào xiāngzi li ba.", "Bular ertaga xizmat safariga olib ketadigan sochiq, tish pastasi va tish cho'tkang, chamadonga solib qo'y.", "Это полотенце, паста и щётка, которые ты завтра берёшь в командировку. Положи их в чемодан.", "Инҳо дастмол, хамираи дандон ва чуткаи дандонанд, ки пагоҳ ба сафар мебарӣ. Ба ҷомадон гузор."),
                    _line("李进", "不用拿这些，宾馆都会免费提供的。再说，箱子已经够重的了！", "Bùyòng ná zhèxiē, bīnguǎn dōu huì miǎnfèi tígōng de. Zàishuō, xiāngzi yǐjīng gòu zhòng de le!", "Bularni olish shart emas, mehmonxonada bepul beradi. Yana chamadon allaqachon yetarlicha og'ir.", "Это брать не нужно, гостиница всё предоставит бесплатно. К тому же чемодан уже достаточно тяжёлый.", "Инҳоро гирифтан шарт нест, меҳмонхона ройгон медиҳад. Ба ғайр аз ин, ҷомадон аллакай кофӣ вазнин аст."),
                    _line("王静", "我当然知道宾馆里有。你不是一直说要保护环境吗？现在就从身边的小事做起吧。", "Wǒ dāngrán zhīdào bīnguǎn li yǒu. Nǐ bú shì yìzhí shuō yào bǎohù huánjìng ma? Xiànzài jiù cóng shēnbiān de xiǎo shì zuòqǐ ba.", "Mehmonxonada borligini bilaman. Sen doim atrof-muhitni himoya qilish kerak derding-ku? Endi yonimizdagi kichik ishlardan boshlaylik.", "Я, конечно, знаю, что в гостинице это есть. Ты ведь всегда говорил о защите среды? Начнём с мелочей рядом с собой.", "Ман албатта медонам, ки дар меҳмонхона ҳаст. Ту ҳамеша мегуфтӣ муҳитро ҳифз кардан лозим? Пас аз корҳои хурди гирду атроф сар кунем."),
                    _line("李进", "行，没问题。我明天上午10点的飞机，你能开车把我送到机场吗？", "Xíng, méi wèntí. Wǒ míngtiān shàngwǔ shí diǎn de fēijī, nǐ néng kāi chē bǎ wǒ sòngdào jīchǎng ma?", "Mayli, muammo yo'q. Ertaga ertalab soat 10 da samolyotim bor, meni mashinada aeroportga olib bora olasanmi?", "Хорошо, без проблем. Завтра в 10 утра у меня самолёт, можешь отвезти меня в аэропорт?", "Майлаш, мушкил нест. Пагоҳ соати 10 ҳавопаймо дорам, маро бо мошин ба фурудгоҳ мебарӣ?"),
                    _line("王静", "那个时间路上堵车多严重啊！你还是坐地铁去机场吧。这样不仅省油钱，而且还不会污染空气。", "Nàge shíjiān lùshang dǔ chē duō yánzhòng a! Nǐ háishi zuò dìtiě qù jīchǎng ba. Zhèyàng bùjǐn shěng yóu qián, érqiě hái bú huì wūrǎn kōngqì.", "O'sha payt yo'lda tiqilinch juda kuchli bo'ladi. Aeroportga metroda bora qol. Shunda nafaqat benzin puli tejaladi, balki havoni ham ifloslantirmaysan.", "В это время на дорогах сильные пробки. Лучше езжай в аэропорт на метро. Так ты сэкономишь на бензине и не загрязнишь воздух.", "Он вақт роҳҳо сахт сермошин мешаванд. Беҳтараш ба фурудгоҳ бо метро рав. Ҳам пули бензин сарфа мешавад, ҳам ҳаво ифлос намешавад."),
                    _line("李进", "好，那就听你的。", "Hǎo, nà jiù tīng nǐ de.", "Yaxshi, unda sen aytgandek qilaman.", "Хорошо, тогда послушаю тебя.", "Хуб, пас ба гапи ту мекунам."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "Menejer restoran tozaligi va xizmat tezligini tekshiradi",
                "scene_ru": "Менеджер проверяет чистоту ресторана и скорость работы",
                "scene_tj": "Менеҷер тозагии тарабхона ва суръати корро месанҷад",
                "word_nos": [8, 9, 10, 11, 12, 13, 14, 15],
                "grammar_nos": [2],
                "dialogue": [
                    _line("经理", "小王，卫生间怎么那么脏啊？这会给客人留下不好的印象，快去打扫一下。", "Xiǎo Wáng, wèishēngjiān zěnme nàme zāng a? Zhè huì gěi kèrén liúxià bù hǎo de yìnxiàng, kuài qù dǎsǎo yíxià.", "Xiao Wang, hojatxona nega bunchalik kir? Bu mijozlarda yomon taassurot qoldiradi, tez borib tozalab kel.", "Сяо Ван, почему туалет такой грязный? Это оставит плохое впечатление у гостей, быстро убери.", "Сяо Ван, чаро ҳоҷатхона ин қадар ифлос аст? Ин ба меҳмонон таассуроти бад медиҳад, зуд тоза кун."),
                    _line("服务员", "经理，实在抱歉。今天店里太忙了，我还没来得及打扫。", "Jīnglǐ, shízài bàoqiàn. Jīntiān diàn li tài máng le, wǒ hái méi láidejí dǎsǎo.", "Menejer, juda uzr. Bugun do'kon juda band edi, tozalashga ulgurmadim.", "Менеджер, очень извиняюсь. Сегодня в заведении слишком много работы, я ещё не успел убрать.", "Менеҷер, хеле узр. Имрӯз ҷой хеле серкор буд, ҳанӯз ба тоза кардан нарасидем."),
                    _line("经理", "那张桌子下面还有一些空饮料瓶子和纸盒子。", "Nà zhāng zhuōzi xiàmian hái yǒu yìxiē kōng yǐnliào píngzi hé zhǐ hézi.", "Ana u stol ostida bo'sh ichimlik shishalari va qog'oz qutilar ham bor.", "Под тем столом ещё есть пустые бутылки от напитков и бумажные коробки.", "Зери он миз чанд шишаи холии нӯшокӣ ва қуттии коғазӣ ҳам ҳаст."),
                    _line("服务员", "好的，我马上就去把它们扔掉。", "Hǎo de, wǒ mǎshàng jiù qù bǎ tāmen rēngdiào.", "Xo'p, hoziroq borib ularni tashlab yuboraman.", "Хорошо, сейчас же выброшу их.", "Хуб, ҳозир онҳоро мепартоям."),
                    _line("经理", "以后你一定得注意这个问题，不管客人多不多，生意多忙，我们都要保证餐厅干净卫生。", "Yǐhòu nǐ yídìng děi zhùyì zhège wèntí, bùguǎn kèrén duō bu duō, shēngyì duō máng, wǒmen dōu yào bǎozhèng cāntīng gānjìng wèishēng.", "Keyin bu masalaga albatta e'tibor berishing kerak. Mijoz ko'pmi-yo'qmi, ish qanchalik band bo'lmasin, restoran toza va gigiyenik bo'lishi shart.", "Впредь обязательно обращай внимание на это. Независимо от количества гостей и занятости, ресторан должен быть чистым.", "Минбаъд ба ин масъала ҳатман диққат деҳ. Меҳмон зиёд бошад ё не, кор сер бошад ҳам, тарабхона бояд тоза бошад."),
                    _line("服务员", "经理您放心，我一定以最快的速度完成。不过咱们真的应该再多招聘几个服务员了。", "Jīnglǐ nín fàngxīn, wǒ yídìng yǐ zuì kuài de sùdù wánchéng. Búguò zánmen zhēn de yīnggāi zài duō zhāopìn jǐ ge fúwùyuán le.", "Xotirjam bo'ling, men albatta eng tez sur'atda bajaraman. Lekin haqiqatan ham yana bir nechta ofitsiant olishimiz kerak.", "Не волнуйтесь, я обязательно выполню это как можно быстрее. Но нам правда стоит нанять ещё нескольких официантов.", "Ором бошед, ман ҳатман бо суръати баландтарин анҷом медиҳам. Аммо дар ҳақиқат бояд боз чанд пешхизмат гирем."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "Sun Yue va Wang Jing \"Yer soati\" haqida gaplashadi",
                "scene_ru": "Сунь Юэ и Ван Цзин говорят о «Часе Земли»",
                "scene_tj": "Сун Юэ ва Ван Ҷинг дар бораи «Соати Замин» суҳбат мекунанд",
                "word_nos": [16, 17, 18, 19, 20, 21],
                "grammar_nos": [3],
                "dialogue": [
                    _line("孙月", "早上听新闻说明天有一个叫“地球一小时”的活动，你对这个活动了解吗？", "Zǎoshang tīng xīnwén shuō míngtiān yǒu yí ge jiào “Dìqiú Yì Xiǎoshí” de huódòng, nǐ duì zhège huódòng liǎojiě ma?", "Ertalab xabarda ertaga \"Yer soati\" degan tadbir bo'lishini eshitdim, bu tadbirni bilasanmi?", "Утром в новостях сказали, что завтра будет акция «Час Земли». Ты о ней знаешь?", "Саҳар аз хабар шунидам, ки пагоҳ чорабинии «Соати Замин» мешавад. Ту онро медонӣ?"),
                    _line("王静", "这个活动年年都有，最早是从2007年开始的。明天晚上很多人都会关灯一小时，支持这个活动。你没看到门口的通知吗？我们公司也参加。", "Zhège huódòng niánnián dōu yǒu, zuì zǎo shì cóng èr líng líng qī nián kāishǐ de. Míngtiān wǎnshang hěn duō rén dōu huì guān dēng yì xiǎoshí, zhīchí zhège huódòng. Nǐ méi kàndào ménkǒu de tōngzhī ma? Wǒmen gōngsī yě cānjiā.", "Bu tadbir har yili bo'ladi, ilk bor 2007-yilda boshlangan. Ertaga kechqurun ko'p odamlar bir soat chiroqni o'chirib, tadbirni qo'llab-quvvatlaydi. Eshik oldidagi e'lonni ko'rmadingmi? Bizning kompaniya ham qatnashadi.", "Эта акция проводится каждый год, впервые она началась в 2007 году. Завтра вечером многие выключат свет на час в поддержку акции. Ты не видел объявление у входа? Наша компания тоже участвует.", "Ин чорабинӣ ҳар сол мешавад, аввалин бор соли 2007 оғоз шудааст. Пагоҳ шаб бисёриҳо барои дастгирӣ як соат чароғро хомӯш мекунанд. Эълони назди дарро надидӣ? Ширкати мо ҳам иштирок мекунад."),
                    _line("孙月", "真的吗？太好了！既然明天晚上公司会关灯停电，那么我们肯定不用加班了。", "Zhēn de ma? Tài hǎo le! Jìrán míngtiān wǎnshang gōngsī huì guān dēng tíng diàn, nàme wǒmen kěndìng búyòng jiābān le.", "Rostdanmi? Juda yaxshi! Modomiki ertaga kechqurun kompaniyada chiroq o'chsa, unda biz albatta qo'shimcha ishlamaymiz.", "Правда? Отлично! Раз завтра вечером компания выключит свет, значит нам точно не нужно работать сверхурочно.", "Рост? Хеле хуб! Модом ки пагоҳ шаб ширкат чароғро хомӯш мекунад, пас мо бешак изофакорӣ намекунем."),
                    _line("王静", "看你得意的样子！还以为你高兴是为了支持环保，原来是因为不用加班啊！", "Kàn nǐ déyì de yàngzi! Hái yǐwéi nǐ gāoxìng shì wèile zhīchí huánbǎo, yuánlái shì yīnwèi búyòng jiābān a!", "O'zingdan mamnunligingni qara! Xursandliging ekologiyani qo'llab-quvvatlash uchun deb o'ylabman, aslida qo'shimcha ish yo'qligi uchun ekan-da!", "Посмотри, как ты радуешься! Я думала, ты рад ради защиты среды, а оказалось, потому что не надо перерабатывать!", "Бин, чӣ қадар хушҳолӣ! Фикр кардам барои дастгирии муҳит хурсандӣ, маълум шуд барои изофакорӣ накардан будааст!"),
                    _line("孙月", "环境保护我当然也支持了！对了，为什么会有这么一个活动啊？", "Huánjìng bǎohù wǒ dāngrán yě zhīchí le! Duì le, wèishénme huì yǒu zhème yí ge huódòng a?", "Atrof-muhit himoyasini albatta qo'llab-quvvatlayman! Aytgancha, nega bunday tadbir bor?", "Защиту среды я, конечно, тоже поддерживаю! Кстати, почему вообще есть такая акция?", "Ҳифзи муҳитро албатта ман ҳам дастгирӣ мекунам! Ростӣ, чаро чунин чорабинӣ ҳаст?"),
                    _line("王静", "其实目的挺简单的，就是提醒人们节约用电，希望引起人们对气候变暖问题的关注。", "Qíshí mùdì tǐng jiǎndān de, jiù shì tíxǐng rénmen jiéyuē yòng diàn, xīwàng yǐnqǐ rénmen duì qìhòu biàn nuǎn wèntí de guānzhù.", "Aslida maqsad oddiy: odamlarga elektrni tejashni eslatish va iqlim isishi muammosiga e'tibor qaratish.", "На самом деле цель простая: напомнить людям экономить электричество и привлечь внимание к потеплению климата.", "Дар асл мақсад сода аст: ба мардум сарфаи барқро ёдрас кардан ва таваҷҷуҳро ба гармшавии иқлим ҷалб кардан."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Plastik paketlardan foydalanish va ekologiya haqida matn",
                "scene_ru": "Текст о пластиковых пакетах и экологии",
                "scene_tj": "Матн дар бораи халтаҳои пластикӣ ва экологӣ",
                "word_nos": [22, 23, 24, 25, 26, 27],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "塑料袋给人们的生活带来方便，受到人们的普遍欢迎，可是，它的大量使用也带来了严重的环境污染问题。", "Sùliàodài gěi rénmen de shēnghuó dàilái fāngbiàn, shòudào rénmen de pǔbiàn huānyíng, kěshì, tā de dàliàng shǐyòng yě dàiláile yánzhòng de huánjìng wūrǎn wèntí.", "Plastik paketlar odamlar hayotiga qulaylik olib keldi va keng ommalashdi, lekin ularning ko'p ishlatilishi jiddiy ekologik ifloslanish muammosini ham keltirdi.", "Пластиковые пакеты удобны и широко популярны, но их массовое использование принесло серьёзную проблему загрязнения среды.", "Халтаҳои пластикӣ ба зиндагӣ осонӣ оварданд ва маъмул шуданд, аммо истифодаи зиёди онҳо мушкили ҷиддии ифлосшавии муҳитро овард."),
                    _line("旁白", "于是，一些国家规定，超市、商场不能为顾客提供免费塑料袋，并且鼓励大家购买可以多次使用的购物袋。", "Yúshì, yìxiē guójiā guīdìng, chāoshì, shāngchǎng bù néng wèi gùkè tígōng miǎnfèi sùliàodài, bìngqiě gǔlì dàjiā gòumǎi kěyǐ duō cì shǐyòng de gòuwùdài.", "Shuning uchun ayrim davlatlar supermarket va savdo markazlari mijozlarga bepul plastik paket bera olmasligini belgiladi va qayta ishlatiladigan xarid xaltalarini olishga undadi.", "Поэтому некоторые страны запретили супермаркетам и торговым центрам бесплатно выдавать пакеты и поощряют покупать многоразовые сумки.", "Бинобар ин баъзе давлатҳо супермаркету марказҳои савдоро аз додани халтаи ройгон манъ карданд ва харидани халтаҳои чандбористифодаро ташвиқ намуданд."),
                    _line("旁白", "我们每个人都有责任保护环境，因此，请大家节约使用塑料袋，或者购物时自备购物袋，甚至拒绝使用塑料袋。", "Wǒmen měi ge rén dōu yǒu zérèn bǎohù huánjìng, yīncǐ, qǐng dàjiā jiéyuē shǐyòng sùliàodài, huòzhě gòuwù shí zì bèi gòuwùdài, shènzhì jùjué shǐyòng sùliàodài.", "Har birimiz atrof-muhitni himoya qilishga mas'ulmiz, shuning uchun plastik paketni tejab ishlating yoki xarid payti o'z xaltangizni olib boring, hatto plastik paketdan voz keching.", "Каждый из нас отвечает за защиту среды, поэтому экономьте пакеты, берите свою сумку или даже отказывайтесь от пластиковых пакетов.", "Ҳар яки мо барои ҳифзи муҳит масъулем, бинобар ин халтаи пластикиро сарфа кунед, ҳангоми харид халтаи худатонро баред ё ҳатто онро рад кунед."),
                    _line("旁白", "虽然这是一件很小的事，但这样做可以减少塑料袋的使用数量，对环境保护有很大的作用。", "Suīrán zhè shì yí jiàn hěn xiǎo de shì, dàn zhèyàng zuò kěyǐ jiǎnshǎo sùliàodài de shǐyòng shùliàng, duì huánjìng bǎohù yǒu hěn dà de zuòyòng.", "Bu kichik ish bo'lsa ham, shunday qilish plastik paket miqdorini kamaytiradi va ekologiya himoyasiga katta foyda beradi.", "Хотя это мелочь, так можно сократить количество пакетов и сильно помочь защите среды.", "Гарчанде ин кори хурд аст, чунин кардан миқдори халтаҳоро кам мекунад ва ба ҳифзи муҳит бисёр ёрӣ медиҳад."),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Kundalik ekologik odatlar haqida matn",
                "scene_ru": "Текст о повседневных экологичных привычках",
                "scene_tj": "Матн дар бораи одатҳои ҳаррӯзаи экологӣ",
                "word_nos": [28, 29, 30, 31, 32],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "保护地球环境，并不是一件离我们很远、很难做到的事情。实际上，我们只需注意一下身边的小事就可以。", "Bǎohù dìqiú huánjìng, bìng bú shì yí jiàn lí wǒmen hěn yuǎn, hěn nán zuòdào de shìqing. Shíjì shang, wǒmen zhǐ xū zhùyì yíxià shēnbiān de xiǎo shì jiù kěyǐ.", "Yer muhitini himoya qilish bizdan uzoq yoki bajarish qiyin ish emas. Aslida yonimizdagi kichik ishlarga e'tibor bersak kifoya.", "Защита Земли - не что-то далёкое и трудное. На самом деле достаточно обращать внимание на мелочи рядом с нами.", "Ҳифзи муҳити Замин кори дур ё душвор нест. Дар асл ба корҳои хурди гирду атроф диққат диҳем, кофист."),
                    _line("旁白", "例如，夏天把空调的温度开得高一些，出门时记得关空调和电脑，这样可以节约用电。", "Lìrú, xiàtiān bǎ kōngtiáo de wēndù kāi de gāo yìxiē, chūmén shí jìde guān kōngtiáo hé diànnǎo, zhèyàng kěyǐ jiéyuē yòng diàn.", "Masalan, yozda konditsioner haroratini biroz balandroq qo'yish, chiqishda konditsioner va kompyuterni o'chirish elektrni tejaydi.", "Например, летом ставить кондиционер чуть выше и выключать кондиционер и компьютер при выходе - это экономит электричество.", "Масалан, тобистон ҳарорати кондитсионерро каме баландтар гузоштан ва ҳангоми баромадан онро бо компютер хомӯш кардан барқро сарфа мекунад."),
                    _line("旁白", "少开车，多骑车或者乘坐地铁和公共汽车，这样能降低空气污染；还有养成把垃圾丢进垃圾桶的习惯什么的。", "Shǎo kāi chē, duō qí chē huòzhě chéngzuò dìtiě hé gōnggòng qìchē, zhèyàng néng jiàngdī kōngqì wūrǎn; hái yǒu yǎngchéng bǎ lājī diūjìn lājītǒng de xíguàn shénme de.", "Kamroq mashina haydab, ko'proq velosiped, metro yoki avtobusdan foydalanish havo ifloslanishini kamaytiradi; yana axlatni axlat qutisiga tashlash odatini shakllantirish kerak.", "Меньше ездить на машине, чаще на велосипеде, метро или автобусе - это снижает загрязнение воздуха; ещё нужно привыкнуть бросать мусор в урну.", "Камтар мошин рондан, бештар дучарха, метро ё автобус савор шудан ифлосшавии ҳаворо кам мекунад; боз одати ба қуттии партов партофтани партовро бояд дошт."),
                    _line("旁白", "这些是我们每个人都能够做到的小事，但却有实实在在的效果。地球是我们共同的家，只有大家共同努力，减少污染，保护环境，才能使我们的家变得更美丽。", "Zhèxiē shì wǒmen měi ge rén dōu nénggòu zuòdào de xiǎo shì, dàn què yǒu shíshízàizài de xiàoguǒ. Dìqiú shì wǒmen gòngtóng de jiā, zhǐyǒu dàjiā gòngtóng nǔlì, jiǎnshǎo wūrǎn, bǎohù huánjìng, cái néng shǐ wǒmen de jiā biàn de gèng měilì.", "Bular har birimiz qila oladigan kichik ishlar, lekin haqiqiy ta'siri bor. Yer bizning umumiy uyimiz; faqat hammamiz birga harakat qilib, ifloslanishni kamaytirsak va muhitni himoya qilsak, uyimiz yanada go'zal bo'ladi.", "Это мелочи, которые может сделать каждый, но у них реальный эффект. Земля - наш общий дом; только общими усилиями, снижая загрязнение и защищая среду, мы сделаем его красивее.", "Инҳо корҳои хурде ҳастанд, ки ҳар яки мо карда метавонем, аммо таъсири воқеӣ доранд. Замин хонаи умумии мост; танҳо бо кӯшиши якҷоя, кам кардани ифлосӣ ва ҳифзи муҳит хонаамон зеботар мешавад."),
                ],
            },
        ],
    },
    15: {
        "title": "教育孩子的艺术",
        "goal": {
            "uz": "bolani tarbiyalash, odat, vaqtni boshqarish, maqtash va mos usul tanlash haqida gapirish; 想起来, 弄, 千万, 来 va 左右 grammatikalarini ishlatish",
            "ru": "говорить о воспитании детей, привычках, управлении временем, похвале и выборе метода; использовать 想起来, 弄, 千万, 来 и 左右",
            "tj": "дар бораи тарбияи кӯдак, одат, идораи вақт, таъриф ва интихоби усул гуфтугӯ кардан; истифодаи 想起来, 弄, 千万, 来 ва 左右",
        },
        "intro_text": {
            "uz": "Bu darsda ota-ona roli, bolaga vaqtni boshqarishni o'rgatish, maqtash san'ati va turli xarakterdagi bolalarga mos tarbiya usullarini o'rganasiz.",
            "ru": "В этом уроке вы изучите роль родителей, обучение ребёнка управлению временем, искусство похвалы и методы воспитания детей с разным характером.",
            "tj": "Дар ин дарс нақши падару модар, омӯзонидани идораи вақт, санъати таъриф ва усулҳои тарбияи кӯдакони гуногунхислатро меомӯзед.",
        },
        "vocabulary": [
            _word(1, "弹钢琴", "tán gāngqín", "v.", "pianino chalmoq", "играть на пианино", "пианино навохтан"),
            _word(2, "棒", "bàng", "adj.", "zo'r, ajoyib", "отличный, замечательный", "олӣ, зӯр"),
            _word(3, "孙子", "sūnzi", "n.", "nabira o'g'il", "внук", "набераи писар"),
            _word(4, "寒假", "hánjià", "n.", "qishki ta'til", "зимние каникулы", "таътили зимистона"),
            _word(5, "父亲", "fùqin", "n.", "ota", "отец", "падар"),
            _word(6, "闹钟", "nàozhōng", "n.", "budilnik", "будильник", "соати зангдор"),
            _word(7, "响", "xiǎng", "v.", "jiringlamoq, ovoz chiqarmoq", "звенеть, звучать", "садо додан"),
            _word(8, "醒", "xǐng", "v.", "uyg'onmoq", "просыпаться", "бедор шудан"),
            _word(9, "赶", "gǎn", "v.", "shoshilmoq, ulgurishga urunmoq", "спешить, торопиться", "шитоб кардан"),
            _word(10, "厕所", "cèsuǒ", "n.", "hojatxona", "туалет", "ҳоҷатхона"),
            _word(11, "批评", "pīpíng", "v.", "tanqid qilmoq", "критиковать", "танқид кардан"),
            _word(12, "弄", "nòng", "v.", "qilmoq, yasamoq", "делать, приводить", "кардан, ба ҳол овардан"),
            _word(13, "管理", "guǎnlǐ", "v.", "boshqarmoq", "управлять", "идора кардан"),
            _word(14, "打针", "dǎ zhēn", "v.", "ukol qilmoq/olmoq", "делать укол", "сӯзандору задан/гирифтан"),
            _word(15, "护士", "hùshi", "n.", "hamshira", "медсестра", "ҳамшира"),
            _word(16, "表扬", "biǎoyáng", "v.", "maqtab qo'ymoq", "хвалить", "таъриф кардан"),
            _word(17, "千万", "qiānwàn", "adv.", "albatta, zinhor", "обязательно, ни в коем случае", "ҳатман, зинҳор"),
            _word(18, "怀疑", "huáiyí", "v.", "shubhalanmoq", "сомневаться", "шубҳа кардан"),
            _word(19, "故意", "gùyì", "adv.", "ataylab", "намеренно", "қасдан"),
            _word(20, "敲", "qiāo", "v.", "taqillatmoq, urmoq", "стучать, ударять", "тақ-тақ кардан, задан"),
            _word(21, "整理", "zhěnglǐ", "v.", "tartibga solmoq", "приводить в порядок", "ба тартиб овардан"),
            _word(22, "合适", "héshì", "adj.", "mos, to'g'ri", "подходящий", "мувофиқ"),
            _word(23, "骗", "piàn", "v.", "aldamoq", "обманывать", "фиреб додан"),
            _word(24, "儿童", "értóng", "n.", "bolalar", "дети", "кӯдакон"),
            _word(25, "假", "jiǎ", "adj.", "soxta, yolg'on", "ложный, фальшивый", "қалбакӣ, дурӯғ"),
            _word(26, "左右", "zuǒyòu", "n.", "atrofida, taxminan", "примерно, около", "тақрибан"),
            _word(27, "懒", "lǎn", "adj.", "dangasa", "ленивый", "танбал"),
            _word(28, "笨", "bèn", "adj.", "befahm, ahmoq", "глупый", "нодон"),
            _word(29, "粗心", "cūxīn", "adj.", "beparvo", "невнимательный", "бепарво"),
            _word(30, "骄傲", "jiāo'ào", "adj.", "kibrli, mag'rur", "высокомерный", "мағрур, худписанд"),
            _word(31, "害羞", "hàixiū", "v.", "uyalmoq, tortinmoq", "стесняться", "шарм доштан"),
        ],
        "grammar": [
            _grammar(1, "想起来", "esga tushmoq", "вспомнить", "ба ёд омадан", "想 dan keyin kelib, xotiradan odam yoki voqeani topishni bildiradi.", "После 想 означает вспомнить человека или событие.", "Баъд аз 想 омаданаш ба ёд овардани одам ё воқеаро мефаҳмонад.", "我想起来了，这孩子又聪明又可爱。", "Wǒ xiǎng qilai le, zhè háizi yòu cōngming yòu kě'ài.", "Esimga tushdi, bu bola ham aqlli, ham yoqimtoy.", "Я вспомнила, этот ребёнок и умный, и милый.", "Ба ёдам омад, ин кӯдак ҳам доно, ҳам ширин аст."),
            _grammar(2, "弄", "qilmoq, holatga keltirmoq", "делать, приводить к состоянию", "кардан, ба ҳолат овардан", "Og'zaki tilda ko'p fe'llar o'rnida kelib, natijaviy holatni bildiradi.", "В разговорной речи заменяет разные глаголы и показывает результат.", "Дар гуфтори рӯзмарра ба ҷои феълҳои гуногун омада, натиҷаро нишон медиҳад.", "每天因为这些小事批评她，弄得我俩心情都不好。", "Měi tiān yīnwèi zhèxiē xiǎo shì pīpíng tā, nòng de wǒ liǎ xīnqíng dōu bù hǎo.", "Har kuni shu mayda ishlar uchun uni tanqid qilib, ikkalamizning kayfiyatimiz ham yomon bo'ladi.", "Каждый день критикую её из-за мелочей, и настроение у нас обеих портится.", "Ҳар рӯз барои ин корҳои хурд танқид мекунам ва кайфияти ҳардуямон бад мешавад."),
            _grammar(3, "千万", "albatta; zinhor", "обязательно; ни в коем случае", "ҳатман; зинҳор", "Kuchli eslatma beradi, ko'pincha 不要/别 bilan inkor shaklida ishlatiladi.", "Выражает сильное предупреждение, часто с отрицанием 不要/别.", "Огоҳии қавӣ медиҳад, аксаран бо 不要/别 дар шакли инкор меояд.", "表扬千万不要太多。", "Biǎoyáng qiānwàn búyào tài duō.", "Maqtash zinhor haddan tashqari ko'p bo'lmasin.", "Хвалить ни в коем случае нельзя слишком много.", "Таъриф кардан зинҳор аз ҳад зиёд набошад."),
            _grammar(4, "来", "biror ishni bajarish uchun", "чтобы сделать", "барои иҷро кардан", "Boshqa fe'l oldida kelib, bajariladigan ish yoki maqsadni ko'rsatadi.", "Перед другим глаголом показывает действие или цель.", "Пеш аз феъли дигар омада, амал ё мақсадро нишон медиҳад.", "有的孩子会通过哭、扔东西或者故意敲打来引起父母的注意。", "Yǒude háizi huì tōngguò kū, rēng dōngxi huòzhě gùyì qiāodǎ lái yǐnqǐ fùmǔ de zhùyì.", "Ba'zi bolalar ota-onaning e'tiborini tortish uchun yig'laydi, narsa tashlaydi yoki ataylab taqillatadi.", "Некоторые дети плачут, бросают вещи или намеренно стучат, чтобы привлечь внимание родителей.", "Баъзе кӯдакон барои ҷалби диққати падару модар гиря мекунанд, чиз мепартоянд ё қасдан тақ-тақ мекунанд."),
            _grammar(5, "左右", "taxminan, atrofida", "примерно, около", "тақрибан", "Son yoki miqdordan keyin kelib, biroz ko'p yoki kamligini bildiradi.", "После числа показывает приблизительное количество.", "Пас аз шумора омада, тахминӣ будани миқдорро мефаҳмонад.", "七岁左右的儿童普遍好动，坐不住。", "Qī suì zuǒyòu de értóng pǔbiàn hào dòng, zuò bu zhù.", "Taxminan yetti yoshdagi bolalar odatda juda harakatchan, joyida o'tirolmaydi.", "Дети примерно семи лет обычно очень подвижны и не могут усидеть.", "Кӯдакони тақрибан ҳафтсола одатан серҳаракатанд ва нишаста наметавонанд."),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "Li o'qituvchi Wang Jingga yaxshi odat tarbiyasi haqida gapiradi",
                "scene_ru": "Учитель Ли говорит Ван Цзин о воспитании хороших привычек",
                "scene_tj": "Муаллим Ли ба Ван Ҷинг дар бораи тарбияи одатҳои хуб мегӯяд",
                "word_nos": [1, 2, 3, 4, 5],
                "grammar_nos": [1],
                "dialogue": [
                    _line("王静", "那个一边弹钢琴一边唱歌的男孩子是谁？表演得真棒！", "Nàge yìbiān tán gāngqín yìbiān chàng gē de nán háizi shì shéi? Biǎoyǎn de zhēn bàng!", "Pianino chalib qo'shiq aytayotgan o'g'il bola kim? Juda zo'r ijro qilyapti!", "Кто тот мальчик, который играет на пианино и поёт? Выступает отлично!", "Он писарбачае, ки ҳам пианино менавозаду ҳам месарояд, кист? Бисёр олӣ иҷро мекунад!"),
                    _line("李老师", "是我孙子。去年寒假前的新年晚会他也表演过一次。", "Shì wǒ sūnzi. Qùnián hánjià qián de xīnnián wǎnhuì tā yě biǎoyǎn guo yí cì.", "Bu mening nabiram. O'tgan yili qishki ta'til oldidagi Yangi yil kechasida ham bir marta chiqish qilgan.", "Это мой внук. На новогоднем вечере перед зимними каникулами в прошлом году он тоже выступал.", "Ин набераи ман аст. Соли гузашта пеш аз таътили зимистона дар шабнишинии Соли нав ҳам баромад карда буд."),
                    _line("王静", "我想起来了，这孩子又聪明又可爱，你们教育得真好！", "Wǒ xiǎng qilai le, zhè háizi yòu cōngming yòu kě'ài, nǐmen jiàoyù de zhēn hǎo!", "Esimga tushdi, bu bola ham aqlli, ham yoqimtoy. Sizlar juda yaxshi tarbiya beribsizlar!", "Я вспомнила, этот ребёнок и умный, и милый. Вы отлично его воспитали!", "Ба ёдам омад, ин кӯдак ҳам доно, ҳам ширин аст. Шумо хеле хуб тарбия кардаед!"),
                    _line("李老师", "是他父母教育得好。父母是孩子最重要的老师。他父母不仅教他知识，而且还花了很长时间帮助他养成了非常好的习惯，现在他每天都自己练习弹钢琴。", "Shì tā fùmǔ jiàoyù de hǎo. Fùmǔ shì háizi zuì zhòngyào de lǎoshī. Tā fùmǔ bùjǐn jiāo tā zhīshi, érqiě hái huā le hěn cháng shíjiān bāngzhù tā yǎngchéngle fēicháng hǎo de xíguàn, xiànzài tā měi tiān dōu zìjǐ liànxí tán gāngqín.", "Uni ota-onasi yaxshi tarbiya qilgan. Ota-ona bola uchun eng muhim o'qituvchi. Ular nafaqat bilim bergan, balki uzoq vaqt yaxshi odat shakllantirishga yordam bergan, hozir u har kuni o'zi pianino mashq qiladi.", "Это его родители хорошо воспитали. Родители - самые важные учителя ребёнка. Они не только учат знаниям, но и долго помогали ему выработать хорошие привычки; теперь он сам каждый день занимается пианино.", "Падару модараш хуб тарбия кардаанд. Падару модар муҳимтарин муаллими кӯдаканд. Онҳо на танҳо дониш додаанд, балки муддати дароз барои одати хуб ёфтан ёрӣ додаанд; ҳоло ӯ ҳар рӯз худаш пианино машқ мекунад."),
                    _line("王静", "让孩子养成一个好习惯实在太重要了，看来我得向他父母好好儿学习。", "Ràng háizi yǎngchéng yí ge hǎo xíguàn shízài tài zhòngyào le, kànlái wǒ děi xiàng tā fùmǔ hǎohāor xuéxí.", "Bolada yaxshi odat shakllantirish juda muhim ekan, men uning ota-onasidan yaxshilab o'rganishim kerak.", "Помочь ребёнку выработать хорошую привычку очень важно. Похоже, мне стоит поучиться у его родителей.", "Ба кӯдак одати хуб додан хеле муҳим будааст, бояд аз падару модараш хуб омӯзам."),
                    _line("李老师", "对。如果希望有一个优秀的孩子，你就要先成为一位优秀的父亲或者母亲。", "Duì. Rúguǒ xīwàng yǒu yí ge yōuxiù de háizi, nǐ jiù yào xiān chéngwéi yí wèi yōuxiù de fùqin huòzhě mǔqin.", "To'g'ri. Agar a'lo farzanding bo'lishini istasang, avval o'zing a'lo ota yoki ona bo'lishing kerak.", "Верно. Если хочешь иметь выдающегося ребёнка, сначала сам стань выдающимся отцом или матерью.", "Дуруст. Агар фарзанди аъло хоҳӣ, аввал худат падар ё модари аъло шав."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "Wang Jing Sun Yuega bolaga vaqtni boshqarishni o'rgatishni maslahat beradi",
                "scene_ru": "Ван Цзин советует Сунь Юэ учить ребёнка управлять временем",
                "scene_tj": "Ван Ҷинг ба Сун Юэ маслиҳат медиҳад, ки ба кӯдак идораи вақтро омӯзонад",
                "word_nos": [6, 7, 8, 9, 10, 11, 12, 13],
                "grammar_nos": [2],
                "dialogue": [
                    _line("王静", "看你脸色不太好，是不是昨晚没休息好？", "Kàn nǐ liǎnsè bú tài hǎo, shì bu shì zuówǎn méi xiūxi hǎo?", "Ranging yaxshi emas ko'rinyapti, kecha yaxshi dam olmadingmi?", "У тебя неважный вид. Ты вчера плохо отдохнула?", "Рӯят хуб нест, шаби гузашта хуб истироҳат накардӣ?"),
                    _line("孙月", "别提了。我女儿昨晚做作业又做到11点。", "Bié tí le. Wǒ nǚ'ér zuówǎn zuò zuòyè yòu zuòdào shíyī diǎn.", "Gapirma qo'yaqol. Qizim kecha yana uy vazifasini 11 gacha qildi.", "Не говори. Дочь вчера опять делала домашку до 11 часов.", "Нагӯй беҳтараш. Духтарам шаби гузашта боз то соати 11 вазифа кард."),
                    _line("王静", "睡觉太晚对孩子的身体没有好处。最近孩子作业是不是太多了？", "Shuì jiào tài wǎn duì háizi de shēntǐ méiyǒu hǎochu. Zuìjìn háizi zuòyè shì bu shì tài duō le?", "Juda kech yotish bola tanasiga foyda qilmaydi. Oxirgi payt uy vazifasi juda ko'pmi?", "Поздно ложиться вредно для ребёнка. В последнее время слишком много заданий?", "Хеле дер хобидан ба саломатии кӯдак хуб нест. Охирҳо вазифааш зиёд шудааст?"),
                    _line("孙月", "主要是她做事情比较慢，比如早上闹钟响了她不醒，我赶时间送她上学，她又急着上厕所。每天因为这些小事批评她，弄得我俩心情都不好。", "Zhǔyào shì tā zuò shìqing bǐjiào màn, bǐrú zǎoshang nàozhōng xiǎng le tā bù xǐng, wǒ gǎn shíjiān sòng tā shàng xué, tā yòu jízhe shàng cèsuǒ. Měi tiān yīnwèi zhèxiē xiǎo shì pīpíng tā, nòng de wǒ liǎ xīnqíng dōu bù hǎo.", "Asosiysi u ishni sekin qiladi: masalan, ertalab budilnik jiringlasa ham uyg'onmaydi, men uni maktabga olib borishga shoshilaman, u esa hojatxonaga shoshadi. Har kuni shu mayda narsalar uchun tanqid qilib, ikkalamizning kayfiyatimiz yomon bo'ladi.", "Главное, она всё делает медленно: утром будильник звонит, а она не просыпается, я спешу отвезти её в школу, а она ещё срочно хочет в туалет. Каждый день критикую её из-за мелочей, и настроение у нас обеих плохое.", "Асосаш, ӯ корҳоро суст мекунад: саҳар соати зангдор садо медиҳад, вале бедор намешавад, ман барои бурданаш ба мактаб мешитобам, ӯ бошад ба ҳоҷатхона мешитобад. Ҳар рӯз барои ин чизҳои хурд танқид мекунам ва кайфияти ҳардуямон бад мешавад."),
                    _line("王静", "孩子做事慢，往往是因为他们不会安排自己的时间。你应该让孩子学会管理时间。", "Háizi zuò shì màn, wǎngwǎng shì yīnwèi tāmen bú huì ānpái zìjǐ de shíjiān. Nǐ yīnggāi ràng háizi xuéhuì guǎnlǐ shíjiān.", "Bola ishni sekin qilsa, ko'pincha o'z vaqtini rejalay olmasligidan bo'ladi. Sen bolaga vaqtni boshqarishni o'rgatishing kerak.", "Если ребёнок делает всё медленно, часто это потому, что он не умеет распределять время. Тебе нужно научить её управлять временем.", "Агар кӯдак корро суст кунад, аксаран сабабаш идора карда натавонистани вақти худ аст. Ту бояд ба ӯ идораи вақтро омӯзонӣ."),
                    _line("孙月", "看来还是我的教育方法有问题。平时看她做事情慢，总想替她做，以后得让她学会安排时间，自己的事情自己做。", "Kànlái háishi wǒ de jiàoyù fāngfǎ yǒu wèntí. Píngshí kàn tā zuò shìqing màn, zǒng xiǎng tì tā zuò, yǐhòu děi ràng tā xuéhuì ānpái shíjiān, zìjǐ de shìqing zìjǐ zuò.", "Demak, mening tarbiya usulimda muammo bor ekan. Odatda u sekin qilsa, uning o'rniga qilishni istayman. Keyin unga vaqtni rejalashni, o'z ishini o'zi qilishni o'rgatishim kerak.", "Похоже, проблема всё-таки в моём методе воспитания. Обычно, когда она медлит, мне хочется сделать за неё. Теперь нужно дать ей научиться планировать время и делать свои дела самой.", "Маълум мешавад усули тарбияам мушкил дорад. Одатан вақте суст мекунад, мехоҳам ба ҷояш кунам. Минбаъд бояд ба ӯ банақшагирии вақт ва кори худро худ карданро омӯзонам."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "Wang Jing va Sun Yue bolani maqtash usulini muhokama qiladi",
                "scene_ru": "Ван Цзин и Сунь Юэ обсуждают, как хвалить ребёнка",
                "scene_tj": "Ван Ҷинг ва Сун Юэ тарзи таъриф кардани кӯдакро муҳокима мекунанд",
                "word_nos": [14, 15, 16, 17, 18],
                "grammar_nos": [3],
                "dialogue": [
                    _line("王静", "明天又要带我儿子去医院打针，想想我就头疼。他就怕打针，每次打针都哭得特别厉害。", "Míngtiān yòu yào dài wǒ érzi qù yīyuàn dǎ zhēn, xiǎngxiang wǒ jiù tóu téng. Tā jiù pà dǎ zhēn, měi cì dǎ zhēn dōu kū de tèbié lìhai.", "Ertaga o'g'limni yana kasalxonaga ukolga olib borishim kerak, o'ylasam boshim og'riydi. U ukoldan juda qo'rqadi, har safar qattiq yig'laydi.", "Завтра опять вести сына в больницу на укол, от одной мысли голова болит. Он боится уколов и каждый раз сильно плачет.", "Пагоҳ боз писарамро ба беморхона барои сӯзандору мебарам, фикр кунам сарам дард мекунад. Ӯ аз сӯзандору метарсад ва ҳар дафъа сахт гиря мекунад."),
                    _line("孙月", "记得我女儿小时候，带她去医院打针，刚开始，她害怕得要哭。我就小声地和护士说我女儿很勇敢，一点儿也不怕打针，女儿听了以后马上就不哭了。", "Jìde wǒ nǚ'ér xiǎoshíhou, dài tā qù yīyuàn dǎ zhēn, gāng kāishǐ, tā hàipà de yào kū. Wǒ jiù xiǎoshēng de hé hùshi shuō wǒ nǚ'ér hěn yǒnggǎn, yìdiǎnr yě bú pà dǎ zhēn, nǚ'ér tīng le yǐhòu mǎshàng jiù bù kū le.", "Qizim kichikligida uni ukolga olib borganim esimda. Avvaliga qo'rqib yig'lamoqchi bo'lgan. Men hamshiraga sekingina qizim juda jasur, ukoldan umuman qo'rqmaydi, dedim. Qizim eshitgach darhol yig'lamay qo'ydi.", "Помню, когда дочь была маленькой и я вела её на укол, сначала она боялась и хотела плакать. Я тихо сказала медсестре, что дочь очень смелая и совсем не боится уколов. Услышав это, она сразу перестала плакать.", "Дар ёдам ҳаст, вақте духтарам хурд буд ва ба сӯзандору бурдам, аввал метарсид ва мехост гиря кунад. Ман ба ҳамшира оҳиста гуфтам, ки духтарам бисёр ҷасур аст ва аз сӯзандору намеҳаросад. Ӯ шунида, фавран дигар гиря накард."),
                    _line("王静", "原来鼓励和表扬对小孩儿挺有用的，下次我也试试。", "Yuánlái gǔlì hé biǎoyáng duì xiǎoháir tǐng yǒuyòng de, xià cì wǒ yě shìshi.", "Demak, rag'bat va maqtov bolalarga ancha foydali ekan, keyingi safar men ham sinab ko'raman.", "Оказывается, поощрение и похвала довольно полезны для детей, в следующий раз тоже попробую.", "Маълум мешавад, ҳавасмандӣ ва таъриф барои кӯдак хеле фоида доранд, дафъаи дигар ман ҳам месанҷам."),
                    _line("孙月", "不过表扬也是一门艺术，表扬千万不要太多，过多的表扬可能会给孩子带来压力。不仅起不到鼓励的作用，还可能让孩子怀疑自己的能力，变得没有信心。", "Búguò biǎoyáng yě shì yì mén yìshù, biǎoyáng qiānwàn búyào tài duō, guòduō de biǎoyáng kěnéng huì gěi háizi dàilái yālì. Bùjǐn qǐ bu dào gǔlì de zuòyòng, hái kěnéng ràng háizi huáiyí zìjǐ de nénglì, biàn de méiyǒu xìnxīn.", "Lekin maqtash ham san'at. Zinhor haddan tashqari ko'p maqtamaslik kerak, ortiqcha maqtov bolaga bosim berishi mumkin. Nafaqat rag'bat bermaydi, balki bola o'z qobiliyatidan shubhalanib, ishonchini yo'qotishi mumkin.", "Но похвала - тоже искусство. Нельзя хвалить слишком много: чрезмерная похвала может давить на ребёнка. Она не только не поощрит, но и заставит сомневаться в своих способностях и потерять уверенность.", "Аммо таъриф ҳам санъат аст. Зинҳор аз ҳад зиёд таъриф кардан лозим нест: таърифи зиёд ба кӯдак фишор меорад. На танҳо ҳавасманд намекунад, балки метавонад ӯро ба қобилияти худ шубҳадор ва беэътимод кунад."),
                    _line("王静", "那怎么表扬孩子才会更有效果呢？", "Nà zěnme biǎoyáng háizi cái huì gèng yǒu xiàoguǒ ne?", "Unda bolani qanday maqtasa samaraliroq bo'ladi?", "Тогда как хвалить ребёнка эффективнее?", "Пас кӯдакро чӣ гуна таъриф кунем, ки таъсирноктар бошад?"),
                    _line("孙月", "我认为表扬要及时，而且表扬不仅仅要看结果，更要看过程，这样才能鼓励他的积极性，让他变得勇敢，不怕困难。", "Wǒ rènwéi biǎoyáng yào jíshí, érqiě biǎoyáng bù jǐnjǐn yào kàn jiéguǒ, gèng yào kàn guòchéng, zhèyàng cái néng gǔlì tā de jījíxìng, ràng tā biàn de yǒnggǎn, bú pà kùnnan.", "Menimcha, maqtov o'z vaqtida bo'lishi kerak; faqat natijaga emas, jarayonga ham qarash kerak. Shunda uning faolligi rag'batlanadi, jasur bo'ladi va qiyinchilikdan qo'rqmaydi.", "Думаю, хвалить нужно вовремя, смотреть не только на результат, но и на процесс. Так можно поощрить активность, сделать ребёнка смелее и не боящимся трудностей.", "Ба фикрам, таъриф бояд сари вақт бошад; на танҳо натиҷа, балки равандро ҳам дидан лозим. Ҳамин тавр фаъолнокӣ ҳавасманд мешавад, кӯдак ҷасур ва аз мушкил натарс мешавад."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Bola e'tibor talab qilganda ota-onaning munosabati haqida matn",
                "scene_ru": "Текст о реакции родителей, когда ребёнок требует внимания",
                "scene_tj": "Матн дар бораи муносибати падару модар вақте кӯдак диққат мехоҳад",
                "word_nos": [19, 20, 21, 22, 23, 24, 25],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "有的孩子在得不到自己想要的东西的时候，会通过哭、扔东西或者故意敲打来引起父母的注意。", "Yǒude háizi zài dé bu dào zìjǐ xiǎng yào de dōngxi de shíhou, huì tōngguò kū, rēng dōngxi huòzhě gùyì qiāodǎ lái yǐnqǐ fùmǔ de zhùyì.", "Ba'zi bolalar xohlagan narsasini ololmaganda, yig'lash, narsa tashlash yoki ataylab taqillatish orqali ota-onaning e'tiborini tortadi.", "Некоторые дети, не получив желаемого, привлекают внимание родителей плачем, бросанием вещей или намеренным стуком.", "Баъзе кӯдакон вақте чизи хостаашонро намегиранд, бо гиря, чизпартоӣ ё қасдан тақ-тақ кардан диққати падару модарро ҷалб мекунанд."),
                    _line("旁白", "在这种情况下，建议父母先不要生气，应该停下手中的事情，陪孩子整理整理东西，和他们聊聊天儿，弄清楚他们的问题。", "Zài zhè zhǒng qíngkuàng xià, jiànyì fùmǔ xiān búyào shēng qì, yīnggāi tíngxià shǒu zhōng de shìqing, péi háizi zhěnglǐ zhěnglǐ dōngxi, hé tāmen liáoliáo tiānr, nòng qīngchu tāmen de wèntí.", "Bunday holatda ota-ona avval jahli chiqmasin, qo'lidagi ishni to'xtatib, bola bilan narsalarni tartiblasin, gaplashsin va muammoni aniqlasin.", "В такой ситуации родителям лучше сначала не сердиться, отложить дела, помочь ребёнку прибраться, поговорить и выяснить проблему.", "Дар чунин ҳолат падару модар аввал хашмгин нашаванд, кори дасташонро монда, бо кӯдак чизҳоро тартиб диҳанд, суҳбат кунанд ва мушкилро равшан кунанд."),
                    _line("旁白", "父母的关心，可以让孩子心情愉快起来。教育孩子应该选择合适的教育方法，最好不要为了解决问题而骗孩子。", "Fùmǔ de guānxīn, kěyǐ ràng háizi xīnqíng yúkuài qǐlái. Jiàoyù háizi yīnggāi xuǎnzé héshì de jiàoyù fāngfǎ, zuì hǎo búyào wèile jiějué wèntí ér piàn háizi.", "Ota-onaning e'tibori bolani xursand qiladi. Bolani tarbiyalashda mos usul tanlash kerak, muammoni hal qilish uchun bolani aldamagan yaxshi.", "Забота родителей может улучшить настроение ребёнка. В воспитании нужно выбирать подходящий метод и лучше не обманывать ребёнка ради решения проблемы.", "Диққати падару модар кайфияти кӯдакро хуб мекунад. Дар тарбия усули мувофиқ интихоб кардан лозим, барои ҳалли мушкил кӯдакро фиреб надодан беҳтар аст."),
                    _line("旁白", "这是因为儿童缺少判断能力，看到父母骗人，他们也会学着说假话。", "Zhè shì yīnwèi értóng quēshǎo pànduàn nénglì, kàndào fùmǔ piàn rén, tāmen yě huì xuézhe shuō jiǎhuà.", "Chunki bolalarda hukm qilish qobiliyati yetarli emas; ota-onasi aldaganini ko'rsa, ular ham yolg'on gapirishni o'rganadi.", "Потому что детям не хватает способности судить; увидев, что родители обманывают, они тоже учатся говорить неправду.", "Зеро кӯдакон қобилияти доварии кофӣ надоранд; агар фиреб додани падару модарро бинанд, онҳо ҳам дурӯғ гуфтанро меомӯзанд."),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "Turli xarakterdagi bolalarga mos tarbiya haqida matn",
                "scene_ru": "Текст о подходящих методах воспитания детей с разным характером",
                "scene_tj": "Матн дар бораи усулҳои мувофиқи тарбияи кӯдакони гуногунхислат",
                "word_nos": [26, 27, 28, 29, 30, 31],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "七岁左右的儿童普遍好动，坐不住，所以老师在教这个年龄段的孩子时，一定要想办法引起他们的兴趣。", "Qī suì zuǒyòu de értóng pǔbiàn hào dòng, zuò bu zhù, suǒyǐ lǎoshī zài jiāo zhège niánlíng duàn de háizi shí, yídìng yào xiǎng bànfǎ yǐnqǐ tāmen de xìngqù.", "Taxminan yetti yoshdagi bolalar odatda harakatchan bo'lib, joyida o'tirolmaydi, shuning uchun o'qituvchi bu yoshdagi bolalarni o'qitganda ularning qiziqishini uyg'otishi kerak.", "Дети примерно семи лет обычно подвижны и не могут усидеть, поэтому учителю нужно искать способ вызвать их интерес.", "Кӯдакони тақрибан ҳафтсола одатан серҳаракатанд ва нишаста наметавонанд, бинобар ин муаллим бояд шавқи онҳоро бедор кунад."),
                    _line("旁白", "只有让他们觉得你教的内容有趣，他们才会愿意努力学习。", "Zhǐyǒu ràng tāmen juéde nǐ jiāo de nèiróng yǒuqù, tāmen cái huì yuànyì nǔlì xuéxí.", "Faqat o'qitayotgan narsang qiziq tuyulsagina ular astoydil o'qishga rozi bo'ladi.", "Только если материал покажется им интересным, они захотят старательно учиться.", "Танҳо агар маводи таълимӣ барои онҳо ҷолиб бошад, онҳо бо хоҳиш мехонанд."),
                    _line("旁白", "当孩子不明白时，应该多鼓励他，不要用“懒”“笨”“粗心”这种词批评他，这样对他们的正常发展不好。", "Dāng háizi bù míngbai shí, yīnggāi duō gǔlì tā, búyào yòng “lǎn” “bèn” “cūxīn” zhè zhǒng cí pīpíng tā, zhèyàng duì tāmen de zhèngcháng fāzhǎn bù hǎo.", "Bola tushunmaganida uni ko'proq rag'batlantirish kerak; \"dangasa\", \"befahm\", \"beparvo\" kabi so'zlar bilan tanqid qilmaslik kerak, bu normal rivojlanishga yomon.", "Когда ребёнок не понимает, его нужно больше поощрять, а не критиковать словами «ленивый», «глупый», «невнимательный», это вредно для нормального развития.", "Вақте кӯдак намефаҳмад, ӯро бештар рӯҳбаланд кардан лозим; бо калимаҳои «танбал», «нодон», «бепарво» танқид кардан ба рушди муқаррарӣ зарар дорад."),
                    _line("旁白", "而且，对不同性格的孩子要使用不同的教育方法。如果孩子比较骄傲，应该让他明白还有很多知识需要学习；要是孩子性格有些害羞，就要经常鼓励他说出自己的看法，这样才能让每一个孩子都健康地发展。", "Érqiě, duì bù tóng xìnggé de háizi yào shǐyòng bù tóng de jiàoyù fāngfǎ. Rúguǒ háizi bǐjiào jiāo'ào, yīnggāi ràng tā míngbai hái yǒu hěn duō zhīshi xūyào xuéxí; yàoshi háizi xìnggé yǒuxiē hàixiū, jiù yào jīngcháng gǔlì tā shuōchū zìjǐ de kànfǎ, zhèyàng cái néng ràng měi yí ge háizi dōu jiànkāng de fāzhǎn.", "Bundan tashqari, har xil xarakterdagi bolaga har xil tarbiya usuli kerak. Bola kibrliroq bo'lsa, unga hali ko'p bilim o'rganishi kerakligini tushuntirish kerak; tortinchoq bo'lsa, o'z fikrini aytishga tez-tez undash kerak. Shunda har bir bola sog'lom rivojlanadi.", "Кроме того, детям с разным характером нужны разные методы. Если ребёнок высокомерен, нужно дать понять, что ещё много знаний предстоит изучить; если он застенчив, часто поощряйте его высказывать мнение. Так каждый ребёнок будет развиваться здорово.", "Ғайр аз ин, барои кӯдакони гуногунхислат усулҳои гуногун лозиманд. Агар кӯдак мағрур бошад, бояд фаҳмад, ки ҳанӯз дониши зиёд омӯхтан лозим; агар шармгин бошад, зуд-зуд ӯро ба гуфтани фикраш ташвиқ кардан лозим. Ҳамин тавр ҳар кӯдак солим рушд мекунад."),
                ],
            },
        ],
    },
    16: {
        "title": "生活可以更美好",
        "goal": {
            "uz": "o'qish/ish rejasi, imkoniyat, rad etish, hozir boshlash va kamtarlik haqida gapirish; 可, 恐怕, 到底, 拿...来说 va 敢 grammatikalarini ishlatish",
            "ru": "говорить о планах учёбы и работы, шансах, отказе, начале сейчас и скромности; использовать 可, 恐怕, 到底, 拿...来说 и 敢",
            "tj": "дар бораи нақшаи таҳсил/кор, имконият, рад кардан, аз ҳозир оғоз кардан ва фурӯтанӣ гуфтугӯ кардан; истифодаи 可, 恐怕, 到底, 拿...来说 ва 敢",
        },
        "intro_text": {
            "uz": "Bu darsda chet elda o'qish hujjatlari, biznesdagi imkoniyat, do'stga odob bilan rad javobi berish, ishni ertaga surmaslik va o'zini xolis baholashni o'rganasiz.",
            "ru": "В этом уроке вы изучите документы для учёбы за рубежом, возможности в бизнесе, вежливый отказ другу, отказ от откладывания дел и трезвую самооценку.",
            "tj": "Дар ин дарс ҳуҷҷатҳои таҳсил дар хориҷ, имконият дар тиҷорат, рад кардани дӯст боодобона, ба фардо нагузоштани кор ва баҳодиҳии воқеии худро меомӯзед.",
        },
        "vocabulary": [
            _word(1, "博士", "bóshì", "n.", "doktorantura darajasi", "доктор наук, докторская степень", "доктор, дараҷаи илмӣ"),
            _word(2, "签证", "qiānzhèng", "n.", "viza", "виза", "раводид"),
            _word(3, "报名", "bào míng", "v.", "ro'yxatdan o'tmoq", "записываться, регистрироваться", "номнавис шудан"),
            _word(4, "表格", "biǎogé", "n.", "forma, jadval", "форма, таблица", "варақа, ҷадвал"),
            _word(5, "传真", "chuánzhēn", "v.", "faks orqali yubormoq", "отправлять факсом", "бо факс фиристодан"),
            _word(6, "号码", "hàomǎ", "n.", "raqam", "номер", "рақам"),
            _word(7, "参观", "cānguān", "v.", "tomosha qilmoq, ko'rib chiqmoq", "посещать, осматривать", "тамошо кардан"),
            _word(8, "激动", "jīdòng", "adj.", "hayajonlangan", "взволнованный", "ҳаяҷонзада"),
            _word(9, "小伙子", "xiǎohuǒzi", "n.", "yigit", "парень, молодой человек", "ҷавонписар"),
            _word(10, "记者", "jìzhě", "n.", "jurnalist", "журналист", "рӯзноманигор"),
            _word(11, "代表", "dàibiǎo", "v.", "ifodalamoq, vakillik qilmoq", "представлять, обозначать", "намояндагӣ кардан, ифода кардан"),
            _word(12, "恐怕", "kǒngpà", "adv.", "ehtimol, qo'rqaman-ki", "боюсь, вероятно", "метарсам ки, эҳтимол"),
            _word(13, "失望", "shīwàng", "v.", "hafsalasi pir bo'lmoq", "разочаровываться", "ноумед шудан"),
            _word(14, "郊区", "jiāoqū", "n.", "shahar cheti", "пригород", "атрофи шаҳр"),
            _word(15, "到底", "dàodǐ", "adv.", "aslida, oxiri", "всё-таки, в конце концов", "охир, аслан"),
            _word(16, "呀", "ya", "part.", "savol ohangini yumshatuvchi zarra", "частица для смягчения вопроса", "ҳиссача барои нарм кардани савол"),
            _word(17, "导游", "dǎoyóu", "n.", "gid", "гид", "роҳбалад"),
            _word(18, "礼貌", "lǐmào", "n.", "odob, xushmuomalalik", "вежливость", "одоб"),
            _word(19, "原谅", "yuánliàng", "v.", "kechirmoq", "прощать", "бахшидан"),
            _word(20, "挂", "guà", "v.", "osmoq; og'izda aylantirmoq", "вешать; держать на устах", "овехтан; ба забон овардан"),
            _word(21, "同情", "tóngqíng", "n./v.", "hamdardlik", "сочувствие, сочувствовать", "ҳамдардӣ"),
            _word(22, "推", "tuī", "v.", "surmoq, kechiktirmoq", "откладывать, отодвигать", "ба таъхир гузоштан"),
            _word(23, "预习", "yùxí", "v.", "oldindan tayyorlanmoq", "готовиться заранее", "пешакӣ тайёрӣ дидан"),
            _word(24, "重点", "zhòngdiǎn", "n.", "asosiy nuqta", "ключевой пункт", "нуқтаи муҳим"),
            _word(25, "马虎", "mǎhu", "adj.", "beparvo, pala-partish", "небрежный", "бепарво"),
            _word(26, "自信", "zìxìn", "adj.", "o'ziga ishongan", "уверенный в себе", "ба худ боварӣ дошта"),
            _word(27, "冷静", "lěngjìng", "adj.", "xotirjam, sovuqqon", "спокойный, хладнокровный", "ором, хунсард"),
            _word(28, "输", "shū", "v.", "yutqazmoq", "проигрывать", "бохтан"),
            _word(29, "重视", "zhòngshì", "v.", "ahamiyat bermoq", "придавать значение", "аҳамият додан"),
            _word(30, "敢", "gǎn", "v.", "jur'at qilmoq", "сметь, решаться", "ҷуръат кардан"),
            _word(31, "尊重", "zūnzhòng", "v.", "hurmat qilmoq", "уважать", "эҳтиром кардан"),
        ],
        "grammar": [
            _grammar(1, "可", "ta'kidlovchi ravish", "усилительная частица/наречие", "равиши таъкидӣ", "Gapning ohangini kuchaytiradi, ayniqsa muammo yoki hayratni ta'kidlaydi.", "Усиливает тон предложения, особенно проблему или удивление.", "Оҳанги ҷумларо пурқувват мекунад, хусусан мушкил ё ҳайратро.", "这可是个大问题，我也不太清楚。", "Zhè kě shì ge dà wèntí, wǒ yě bú tài qīngchu.", "Bu juda katta muammo-ku, men ham aniq bilmayman.", "Это ведь большая проблема, я тоже не очень понимаю.", "Ин воқеан мушкили калон аст, ман ҳам хуб намедонам."),
            _grammar(2, "恐怕", "ehtimol, qo'rqaman-ki", "боюсь, вероятно", "метарсам ки, эҳтимол", "Taxmin bilan birga biroz xavotir bildiradi.", "Выражает предположение с оттенком беспокойства.", "Тахминро бо каме нигаронӣ мефаҳмонад.", "听完我的回答，恐怕你已经知道我的答案了吧。", "Tīngwán wǒ de huídá, kǒngpà nǐ yǐjīng zhīdào wǒ de dá'àn le ba.", "Javobimni eshitgach, ehtimol mening javobimni allaqachon bilgandirsiz.", "Услышав мой ответ, вы, наверное, уже знаете мой ответ.", "Ҷавобамро шунида, эҳтимол ҷавоби маро аллакай донистед."),
            _grammar(3, "到底", "aslida, oxiri", "всё-таки, в конце концов", "охир, аслан", "Savolni chuqurlashtirib, aniq javob talab qiladi.", "Углубляет вопрос и требует точного ответа.", "Саволро амиқ карда, ҷавоби дақиқ мехоҳад.", "你到底怎么打算的呀？", "Nǐ dàodǐ zěnme dǎsuàn de ya?", "Oxiri nima qilmoqchisan o'zi?", "Так что ты всё-таки собираешься делать?", "Охир ту чӣ нақша дорӣ?"),
            _grammar(4, "拿……来说", "...ni misol qilib olsak", "если взять ... как пример", "агар ...-ро мисол гирем", "Tushuntirilayotgan mavzu uchun misolni kiritadi.", "Вводит пример для объясняемой темы.", "Барои фаҳмондани мавзӯъ мисол меорад.", "就拿学汉语来说吧，首先要注意课前预习。", "Jiù ná xué Hànyǔ lái shuō ba, shǒuxiān yào zhùyì kè qián yùxí.", "Xitoy tilini o'rganishni misol qilsak, avvalo darsdan oldin tayyorlanishga e'tibor berish kerak.", "Если взять изучение китайского как пример, сначала нужно готовиться перед уроком.", "Агар омӯзиши чиниро мисол гирем, аввал ба омодагии пеш аз дарс диққат додан лозим."),
            _grammar(5, "敢", "jur'at qilmoq", "сметь, решаться", "ҷуръат кардан", "Fe'l oldida kelib, bir ishni qilishga jur'at yoki ishonch borligini bildiradi.", "Перед глаголом показывает смелость или уверенность сделать что-то.", "Пеш аз феъл омада, ҷуръат ё боварӣ ба иҷрои амалро нишон медиҳад.", "如果你敢诚实地说出自己对哪方面不了解，并不说明自己比别人差。", "Rúguǒ nǐ gǎn chéngshí de shuōchū zìjǐ duì nǎ fāngmiàn bù liǎojiě, bìng bù shuōmíng zìjǐ bǐ biérén chà.", "Agar bilmagan tomoningni rost aytishga jur'at qilsang, bu boshqalardan yomonligingni anglatmaydi.", "Если ты осмелишься честно сказать, чего не понимаешь, это не значит, что ты хуже других.", "Агар ҷуръат карда рост гӯӣ, ки кадом чизро намефаҳмӣ, ин маънои аз дигарон бад буданатро надорад."),
        ],
        "dialogues": [
            {
                "block_no": 1,
                "section_label": "课文 1",
                "scene_uz": "Xiaxia chet elda doktoranturada o'qish hujjatlarini tayyorlaydi",
                "scene_ru": "Сяося готовит документы для докторантуры за рубежом",
                "scene_tj": "Сяося ҳуҷҷатҳои таҳсил дар докторантураи хориҷро омода мекунад",
                "word_nos": [1, 2, 3, 4, 5, 6],
                "grammar_nos": [1],
                "dialogue": [
                    _line("小雨", "你马上就要硕士毕业了吧？将来有什么打算？", "Nǐ mǎshàng jiù yào shuòshì bìyè le ba? Jiānglái yǒu shénme dǎsuàn?", "Tez orada magistraturani bitirasan-a? Kelajakda qanday rejang bor?", "Ты скоро заканчиваешь магистратуру? Какие планы на будущее?", "Ба наздикӣ магистратураро хатм мекунӣ, дуруст? Барои оянда чӣ нақша дорӣ?"),
                    _line("小夏", "我想出国读博士，一直在准备办签证需要的材料。", "Wǒ xiǎng chū guó dú bóshì, yìzhí zài zhǔnbèi bàn qiānzhèng xūyào de cáiliào.", "Men chet elga doktorantura o'qishga bormoqchiman, viza uchun kerakli hujjatlarni tayyorlayapman.", "Я хочу поехать за границу учиться в докторантуре и всё время готовлю материалы для визы.", "Ман мехоҳам барои докторантура ба хориҷ равам ва ҳуҷҷатҳои лозими раводидро омода карда истодаам."),
                    _line("小雨", "现在材料准备得怎么样了？", "Xiànzài cáiliào zhǔnbèi de zěnmeyàng le?", "Hozir hujjatlar tayyorgarligi qanday?", "Как сейчас с подготовкой документов?", "Ҳоло омодагии ҳуҷҷатҳо чӣ хел аст?"),
                    _line("小夏", "成绩证明和护照已经准备好了，另外，还跟国外的大学取得了联系，填写了报名表格。", "Chéngjì zhèngmíng hé hùzhào yǐjīng zhǔnbèi hǎo le, lìngwài, hái gēn guówài de dàxué qǔdé le liánxì, tiánxiě le bào míng biǎogé.", "Baholar ma'lumotnomasi va pasport tayyor, yana chet eldagi universitet bilan aloqa qildim va ro'yxatdan o'tish formasini to'ldirdim.", "Справка об оценках и паспорт уже готовы, кроме того, я связался с зарубежным университетом и заполнил форму регистрации.", "Маълумномаи баҳоҳо ва шиноснома омодаанд, ҳамчунин бо донишгоҳи хориҷӣ тамос гирифтам ва варақаи номнависиро пур кардам."),
                    _line("小雨", "还应该有国外大学给你的邀请信吧？他们把邀请信传真给你了吗？", "Hái yīnggāi yǒu guówài dàxué gěi nǐ de yāoqǐngxìn ba? Tāmen bǎ yāoqǐngxìn chuánzhēn gěi nǐ le ma?", "Chet el universitetidan taklif xati ham bo'lishi kerak-ku? Ular taklif xatini senga faks qildimi?", "Ещё должно быть приглашение от зарубежного университета, верно? Они отправили его тебе факсом?", "Аз донишгоҳи хориҷӣ бояд номаи даъват ҳам бошад, дуруст? Онҳо онро ба ту факс карданд?"),
                    _line("小夏", "没有啊，下个星期我就要去使馆办签证了，这可怎么办？", "Méiyǒu a, xià ge xīngqī wǒ jiù yào qù shǐguǎn bàn qiānzhèng le, zhè kě zěnme bàn?", "Yo'q, keyingi hafta elchixonaga viza olishga borishim kerak, endi nima qilaman?", "Нет, а на следующей неделе мне уже идти в посольство оформлять визу. Что же делать?", "Не, ҳафтаи оянда бояд ба сафорат барои раводид равам, акнун чӣ кор кунам?"),
                    _line("小雨", "这可是个大问题，我也不太清楚。我帮你查一下学校的电话号码，你打电话问一下吧。", "Zhè kě shì ge dà wèntí, wǒ yě bú tài qīngchu. Wǒ bāng nǐ chá yíxià xuéxiào de diànhuà hàomǎ, nǐ dǎ diànhuà wèn yíxià ba.", "Bu juda katta muammo-ku, men ham aniq bilmayman. Men senga maktab telefon raqamini topib beraman, qo'ng'iroq qilib so'rab ko'r.", "Это серьёзная проблема, я тоже не очень знаю. Я помогу найти номер университета, позвони и спроси.", "Ин мушкили калон аст, ман ҳам хуб намедонам. Рақами телефони донишгоҳро ёфта медиҳам, занг зада пурс."),
                ],
            },
            {
                "block_no": 2,
                "section_label": "课文 2",
                "scene_uz": "Wang boshliq Li Jinga muvaffaqiyat tajribasini tushuntiradi",
                "scene_ru": "Босс Ван объясняет Ли Цзиню свой опыт успеха",
                "scene_tj": "Роҳбари Ван ба Ли Ҷин таҷрибаи муваффақияти худро мефаҳмонад",
                "word_nos": [7, 8, 9, 10, 11, 12],
                "grammar_nos": [2],
                "dialogue": [
                    _line("李进", "谢谢您带我参观您的公司。在参观过程中我很激动，有个问题一直想问您。", "Xièxie nín dài wǒ cānguān nín de gōngsī. Zài cānguān guòchéng zhōng wǒ hěn jīdòng, yǒu ge wèntí yìzhí xiǎng wèn nín.", "Kompaniyangizni ko'rsatganingiz uchun rahmat. Tashrif davomida juda hayajonlandim, doim sizdan so'ramoqchi bo'lgan savolim bor.", "Спасибо, что показали мне вашу компанию. Во время осмотра я был очень впечатлён, у меня давно есть вопрос к вам.", "Ташаккур, ки ширкати худро нишон додед. Ҳангоми тамошо хеле ҳаяҷон доштам, саволе дорам, ки дер боз мехостам пурсам."),
                    _line("王老板", "好啊！小伙子，咱们一边吃西瓜，一边聊。", "Hǎo a! Xiǎohuǒzi, zánmen yìbiān chī xīguā, yìbiān liáo.", "Yaxshi! Yigit, keling, tarvuz yeyib gaplashamiz.", "Хорошо! Молодой человек, давай есть арбуз и разговаривать.", "Хуб! Ҷавонписар, биё тарбуз хӯрему суҳбат кунем."),
                    _line("李进", "您从大学毕业开始工作，到现在才十年时间，怎么给公司赚了这么多钱？这让我非常吃惊。我想向您学习一下成功的经验。", "Nín cóng dàxué bìyè kāishǐ gōngzuò, dào xiànzài cái shí nián shíjiān, zěnme gěi gōngsī zhuànle zhème duō qián? Zhè ràng wǒ fēicháng chījīng. Wǒ xiǎng xiàng nín xuéxí yíxià chénggōng de jīngyàn.", "Universitetni bitirib ishlay boshlaganingizga endi o'n yil bo'libdi, kompaniyaga bunchalik ko'p pulni qanday ishlatdingiz? Bu meni juda hayron qoldirdi. Sizdan muvaffaqiyat tajribasini o'rganmoqchiman.", "Вы работаете всего десять лет после университета, как вы заработали для компании столько денег? Это меня очень удивило. Я хочу поучиться у вас опыту успеха.", "Аз хатми донишгоҳ то ҳоло ҳамагӣ даҳ сол шудааст, чӣ тавр барои ширкат ин қадар пул кор кардед? Ин маро хеле ҳайрон кард. Мехоҳам аз таҷрибаи муваффақияти шумо омӯзам."),
                    _line("王老板", "这个问题以前一个记者也问过我。做生意时虽然会遇到各种压力和困难，但是大家的机会都是相同的。", "Zhège wèntí yǐqián yí ge jìzhě yě wèn guo wǒ. Zuò shēngyi shí suīrán huì yùdào gè zhǒng yālì hé kùnnan, dànshì dàjiā de jīhuì dōu shì xiāngtóng de.", "Bu savolni oldin bir jurnalist ham so'ragan. Biznes qilganda turli bosim va qiyinchiliklar bo'ladi, lekin hammaning imkoniyati bir xil.", "Этот вопрос мне раньше задавал один журналист. В бизнесе бывают разные давления и трудности, но возможности у всех одинаковые.", "Ин саволро пештар як рӯзноманигор ҳам пурсид. Дар тиҷорат фишор ва душвориҳои гуногун мешавад, аммо имконияти ҳама якхела аст."),
                    _line("王老板", "你看，这里有三块大小不同的西瓜，我们用西瓜的大小代表钱的多少，要是我们一起开始吃，你会先选哪块？", "Nǐ kàn, zhèlǐ yǒu sān kuài dàxiǎo bù tóng de xīguā, wǒmen yòng xīguā de dàxiǎo dàibiǎo qián de duōshǎo, yàoshi wǒmen yìqǐ kāishǐ chī, nǐ huì xiān xuǎn nǎ kuài?", "Qarang, bu yerda kattaligi har xil uch bo'lak tarvuz bor. Tarvuz kattaligi pul miqdorini ifodalasin. Agar birga yeyishni boshlasak, avval qaysi bo'lakni tanlaysiz?", "Смотри, здесь три куска арбуза разного размера. Пусть размер означает количество денег. Если начнём есть вместе, какой кусок ты выберешь первым?", "Бин, ин ҷо се пора тарбузи ҳаҷмашон гуногун аст. Ҳаҷми тарбуз миқдори пулро ифода кунад. Агар якҷо хӯрданро сар кунем, аввал кадом пораро интихоб мекунӣ?"),
                    _line("李进", "我肯定先吃最大的一块了，难道您会先吃小的，放弃吃大块的机会吗？", "Wǒ kěndìng xiān chī zuì dà de yí kuài le, nándào nín huì xiān chī xiǎo de, fàngqì chī dà kuài de jīhuì ma?", "Men albatta eng kattasini birinchi yeyman. Nahotki siz kichigini yeb, katta bo'lak imkoniyatidan voz kechsangiz?", "Я, конечно, сначала съем самый большой. Неужели вы сначала возьмёте маленький и откажетесь от шанса съесть большой?", "Ман албатта аввал калонтаринро мехӯрам. Наход шумо аввал хурдро хӯрда, аз имкони пораи калон даст мекашед?"),
                    _line("王老板", "我会先吃最小的一块，因为在你没吃完最大的那块时，我还有时间再多吃一块，最后一定比你吃的西瓜多。听完我的回答，恐怕你已经知道我的答案了吧。", "Wǒ huì xiān chī zuì xiǎo de yí kuài, yīnwèi zài nǐ méi chīwán zuì dà de nà kuài shí, wǒ hái yǒu shíjiān zài duō chī yí kuài, zuìhòu yídìng bǐ nǐ chī de xīguā duō. Tīngwán wǒ de huídá, kǒngpà nǐ yǐjīng zhīdào wǒ de dá'àn le ba.", "Men avval eng kichigini yeyman, chunki siz eng kattasini tugatguningizcha, men yana bir bo'lak yeyishga ulguraman va oxirida sizdan ko'proq tarvuz yeyman. Javobimni eshitgach, ehtimol mening javobimni bilib oldingiz.", "Я сначала съем самый маленький, потому что пока ты не доешь самый большой, я успею съесть ещё один кусок и в итоге съем больше. Услышав мой ответ, ты, наверное, уже понял мой ответ.", "Ман аввал хурдтаринро мехӯрам, чун то ту калонтаринро тамом кунӣ, ман боз як пора хӯрда метавонам ва дар охир аз ту зиёдтар мехӯрам. Ҷавобамро шунида, эҳтимол ҷавобамро фаҳмидӣ."),
                ],
            },
            {
                "block_no": 3,
                "section_label": "课文 3",
                "scene_uz": "Xiao Lin do'stini rad etishga uyaladi",
                "scene_ru": "Сяо Лин стесняется отказать другу",
                "scene_tj": "Сяо Лин аз рад кардани дӯст шарм медорад",
                "word_nos": [13, 14, 15, 16, 17, 18, 19],
                "grammar_nos": [3],
                "dialogue": [
                    _line("小林", "今年放假我又回不了家了，这次我父母又要失望了。你有什么计划？", "Jīnnián fàng jià wǒ yòu huí bu liǎo jiā le, zhè cì wǒ fùmǔ yòu yào shīwàng le. Nǐ yǒu shénme jìhuà?", "Bu yil ta'tilda yana uyga qaytolmayman, ota-onam yana hafsalasi pir bo'ladi. Sening qanday rejang bor?", "В этом году на каникулах я опять не смогу поехать домой, родители снова расстроятся. Какие у тебя планы?", "Имсол дар таътил боз ба хона рафта наметавонам, падару модарам боз ноумед мешаванд. Ту чӣ нақша дорӣ?"),
                    _line("小李", "我计划去郊区住一个月。你不是已经买好火车票了吗？你到底怎么打算的呀？", "Wǒ jìhuà qù jiāoqū zhù yí ge yuè. Nǐ bú shì yǐjīng mǎi hǎo huǒchēpiào le ma? Nǐ dàodǐ zěnme dǎsuàn de ya?", "Men shahar chetiga bir oy yashashga borishni rejalayapman. Sen poyezd chiptasini olib bo'lgan eding-ku? Oxiri nima qilmoqchisan?", "Я планирую пожить месяц в пригороде. Ты ведь уже купил билет на поезд? Так что ты всё-таки собираешься делать?", "Ман нақша дорам як моҳ дар атрофи шаҳр зиндагӣ кунам. Ту билетро харида будӣ-ку? Охир чӣ нақша дорӣ?"),
                    _line("小林", "昨天一个外地的好朋友打电话说要来旅游，让我当导游，我实在不好意思拒绝。", "Zuótiān yí ge wàidì de hǎo péngyou dǎ diànhuà shuō yào lái lǚyóu, ràng wǒ dāng dǎoyóu, wǒ shízài bù hǎoyìsi jùjué.", "Kecha boshqa joydagi yaxshi do'stim qo'ng'iroq qilib, sayohatga kelishini va menga gid bo'lishimni aytdi. Rostdan rad etishga uyalayapman.", "Вчера хороший друг из другого города позвонил и сказал, что приедет путешествовать и хочет, чтобы я был гидом. Мне правда неудобно отказать.", "Дирӯз як дӯсти наздики берун аз шаҳр занг зада гуфт, ки барои саёҳат меояд ва мехоҳад ман роҳбалад шавам. Ростӣ рад кардан бароям нороҳат аст."),
                    _line("小李", "其实拒绝并不表示不愿意帮忙。遇到解决不了的问题或者无法完成的任务时，拒绝正好说明你对朋友负责。这也是对你父母负责的态度。", "Qíshí jùjué bìng bù biǎoshì bù yuànyì bāng máng. Yùdào jiějué bu liǎo de wèntí huòzhě wúfǎ wánchéng de rènwu shí, jùjué zhènghǎo shuōmíng nǐ duì péngyou fùzé. Zhè yě shì duì nǐ fùmǔ fùzé de tàidu.", "Aslida rad etish yordam bermoqchi emasligingni bildirmaydi. Hal qilib bo'lmaydigan muammo yoki bajarib bo'lmaydigan vazifa bo'lsa, rad etish do'stga mas'uliyatli ekaningni ko'rsatadi. Bu ota-onang oldidagi mas'uliyat ham.", "На самом деле отказ не означает нежелание помочь. Если проблема нерешаемая или задача невыполнимая, отказ как раз показывает ответственность перед другом. Это также ответственное отношение к родителям.", "Дар асл рад кардан маънои ёрӣ додан нахостанро надорад. Агар мушкил ҳалнашаванда ё вазифа иҷронашаванда бошад, рад кардан масъулият ба дӯстро нишон медиҳад. Ин ҳам муносибати масъулона ба падару модар аст."),
                    _line("小林", "既然别人找我帮忙，说明他真的很需要我的帮助。我担心要是说“不”的话，会让他误会和伤心。", "Jìrán biérén zhǎo wǒ bāng máng, shuōmíng tā zhēn de hěn xūyào wǒ de bāngzhù. Wǒ dānxīn yàoshi shuō “bù” dehuà, huì ràng tā wùhuì hé shāngxīn.", "Modomiki u mendan yordam so'ragan ekan, demak u haqiqatan yordamimga muhtoj. \"Yo'q\" desam, noto'g'ri tushunib, xafa bo'lishidan qo'rqaman.", "Раз он обратился ко мне за помощью, значит ему правда нужна моя помощь. Я боюсь, что если скажу «нет», он неправильно поймёт и расстроится.", "Модом ки ӯ аз ман ёрӣ хост, демак воқеан ба кӯмакам ниёз дорад. Метарсам агар «не» гӯям, нодуруст мефаҳмад ва меранҷад."),
                    _line("小李", "别担心！如果你用一个既合适又礼貌的方法告诉朋友，他一定会原谅你的。", "Bié dānxīn! Rúguǒ nǐ yòng yí ge jì héshì yòu lǐmào de fāngfǎ gàosu péngyou, tā yídìng huì yuánliàng nǐ de.", "Xavotir olma! Agar do'stingga mos va odobli usulda aytsang, u albatta seni kechiradi.", "Не волнуйся! Если ты скажешь другу подходящим и вежливым способом, он обязательно тебя простит.", "Хавотир нашав! Агар бо роҳи мувофиқ ва боодобона ба дӯстат гӯӣ, ӯ ҳатман туро мебахшад."),
                ],
            },
            {
                "block_no": 4,
                "section_label": "课文 4",
                "scene_uz": "Ishni ertaga surmaslik va xitoy tilini o'rganish haqida matn",
                "scene_ru": "Текст о том, как не откладывать дела и учить китайский",
                "scene_tj": "Матн дар бораи ба фардо нагузоштани кор ва омӯзиши чинӣ",
                "word_nos": [20, 21, 22, 23, 24, 25, 26],
                "grammar_nos": [4],
                "dialogue": [
                    _line("旁白", "有些同学经常把“明天”和“将来”挂在嘴边，常说作业明天再完成，下次考试一定好好儿复习，等等。", "Yǒuxiē tóngxué jīngcháng bǎ “míngtiān” hé “jiānglái” guà zài zuǐ biān, cháng shuō zuòyè míngtiān zài wánchéng, xià cì kǎoshì yídìng hǎohāor fùxí, děngděng.", "Ba'zi o'quvchilar \"ertaga\" va \"kelajakda\" degan gaplarni og'zidan tushirmaydi: vazifani ertaga qilaman, keyingi imtihonga yaxshilab tayyorlanaman va hokazo.", "Некоторые ученики постоянно говорят «завтра» и «в будущем»: домашку сделаю завтра, к следующему экзамену обязательно хорошо подготовлюсь и так далее.", "Баъзе донишҷӯён «пагоҳ» ва «оянда»-ро аз даҳон намемонанд: вазифаро пагоҳ мекунам, ба имтиҳони оянда хуб тайёр мешавам ва ғайра."),
                    _line("旁白", "这种态度会浪费时间，不但会让你到最后什么事情都做不成，而且还得不到别人的同情。", "Zhè zhǒng tàidu huì làngfèi shíjiān, bùdàn huì ràng nǐ dào zuìhòu shénme shìqing dōu zuò bù chéng, érqiě hái dé bu dào biérén de tóngqíng.", "Bunday munosabat vaqtni isrof qiladi; oxirida hech narsani tugata olmay qolasan va boshqalarning hamdardligini ham olmaysan.", "Такое отношение тратит время: в итоге ничего не сделаешь и даже не получишь сочувствия.", "Ин муносибат вақтро беҳуда мекунад: дар охир ҳеҷ корро анҷом дода наметавонӣ ва ҳамдардии дигаронро ҳам намегирӣ."),
                    _line("旁白", "所以不要把什么事情都推到“明天”，一切从现在做起。", "Suǒyǐ búyào bǎ shénme shìqing dōu tuīdào “míngtiān”, yíqiè cóng xiànzài zuòqǐ.", "Shuning uchun hamma ishni \"ertaga\"ga surma, hammasini hozirdan boshlagin.", "Поэтому не откладывай всё на «завтра», начинай всё сейчас.", "Бинобар ин ҳама корро ба «пагоҳ» нагузор, ҳама чизро аз ҳозир оғоз кун."),
                    _line("旁白", "就拿学汉语来说吧，首先要注意课前预习，找出第二天要学习的重点；其次，上课时要认真听，不能马虎；最后，课后要记得复习。只要这样，汉语就能越学越好，越说越自信。", "Jiù ná xué Hànyǔ lái shuō ba, shǒuxiān yào zhùyì kè qián yùxí, zhǎochū dì-èr tiān yào xuéxí de zhòngdiǎn; qícì shàng kè shí yào rènzhēn tīng, bù néng mǎhu; zuìhòu, kè hòu yào jìde fùxí. Zhǐyào zhèyàng, Hànyǔ jiù néng yuè xué yuè hǎo, yuè shuō yuè zìxìn.", "Xitoy tilini o'rganishni misol qilsak, avval darsdan oldin tayyorlanib, ertangi mavzuning asosiy joylarini topish kerak; keyin darsda diqqat bilan tinglash, beparvo bo'lmaslik kerak; oxirida darsdan keyin takrorlash kerak. Shunda xitoy tili tobora yaxshi o'rganiladi va gapirgan sari ishonch ortadi.", "Если взять изучение китайского, сначала нужно готовиться перед уроком и находить ключевые места следующего занятия; затем внимательно слушать на уроке, не быть небрежным; наконец, после урока повторять. Только так китайский будет становиться всё лучше, а речь увереннее.", "Агар омӯзиши чиниро мисол гирем, аввал пеш аз дарс тайёрӣ дида, нуқтаҳои муҳими дарси ояндаро ёфтан лозим; баъд дар дарс бодиққат гӯш кардан, бепарво набудан; охир баъди дарс такрор кардан. Ҳамин тавр чинӣ рӯз ба рӯз беҳтар ва гуфтор боэътимодтар мешавад."),
                ],
            },
            {
                "block_no": 5,
                "section_label": "课文 5",
                "scene_uz": "A'lo bo'lganda ham xotirjam va kamtar qolish haqida matn",
                "scene_ru": "Текст о спокойствии и скромности, даже когда ты силён",
                "scene_tj": "Матн дар бораи оромӣ ва фурӯтанӣ ҳатто вақте беҳтарин ҳастӣ",
                "word_nos": [27, 28, 29, 30, 31],
                "grammar_nos": [5],
                "dialogue": [
                    _line("旁白", "当你认为自己在哪方面很优秀时，千万要冷静，不要骄傲。", "Dāng nǐ rènwéi zìjǐ zài nǎ fāngmiàn hěn yōuxiù shí, qiānwàn yào lěngjìng, búyào jiāo'ào.", "Qaysidir sohada o'zingni juda yaxshi deb bilsang, albatta xotirjam bo'l, kibr qilma.", "Когда считаешь себя сильным в какой-то области, обязательно сохраняй спокойствие и не гордись.", "Вақте худро дар ягон соҳа хеле хуб медонӣ, ҳатман ором бош ва мағрур нашав."),
                    _line("旁白", "因为这个世界很大，“天外有天，人外有人”，很可能有人在这方面比你更厉害。你现在是第一，并不表示你永远都是第一。", "Yīnwèi zhège shìjiè hěn dà, “tiān wài yǒu tiān, rén wài yǒu rén”, hěn kěnéng yǒu rén zài zhè fāngmiàn bǐ nǐ gèng lìhai. Nǐ xiànzài shì dì-yī, bìng bù biǎoshì nǐ yǒngyuǎn dōu shì dì-yī.", "Chunki dunyo juda katta, \"osmon ustida osmon, odam ustida odam bor\"; ehtimol bu sohada sendan ham kuchliroq odam bordir. Hozir birinchi bo'lishing doim birinchi bo'lasan degani emas.", "Мир огромен: «за небом есть небо, среди людей есть более сильные». Возможно, кто-то в этой области сильнее тебя. То, что ты сейчас первый, не значит, что всегда будешь первым.", "Зеро дунё хеле калон аст: «болои осмон осмон, миёни одамон одам ҳаст». Эҳтимол касе дар ин соҳа аз ту зӯртар бошад. Ҳоло якум буданат маънои ҳамеша якум буданро надорад."),
                    _line("旁白", "就像比赛一样，没有人会永远输，也没有人会一直赢。我们知道的越多，就会发现自己不懂的也越多。", "Jiù xiàng bǐsài yíyàng, méiyǒu rén huì yǒngyuǎn shū, yě méiyǒu rén huì yìzhí yíng. Wǒmen zhīdào de yuè duō, jiù huì fāxiàn zìjǐ bù dǒng de yě yuè duō.", "Musobaqadek: hech kim abadiy yutqazmaydi, hech kim doim yutmaydi. Qancha ko'p bilsak, bilmaydigan narsamiz ham shuncha ko'p ekanini ko'ramiz.", "Как в соревновании: никто не проигрывает вечно и никто не выигрывает всегда. Чем больше мы знаем, тем больше понимаем, чего не знаем.", "Мисли мусобиқа: ҳеҷ кас ҳамеша намебозад ва ҳеҷ кас ҳамеша намебарад. Ҳар қадар бештар донем, ҳамон қадар бештар мефаҳмем, ки намедонем."),
                    _line("旁白", "我们应该重视平时的积累，多向周围的人学习。如果你敢诚实地说出自己对哪方面不了解，并不说明自己比别人差，相反，这样做更能得到别人的尊重。", "Wǒmen yīnggāi zhòngshì píngshí de jīlěi, duō xiàng zhōuwéi de rén xuéxí. Rúguǒ nǐ gǎn chéngshí de shuōchū zìjǐ duì nǎ fāngmiàn bù liǎojiě, bìng bù shuōmíng zìjǐ bǐ biérén chà, xiāngfǎn, zhèyàng zuò gèng néng dédào biérén de zūnzhòng.", "Kundalik to'plash va o'rganishga ahamiyat berib, atrofdagilardan ko'proq o'rganishimiz kerak. Agar bilmagan tomoningni rost aytishga jur'at qilsang, bu boshqalardan yomonligingni bildirmaydi; aksincha, shunday qilish boshqalarning hurmatini ko'proq keltiradi.", "Нужно ценить повседневное накопление и больше учиться у окружающих. Если ты осмелишься честно сказать, чего не понимаешь, это не значит, что ты хуже других; наоборот, так легче получить уважение.", "Бояд ба ҷамъ кардани дониш дар рӯзҳои одӣ аҳамият диҳем ва аз атрофиён бештар омӯзем. Агар ҷуръат карда рост гӯӣ, ки чӣ чизро намефаҳмӣ, ин маънои аз дигарон бад буданатро надорад; баръакс, чунин кор эҳтироми дигаронро бештар меорад."),
                ],
            },
        ],
    },
}
